### ISSUE TITLE
V0.98 - PDF image is broken or in an unknown format

### ISSUE THREAD

**Issue by sbertrand-witekio** [rst2pdf/rst2pdf#1007]
Including pdf images fails `.. image:: image.pdf`

```
rst2pdf test.rst
[ERROR] image.py:285 The image (C:\Work\test-rst2pdf\image.pdf, near line 4 in file test.rst) is broken or in an unknown format
```
Environment :
- rst2pdf 0.98
- Python 3.8.6

When using version 0.97, the image inclusion works.

```
$ pip install rst2pdf==0.97
$ rst2pdf test.rst
# No error and the generated pdf has the image
```

**Comment by sbertrand-witekio** [comment]
This is a change in v0.98, not an issue.
https://github.com/rst2pdf/rst2pdf/pull/896

**Comment by lornajane** [comment]
I'm sorry to say that we no longer have support for PDF-format images in rst2pdf, as a result of a dependency problem that we couldn't find another solution to. I'd recommend converting the image format if possible .... it took me so long to type this that you've already found the problem and closed the issue :)
