### ISSUE TITLE
RST file errors or warnings to cause non-zero exit code

### ISSUE THREAD

**Issue by pawelszramowski** [rst2pdf/rst2pdf#1009]
**Feature request**
It would be great if rst2pdf could return a non-zero exit code if any errors or warnings were encountered while processing the RST file if it was enabled by the user using a command-line argument(s). Currently, it only seems to do it in case of critical errors:
```batch
>rst2pdf non_existent_file && echo PASS || echo FAIL
[ERROR] createpdf.py:1406 [Errno 2] No such file or directory: 'non_existent_file'
FAIL
```
and not if it wasn't able to generate a reasonable file:
```batch
>rst2pdf malformed.rst && echo PASS || echo FAIL
malformed.rst:1: (ERROR/3) Malformed table.

+----------+----------+
| Header 1 | Header 2 |
+==========+===========+
| Cell 1   | Cell 2   |
+----------+----------+
PASS
```
(`malformed.pdf` is empty.)

This would make easier it to use it as an RST quality gatekeeper in projects that do not otherwise process RST files. Currently, I have had to resort to detecting that rst2pdf has printed anything to the standard error stream, however, this is a bit unreliable; parsing stderr would be even worse.

🖥 **Versions**py -3 -V
Python 3.9.1
py -3 -m pip freeze | grep rst2pdf
rst2pdf==0.97
py -3 -m pip freeze | grep reportlab
reportlab==3.5.66

Which operating system are you using?
Windows 10

**Comment by akrabat** [comment]
This has been fixed in https://github.com/rst2pdf/rst2pdf/pull/925. We'lll try and get a release out soon-ish.
