### ISSUE TITLE
How to make pdf without command or python enveriment?

### ISSUE THREAD

**Issue by Universe-Liu** [rst2pdf/rst2pdf#1011]
I need to use pyinstaller to pick a program which is used to make a pdf with rst2pdf.
However, this program maybe need to run on a computer without python.
How to make pdf without command or python enveriment?
 I mean just like pyqt5 or others. We can use it by import,

**Comment by stephenfin** [comment]
This is out of scope for us. There's nothing unusual about rst2pdf. A solution that allows you to generate packaged exe files with the interpreter included should work for all python libraries including `rst2pdf`. I suggest you investigate this.
