### ISSUE TITLE
Unclear requirements

### ISSUE THREAD

**Issue by dvzrv** [rst2pdf/rst2pdf#1015]
When trying to package rst2pdf 0.98 for Arch Linux I have a hard time figuring out which dependencies are actually required.
I require rst2pdf to build scons (https://github.com/SCons/scons/issues/3769).

**Description of problem**
I am trying to package rst2pdf as a system package and follow [requirements.in](https://github.com/rst2pdf/rst2pdf/blob/d9bf8cd737c11cfc572c936173228c1103344fdf/requirements.in) and [setup.py](https://github.com/rst2pdf/rst2pdf/blob/d9bf8cd737c11cfc572c936173228c1103344fdf/setup.py) to figure out what is required during runtime, what is a test dependency and what is actually not required.

In setup.py we have as (install) dependencies:
* docutils
* importlib_metadata
* jinja2
* packaging
* pygments
* reportlab
* smartypants

and as extras:
 * pypdf2 (test)
 * pymupdf (test)
 * sphinx (sphinx)
 * wordaxe (hyphenation)
 * svglib (svg support)
 * aafigure (ASCII images)
 * matplotlib (math support)
 * xhtml2pdf (raw HTML support)

In requirements.in we have
* aafigure
* docutils
* matplotlib
* pygments
* pyPdf2
* reportlab
* smartypants
* sphinx
* svglib
* svg2rlg
* xhtml2pdf

The following are unclear to me:

* requirements.in states e.g. `svg2rlg`, but this is never mentioned in setup.py (what is it used for? is it needed?)
* setup.py states `importlib_metadata`, `jinja2`, `packaging`, `pymupdf` and `wordaxe` but this is never mentioned in requirements.in (are all of them needed?)
* Additionally I [can not find wordaxe anywhere on pypi.org](https://pypi.org/search/?q=wordaxe)(?).

In the [.gitlab-ci.yml](https://github.com/rst2pdf/rst2pdf/blob/d9bf8cd737c11cfc572c936173228c1103344fdf/.gitlab-ci.yml#L4) we have the test requirements:
* nose
* coverage
 
The above (if actually in use) can be added to the relevant entry in `setup()`'s `extras_require` or to a separate requirements file.

(updated to add travis.yml information below)
In the [.travis.yml](https://github.com/rst2pdf/rst2pdf/blob/d9bf8cd737c11cfc572c936173228c1103344fdf/.travis.yml#L8-L19) we have system packages, that are seemingly required:

* dvipng
* plantuml
* texlive-latex-base

These system packages should be documented as a requirement for the test environment, as without them it seems that tests are failing (at the time of writing I am still at 24 failing tests, probably due to missing dependencies or other issues).

Additionally, the file states that `pytest` is used for the test environment.

**What is the expected output? What do you see instead?**

I would expect a clearer and more explicit definition of what is required for:
* building the software
* testing the software
* running the software
* running any optional features of the software

🖥 **Versions**

Python 3.9.6
rst2pdf 0.98
reportlab 3.5.68
sphinx 4.0.3

Which operating system are you using?

Arch Linux

**Additional information**

A clear definition of what is required to build, test and run a software is the cornerstone of a good system integration on downstream distributions (such as a Linux distribution).
Without it, packagers are less likely to get things right, are more likely to spend a lot of time researching, not to run tests and therefore it is also more likely to expose you as an upstream project to users with issues due to integration problems.

**Comment by lornajane** [comment]
Thanks for asking about this, there are some really good points here. We're non-python-specialist maintainers who inherited an existing project so there are some things we either don't know or haven't fixed yet! I think `requirements.txt` is a good representation of what I think the dependencies are, in particular we're pinned to an old version of Sphinx. I'll keep this issue open as this does definitely need improvement, especially for those packaging the project.

**Comment by lornajane** [comment]
Adding information as I find it in case it helps (but I'll do a final update with everything in it once I get through all the details). So far:
 - we don't use gitlab CI, I'll remove the file. We don't use travis any more either, similarly I'll tidy that up. The CI is now all in github actions, which might make things clearer or (very likely since it was a direct port from our travis setup) might not.
 - we do now use pytest, so nose shouldn't be needed, I'm not sure about coverage but either @nfraprado or @akrabat may know
 - wordaxe is no longer supported and rst2pdf now uses pyphen
 - svg2rlg is used by the SVG support
 - plantuml is required if you want to support UML diagrams, but I think the package should build without it and be able to do everything except UML

**Comment by akrabat** [comment]
0.98 is a little old now and we really need a 0.99 out. We'll do that when #1020 is merged.

The rest of my comment applies to `master`.

**Installing rst2pdf**

I think that the way it should work for a user of rst2pd with a checkout of the codebase:

1. `pip install .` should install a minimal working installation of rst2pdf.
2. `pip install .[aafiguresupport,mathsupport,rawhtmlsupport,sphinx,svgsupport]` will install rst2pdf with all options.

For running the tests on a checkout of the codebase we need a specific set of dependencies, so for testing we use `requirements.txt`:

```
pip install -r requirements.txt
pip install -e .[aafiguresupport,mathsupport,rawhtmlsupport,sphinx,svgsupport,tests]
pytest
```

Though practically, `pip install -e .[tests]` would also work as the extras should not install any additional dependencies. 

So from this, what should be the case is that `pip install -r requirements.txt` should be practically the same as `pip install .[aafiguresupport,mathsupport,rawhtmlsupport,sphinx,svgsupport]` in terms of packages installed (different versions though).

Note that for successful development where you are going to raise a PR, you also need `pip install pre-commit` for the pre-commit hooks to ensure that the code is formatted properly, etc.

**Dependencies**

* `jinja2`, `importlib_metadata` & `packaging` should be in `requirements.in` as they are required by the base installation of rst2pdf.
* `svg2rlg` should not be in `requirements.in` as it is no longer used.
* `pyPdf2` should not be in `requirements.in` as it is not a direct requirement (needed for rawhtml or tests only).
* `pytest` should be in `extra_require` => `"tests"` within `setup.py` as that's how we run the tests.

**Continuous Integration**

GitHub Actions run CI via `.github/workflows/ci.yml`. Hence `.travis.yml` and `.gitlab-ci.yml` are obsolete.

**Next step**

I will raise a PR to hopefully get this all straighter!

**Comment by akrabat** [comment]
PR #1021 should make everything more consistent.

**Comment by akrabat** [comment]
I think this is now addressed with the changes on `master`. @dvzrv, do we need to do anything else?

**Comment by dvzrv** [comment]
@akrabat Sorry for the late response. Too many other things...

So, while the dependency declarations seem fine all fine to me now (thanks! :) ), I am still left with 16 failing tests:

```
=========================== short test summary info ============================
FAILED rst2pdf/tests/input/test_box_widths.rst::test_box_widths
FAILED rst2pdf/tests/input/test_header_footer_in_stylesheet.rst::test_header_footer_in_stylesheet
FAILED rst2pdf/tests/input/test_issue_110.rst::test_issue_110
FAILED rst2pdf/tests/input/test_issue_110_2.rst::test_issue_110_2
FAILED rst2pdf/tests/input/test_issue_110_3.rst::test_issue_110_3
FAILED rst2pdf/tests/input/test_issue_126.rst::test_issue_126
FAILED rst2pdf/tests/input/test_issue_261.rst::test_issue_261
FAILED rst2pdf/tests/input/test_issue_274_2.rst::test_issue_274_2
FAILED rst2pdf/tests/input/test_issue_288.rst::test_issue_288
FAILED rst2pdf/tests/input/test_issue_295.rst::test_issue_295
FAILED rst2pdf/tests/input/test_preprocessor.rst::test_preprocessor
FAILED rst2pdf/tests/input/test_raw_html.rst::test_raw_html
FAILED rst2pdf/tests/input/test_stylesheet_includes.rst::test_stylesheet_includes
FAILED rst2pdf/tests/input/test_table_in_header.rst::test_table_in_header
FAILED rst2pdf/tests/input/test_uml_extension.rst::test_uml_extension
FAILED rst2pdf/tests/input/sphinx-footnotes-order/conf.py::sphinx-footnotes-order
============ 16 failed, 275 passed, 22 skipped in 169.21s (0:02:49) ============
```
Full build log: 
[rst2pdf-0.99-build.log](https://github.com/rst2pdf/rst2pdf/files/7981256/rst2pdf-0.99-build.log)


This might be due to the fact, that I do not yet have python-xhtml2pdf in the build/test environment (I'm currently waiting for a new release after https://github.com/xhtml2pdf/xhtml2pdf/issues/560 has settled).
For me it is unfortunately a bit hard to evaluate whether these failing tests have anything to do with that or not. It would be appreciated if you could have a quick look at the pytest output in the attached build log! :)
If this is the case I'll likely ignore those failing tests for now and ship 0.99 as is.

**Comment by sarnold** [comment]
I have a document workflow using `rst2pdf[svgsupport]` in the tox file and the resulting PDF has a broken image box where the .svg logo should be.  Tox is just installing from PyPI so I'm not sure what the answer is.

I remember this *did* work not too long ago, but that was an OS package and not from PyPI.  The work flow is actually a template so it's super simple, and sadly it does not generate any errors except in my eyeballs.  All the bits are here: https://github.com/VCTLabs/software_user_manual_template

Thanks!

**Comment by sarnold** [comment]
That ^^ is apparently pillow barfing:
```
>>> PILImage.open('sum/images/ACME_Logo.png')
<PIL.PngImagePlugin.PngImageFile image mode=RGBA size=2400x1102 at 0xFFFF8C09B350>
>>> PILImage.open('sum/images/ACME_Logo.svg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nerdboy/src/sum_did_format/.tox/build/lib/python3.11/site-packages/PIL/Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'sum/images/ACME_Logo.svg'
```
Needless to say, that svg file displays fine and inkscape does not clean anything.

**Comment by sarnold** [comment]
At least the "Unclear" seems to be accurate, as pillow has an open bug about SVG support for a long time now.  What exactly is the expectation for rst2pdf?  Is there a backend  that works with svg or is it intended to fall back to pillow in spite of the lack of SVG support?  it feels like something really fell through the cracks here but I have no idea what it is yet...

**Comment by lornajane** [comment]
After merging #1242 to switch our dependencies/requirements setup to `uv`, I think this issue is too outdated to be useful. I'll therefore close it BUT please do open new issues if there's anything that still seems unclear or anything we can do to help with packaging.
