### ISSUE TITLE
In createpdf.py dest=breaklevel should be dest=break_level

### ISSUE THREAD

**Issue by carakel** [rst2pdf/rst2pdf#1022]
It looks like this code as a misnamed parameter for dest - 

    def_break = config.getValue("general", "break_level", 0)
    parser.add_option(
        '-b',
        '--break-level',
        dest='breaklevel',

**Description of problem**

Setting pdf_break_level to 1 in Sphinx conf.py didn't seem to do anything so I scanned the code.

**What is the expected output? What do you see instead?**

🖥 **Versions**

`python -V`

`pip freeze | grep rst2pdf`

`pip freeze | grep reportlab`

`pip freeze | grep Sphinx`

Which operating system are you using?

**Additional information**

**Comment by akrabat** [comment]
In Sphinx, the configuration section is defined as `pdf_break_level` as per [this line](https://github.com/rst2pdf/rst2pdf/blob/377ab8f2f67666e237f44a272b3d0a4caafdc1d5/rst2pdf/pdfbuilder.py#L98):

```python
breaklevel=opts.get('pdf_break_level', self.config.pdf_break_level),
```

To see how it works, consider this `index.rst`:

```rst
rst2pdf Sphinx pdf_break_level test
###################################

This test looks at what the pdf_break_level option does.

* ``pdf_break_level = 0``: Everything is on a single page.
* ``pdf_break_level = 1``: A new page after each section, but not sub-section
* ``pdf_break_level = 2``: A new page after each section, *and* sub-section

The next section
################

This is the next section of the document. This will be on a new page if ``pdf_break_level >= 1``.

The first sub-section
=====================

This is the first sub-section of the *next section*. This will be on a new page if ``pdf_break_level >= 2``.

The second sub-section
======================

This is the second sub-section of the *next section*. This will be on a new page if ``pdf_break_level >= 2``.

The section after next
######################

This is the section after next of the document. This will be on a new page if ``pdf_break_level >= 1``.

Another first sub-section
=========================

This is the first sub-section of the *section after next*. This will be on a new page if ``pdf_break_level >= 2``.

Another second sub-section
==========================

This is the second sub-section of the *section after next*. This will be on a new page if ``pdf_break_level >= 2``.
```

And this `conf.py` file:

```
# -- General configuration -----------------------------------------------------
extensions = ['rst2pdf.pdfbuilder']
master_doc = 'index'

# -- Options for PDF output ----------------------------------------------------
# Grouping the document tree into PDF files (source start file, target file name, title, author).
pdf_documents = [('index', 'BreakLevel_2', 'Break Level Test', 'Rob Allen')]

pdf_stylesheets = ['sphinx']
pdf_use_toc = False
pdf_use_index = False
pdf_use_modindex = False
pdf_use_coverpage = False
pdf_invariant = True
pdf_breakside = 'any'

pdf_break_level = 2
```

From the directory with these two files in, build with:

```
sphinx-build -b pdf . ./pdf
```

This will create `pdf/BreakLevel_2.pdf`. Change `pdf_break_level = 2` and the filename in `pdf_documents` to generate for `pdf_break_level`s of 0 and 1. You will now have three PDF files: `BreakLevel_0.pdf`, `BreakLevel_1.pdf` & `BreakLevel_1.pdf`. 

If you compare them, you'll see how it works.

I've also attached the three files that I get.

[BreakLevel_0.pdf](https://github.com/rst2pdf/rst2pdf/files/7075434/BreakLevel_0.pdf)
[BreakLevel_1.pdf](https://github.com/rst2pdf/rst2pdf/files/7075435/BreakLevel_1.pdf)
[BreakLevel_2.pdf](https://github.com/rst2pdf/rst2pdf/files/7075437/BreakLevel_2.pdf)

**Comment by carakel** [comment]
I see that my issue is that I am wanting it to work across multiple rst files which are included within the index.rst file.    I divided the content in the index.rst between index2.rst and index3.rst and then reference index2 and index3 in index.rst.  I was hoping it would insert page breaks between each section found within each rst file.

index.rst:

Break Test  
==========


..
    Contents
..
    ========

.. toctree::
      :maxdepth: 2
   :caption: Contents:


   index2

   index3

**Comment by lornajane** [comment]
rst2pdf doesn't take account of where the file boundaries are, the include directive gets parsed and then the resulting rst gets turned into a PDF. What it can do is add page breaks at a particular level of heading - which is what the demonstration above, and the tests that are added in #1023 show. Does that help?
