### ISSUE TITLE
[ERROR] createpdf.py:1134 Template 'twoColumn' is not defined

### ISSUE THREAD

**Issue by foolcage** [rst2pdf/rst2pdf#1061]
```
os: mac os 10.15.7
python: 3.8
Name: rst2pdf
Version: 0.99

```

**Comment by akrabat** [comment]
`twoColumn` is no longer part of the default styles in 0.99, so you now need to explicitly include the twoColumn style file.

For stock rst2pdf, you'd use `-s twocolumn` and for Sphinx, it's `pdf_stylesheets = ['twocolumn']`

**Comment by foolcage** [comment]
@akrabat thanks a lot!
