### ISSUE TITLE
Disable blank page after Title page and TOC (sphinx)

### ISSUE THREAD

**Issue by Sponge5** [rst2pdf/rst2pdf#1073]
Hi, I've looked through the sphinx's `conf.py` example and `sphinx.yaml` and couldn't find a way to disable empty pages after the Title page and TOC page. I've browsed through the issues here and on the sphinx project and didn't find anyone with the same problem, that's why I'm creating a new issue. Is there a simple way to do this?

Also, in `conf.py`, there's an array of styles that I can configure, are those the only ones that will be used? I searched for keyword `empty` in `rst2pdf/styles` and found references to `emptyPage` in `styles.yaml` and `rst2pdf-0-9.yaml`. I naively tried to copy the contents to my custom style and removed the `emptyPage` reference trying to get rid of the empty page, but that was of no help.

**Comment by lornajane** [comment]
We might need some simple examples as a replication case; rst2pdf does work with sphinx, but we (the maintainers) tend to use the tool by itself so we don't know really well how settings in sphinx pull through, or don't, to rst2pdf. You might be able to pass some additional command options to improve the output and a good starting point for that is to run rst2pdf itself as a command and look at the options it supports.

Please let us know if you have examples we can look at to try to help more

**Comment by lornajane** [comment]
Closing this since we didn't get any more information, but I'm happy to re-open at any time if there's more that would help to understand the problem.
