### ISSUE TITLE
Generate PDF for language files

### ISSUE THREAD

**Issue by sachin-suresh-rapyuta** [rst2pdf/rst2pdf#1077]
How to generate the pdf for language translated `.po` files?

The command `sphinx-build -b pdf . build/pdf` works for default English pdf.

I have created the POT files using the command: 
`sphinx-build -b gettext . build/gettext`.

Generated the `.po` files using:
`sphinx-build -b html . build/html/ja -D language='ja'`

Now I need to generate the PDF file for the `index.html` which is inside the `build/html/<lang>` folder.

**Comment by lornajane** [comment]
I'm sorry for the slow response, but I didn't understand your question.

rst2pdf generates PDF files from restructured text files, not from HTML.

**Comment by lornajane** [comment]
I'm closing because there's not enough information to move forward on this, but if you have more information, please comment/re-open, we can look more at this.
