### ISSUE TITLE
PDF directive in Makefile not executing

### ISSUE THREAD

**Issue by sachin-suresh-rapyuta** [rst2pdf/rst2pdf#1078]
I am trying to generate PDF as part of the build process. When I manually run the `sphinx-build -b pdf . build/pdf` command, I get the PDF. But not when I modify the Makefile.

**What I Tried:**

As per the manual, I added the below lines in Makefile:

```
pdf:
 $(SPHINXBUILD) -b pdf $(ALLSPHINXOPTS) _build/pdf
 @echo
 @echo "Build finished. The PDF files are in _build/pdf."
```

**Expected output:**

When I `make html`, I should also get the PDF in the build folder just like `index.html`.

🖥 **Versions**

```
$ python -V
Python 3.8.10

$ pip freeze | grep rst2pdf
rst2pdf @ file:///home/sachin/Workspace/Sootballs/pa-amr/docs/rst2pdf

$ pip freeze | grep reportlab
reportlab==3.5.34

$ pip freeze | grep Sphinx
Sphinx==4.5.0
```

Which operating system are you using?
Linux Ubuntu 20.04

**Comment by lornajane** [comment]
You will need to run `make pdf` to get the PDF. If you do want to get both formats when you run `make html` check the Makefile docs for how to require additional targets.
