### ISSUE TITLE
Unicode characters replaced with Unicode black square (U+25a0)

### ISSUE THREAD

**Issue by rogerbinns** [rst2pdf/rst2pdf#1125]
**Description of problem**

Have an rst file with Unicode characters such as line drawing or the front page of wikipedia.  Once converted to pdf, those characters are replaced with [black square](https://unicodemap.org/search.asp?search=%E2%96%A0).

Note that this is not the pdf viewer doing rendering that way.  If you copy the text out of the pdf viewer it really is the black square codepoints.  Tested on both the default Linux pdf viewer and Apple's iPad PDF viewer.

My encoding is UTF8 and I also tried adding that to `code-block` which made no difference.  I can't find anything in the manual or searches giving a solution.

**What is the expected output? What do you see instead?**

This file has some line drawing and then text from wikipedia. (Github wouldn't let me upload uncompressed).

[foo.rst.gz](https://github.com/rst2pdf/rst2pdf/files/10912930/foo.rst.gz)

Also in correctly rendering [gist](https://gist.github.com/rogerbinns/401316bc9cee1bb9da90f8a93fbc9188)

This is what it looks like if `rst2html` is run:

![image](https://user-images.githubusercontent.com/553885/223519514-340fbeb3-39c6-4328-b1a6-96b72a2bcf77.png)

And this is page 1 from running `rstpdf`:

![image](https://user-images.githubusercontent.com/553885/223519795-66e7cb53-71f3-4360-8c5d-8eeaae42b0f8.png)

And page 2 with wikipedia text:

![image](https://user-images.githubusercontent.com/553885/223519996-169028b6-9828-4dc1-bd37-a8801844f0ba.png)

This is copy and paste from html output:

    Polski العربية Deutsch English Español Français Italiano مصرى Nederlands 日本語

This is copy and paste from PDF:

    Polski ■■■■■■■ Deutsch English Español Français Italiano ■■■■ Nederlands ■■■

🖥 **Versions**

`python -V`
Python 3.10.7
`pip freeze | grep rst2pdf`
rst2pdf==0.99
`pip freeze | grep reportlab`
reportlab==3.6.12

Which operating system are you using?

Ubuntu 22.10

**Comment by lornajane** [comment]
Thanks for the clear bug report, this is always appreciated here! I am not sure what to suggest, except maybe a font with more symbol coverage perhaps? Perhaps someone with more expertise in this area could chime in to assist.

**Comment by akrabat** [comment]
This is related to fonts. The standard PDF fonts have a very limited set of glyphs, so you need to provide your own for the glyphs you need. For your example, I grabbed [unifont](http://www.unifoundry.com/unifont/index.html) and then created a stylesheet:

foo.yaml:
```yaml
---

# Download unifont-15.0.01.ttf from http://www.unifoundry.com/unifont/index.html 
# and rename to unifont-15.0.01.ttf
embeddedFonts: 
  - [unifont.ttf, unifont.ttf, unifont.ttf, unifont.ttf]

fontsAlias: 
  fontSans: unifont
```

You can now create your PDF using `rst2pdf foo.rst -s foo.yaml` and it will generate `foo.pdf` with the correct glyphs for nearly all the characters:

<img width="786" alt="image" src="https://user-images.githubusercontent.com/33135/233937783-d1695e1b-6ac9-4844-82a3-3d9c426e467f.png">
