### ISSUE TITLE
Disappearance of mathematical formulas

### ISSUE THREAD

**Issue by mtwoz** [rst2pdf/rst2pdf#1135]
**Description of problem**
Hello, I am trying to port rst2pdf to RISC-V platform, but the compilation has the following failures in check(), and I found all the errors are due to disappearing math formulas. I would like to know what are the possible causes and which source files are related to it.

=========================== short test summary info ============================
FAILED rst2pdf/tests/input/test_docutils_math.rst::test_docutils_math
FAILED rst2pdf/tests/input/test_issue_363.rst::test_issue_363
FAILED rst2pdf/tests/input/test_math.rst::test_math
FAILED rst2pdf/tests/input/test_math_default_role.rst::test_math_default_role
FAILED rst2pdf/tests/input/test_math_role.rst::test_math_role
FAILED rst2pdf/tests/input/test_slides.rst::test_slides
FAILED rst2pdf/tests/input/sphinx-issue252/conf.py::sphinx-issue252
= 7 failed, 267 passed, 22 skipped, 17 deselected, 313 warnings in 687.43s (0:11:27) =

**Comment by akrabat** [comment]
I'm not sure, but is `matplotlib` installed?

**Comment by mtwoz** [comment]
> I'm not sure, but is `matplotlib` installed?

Yes, the required dependencies are installed.

**Comment by akrabat** [comment]
Did you solve this @mtwoz ?

**Comment by mtwoz** [comment]
> Did you solve this @mtwoz ?

No... But I found some problems with **matplotlib**'s dependency library **xarray** that can't be built directly, which may affect **matplotlib** and **rst2pdf**.
