### ISSUE TITLE
Línea separadora de las notas al final

### ISSUE THREAD

**Issue by TigerClawKnight** [rst2pdf/rst2pdf#1178]
Buenas tardes. 
Solicito de su ayuda para saber si existe la posibilidad de:
- Cambiar el color de la línea de separación de las notas al final
- Cambiar el grosor de la línea.
- Eliminarla.
Quedo a la espera de su ayuda.
Soy nuevo utilizando rst2pdf,sphinx,reportlab.
![line_separator](https://github.com/rst2pdf/rst2pdf/assets/145498662/2dd7f0f4-bfb0-4c85-9db6-0bc4673c2b79)

**Comment by lornajane** [comment]
Closing in favour of duplicate (but in English) #1179

**Comment by TigerClawKnight** [comment]
¿No se puedo modificar o eliminar esa línea?
