### ISSUE TITLE
line separator footnote

### ISSUE THREAD

**Issue by TigerClawKnight** [rst2pdf/rst2pdf#1179]
Good afternoon.
I am new to using this tool.
Starting to use: sphinx, reportlab, rst.
Ask for your help to know if the line that appears when using a note at the end of the document how? and where? can be removed or changed color.
I searched for "line separator"
I found that there are transitions used characters to separate paragraphs in rst
Example:
Paragraph 1
--------
Paragraph 2
![line_separator](https://github.com/rst2pdf/rst2pdf.github.io/assets/145498662/5e4448f7-6db1-4a7e-bf49-bbdec35f84b2)

**Comment by TigerClawKnight** [comment]
¿Entonces no se puede elimina o cambiar el color a esa línea?

**Comment by lornajane** [comment]
I'm sorry but no, there's no support for customizing the line for the footnotes.
