### ISSUE TITLE
Insert a background image from my disk into restructuredtext pdf

### ISSUE THREAD

**Issue by mpenning** [rst2pdf/rst2pdf#1183]
I am using Python3.11.2 with `rst2pdf` version 0.101.

I need to insert an image as a background image and then overlay some text on that image.

I tried this but it did not insert the image on the page... only the text before it.

```
- bullet 1
- bullet 2

.. raw:: html

   <div>
      <style>
         body {
           background-color: white;
           background-image: url('/home/mpenning/ciscoconfparse_logo_bw_01.png');
           z-index: -1;
         }
      </style>
   </div>
```

What should I do to insert an image behind my text on a pdf page?

**Comment by akrabat** [comment]
Create a new page using the `PageBreak` directive as that takes a `background` parameter like this:

```
PageBreak emptyPage background=/home/mpenning/ciscoconfparse_logo_bw_01.png
```


I use relative paths, but I guess that a fully qualified one will work.

**Comment by mpenning** [comment]
The explicit solution that worked for me... a title page and then the next page with text overlayed on the background image...

```none
Insert Presentation Title Here

.. image:: /home/mpenning/ciscoconfparse_logo_bw_01.png
   :align: center

.. raw:: pdf

    PageBreak background=/home/mpenning/ciscoconfparse_logo_bw_01.png fit-background-mode=scale

- Bullet 1
- Bullet 2
- Bullet 3
```
