### ISSUE TITLE
Two-column text in one line

### ISSUE THREAD

**Issue by mpenning** [rst2pdf/rst2pdf#1184]
### Problem: Two-column line, left-right aligned
- I am using rst2pdf version 0.101 from PYPI.
- I would like to achieve the following two-column alignment without manually padding spaces between the columns.
- I need to render an inline sentence as shown below; how can I achieve this with rst2pdf?

```none
Lorem Ipsum Left                                                                       Lorem Ipsum Right
```

### Problem: Dynamic, multi-column, centered, left-right alignment

```none
• Lorum Ipsum             • Dolor Sit Amet               • Adipiscing Elit              • Eget Posuere a
```

Is there a way to achieve these dynamically one-line at a time?

**Comment by akrabat** [comment]
I would use tables for this. https://akrabat.com/styling-rst2pdf-tables/ might give you ideas on setting up.

**Comment by mpenning** [comment]
@akrabat said:
> I would use tables for this.

I can't.  This is for my resume and Applicant Tracking Systems are [famously hateful towards tables](https://www.jobscan.co/blog/resume-tables-columns-ats/).

Is there a way besides table columns?

**Comment by akrabat** [comment]
> Is there a way besides table columns?

Use a page style with frames?

**Comment by lornajane** [comment]
I think @akrabat answered this so I'll close the issue but @mpenning do let us know how you got on, or if you need anything else.
