### ISSUE TITLE
rst2pdf warning de estilo indefinido y error en la interpretación de docstrings de python

### ISSUE THREAD

**Issue by TigerClawKnight** [rst2pdf/rst2pdf#1204]
Buenos días, compañeros.

Nota: En la investigación realizada no he encontrado algo referente a si rst2pdf puede generar documentación de código python por medio de los docstrings.

Solicitando de su ayuda y asesoría para resolver lo siguiente que les compartó.

Parte 1: Warning styles.py Using undefined style 'function', aliased to style 'normal'.
Este detalle sale al utilizar rst2pdf bajo el caso:
1.- Cuando se ejecuta el comando rst2pdf archivo.rst archivo.pdf
      Dentro del rst tengo lo siguiente:
      Ejemplo 1
      --------------
      .. include:: prueba.py
         :code: python

En el archivo.py:
    def primer_hola_mundo():
    """Una función de prueba para
       Para utilizar rst2pdf.
    """
    print("Buen día, hola mundo")

2.- Caso contrario, cuando se ejecuta el comando rst2pdf archivo.py archivo.pdf no marca este detalle.

Nota: Esto lo veo por que son archivos de prueba pero en códigos más grandes marca el error del estilo.

Se le pasa una hoja de estilo que se tiene creada pero aún así sigue marcando errores de estilos, pienso que es por que está interpretando el nombre de la función como un estilo pero es código, no debería considerarlo como estilo.

Parte 2: Docstrings de código python

En el archivo.py tengo el código documentado con el formato de Google, al querer generar el pdf para obtener la documentación de los comentarios del código del archivo.py, marca errores de indentación pero no dentro de los comentarios sino del código mismo. Se ha revisado de forma exhaustiva los espacios y todo está bien.
Al ejecutar el comando rst2pdf archivo.py archivo.pdf muestra lo siguiente:
     (ERROR/3)Unexpected indentation.
     (ERROR/3)Unexpected indentation.
     (ERROR/3)Unexpected indentation.
     (WARNING/2) Block quote ends without a blank line; unexpected unindent.

Nota: Esas líneas que marcan error de indentación puede ser que rst2pdf esté intentando interpretarlo por que en el pdf esas líneas la primera tiene un enfásis más fuerte (bold) y el resto texto normal.
![error](https://github.com/rst2pdf/rst2pdf/assets/145498662/d8c61ead-6c4a-402c-9812-72a4f98b8059)

**Comment by lornajane** [comment]
I missed this one, sorry. Do you still have a question @TigerClawKnight ?

**Comment by TigerClawKnight** [comment]
> I missed this one, sorry. Do you still have a question @TigerClawKnight ?

Yeah.

Is it possible to output python documentation to a PDF file using rst2pdf?

I have investigated and with sphinx you can get both pdf and html outputs.

But I am working with rst2pdf for making pdf files from rst files.

But I would like to know if it is possible to generate docstring documentation from python files with rst2pdf.

Any recommendations?

**Comment by lornajane** [comment]
No, rst2pdf converts restructuredtext to PDF output, as far as I know it doesn't generate the rst from python or any other source.
