### ISSUE TITLE
Support `xhtml2pdf` 0.2.12+

### ISSUE THREAD

**Issue by justinmayer** [rst2pdf/rst2pdf#1215]
It seems that `rst2pdf` may have a problematic import with `xhtml2pdf` 0.2.12 and above that produces a confusing error.

**Description of problem**

I maintain [Pelican](https://github.com/getpelican/pelican), and a user [reported](https://github.com/pelican-plugins/pdf/issues/17) that the [PDF plugin](https://github.com/pelican-plugins/pdf) produces an error saying “You need `xhtml2pdf` installed to use the raw HTML directive” even though `xhtml2pdf` was already installed. I confirmed this behavior and tracked down the cause to [`xhtml2pdf` changing a module name from `memoized` to upper-case `Memoized`](https://github.com/xhtml2pdf/xhtml2pdf/commit/a3211b854672a09e257d8c4cf7192e30a2690d58#diff-a3bbad1de17b7fa3acba9bbdf547b6e0b3c4a88a75b7b74ce193056cfc7a8317R44) starting in the [0.2.12 release](https://github.com/xhtml2pdf/xhtml2pdf/releases/tag/v0.2.12).

**Steps to Reproduce**

1. Install `rst2pdf` via `python -m pip install rst2pdf xhtml2pdf`
2. Run: `python`
3. `>>> from xhtml2pdf.util import memoized`
4. Note error: `ImportError: cannot import name 'memoized' from 'xhtml2pdf.util'`
5. `>>> from xhtml2pdf.util import Memoized as memoized`
6. Note that above amended import completes successfully.

🖥 **Versions**

`python -V`: Python 3.11.9

`pip freeze | grep rst2pdf`: rst2pdf==0.101

`pip freeze | grep reportlab`: reportlab==4.0.9

Which operating system are you using?

MacOS 14.4.1

**Comment by akrabat** [comment]
Yes. I found that recently and it's fixed in #1214. Specifically, this commit: https://github.com/rst2pdf/rst2pdf/pull/1214/commits/4dfd43b74c9c0a998529ec4278a3f03bf05498b2

**Comment by justinmayer** [comment]
Thanks for the quick response, Rob. I searched before filing the issue, but that commit didn't come up, perhaps because it doesn't exist in this repo yet.

**Comment by akrabat** [comment]
Yep - it's just in the PR from my repo to this one. The PR is also unhelpfully named. Sorry.

**Comment by lornajane** [comment]
Closing since #1214 is merged. Thanks, both of you!
