### ISSUE TITLE
Text not wrapping around images when specified

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#186]
```
What steps will reproduce the problem?
1. Insert an image with :align: right
2.
3.

What is the expected output? What do you see instead?
Text to wrap around the image.

What version of the product are you using? On what operating system?
svn, ubuntu

Please provide any additional information below.
Tried to do it with figures and inline images as well, but not having any
success. This seems like it would be something rather fundamental...

```

Original issue reported on code.google.com by `joseph.w...@gmail.com` on 2 Sep 2009 at 5:17

**Comment by thmo** [comment]
I tried to wrap text consisting of multiple paragraphs around an image, using a `container` and this recipe:
```
Text before.

.. image:: images/foo.png
   :width: 7cm
   :align: right

.. container::

   First paragraph.

   Second paragraph.

Text after.
```
Using `--use-floating-images` lets "First paragraph" to appear left of the image, but "Second paragraph" is shifted below the image. It seems the containter directive doesn't have any effect. What am I doing wrong?

rst2pdf 0.93.dev0, reportlab 3.4.0
