### ISSUE TITLE
Improve math directive/role

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#253]
```
While basic math support exists, its behaviour should be made equivalent 
to sphinx's math extensions, supporting the same options, numbered 
equations, etc.
```

Original issue reported on code.google.com by `roberto.alsina` on 5 Dec 2009 at 12:52

**Comment by lornajane** [comment]
There's not enough detail to implement this as a whole but if anyone needs a particular maths feature, then please open an individual with specific examples of the support you'd like to see. I think an as-needed approach will be a good way to implement these pieces.
