### ISSUE TITLE
Bullets can not be customized

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#289]
```
There seems to be (as of r1924) no way to change the bullets font or size from 
the stylesheet.

This was first reported by Malte Schwerhoff in the rst2pdf-discuss mailing list:

http://groups.google.com/group/rst2pdf-
discuss/browse_thread/thread/a6c9677788f1873d
```

Original issue reported on code.google.com by `roberto.alsina` on 18 Mar 2010 at 12:28

**Comment by lornajane** [comment]
I'm not aware of a problem with the bullets so I'll close this - the bullet fonts seem to be working fine, I don't think images are supported. If that's not correct feel free to re-open and/or add more info.
