### ISSUE TITLE
Line numbers when including sources in codeblocks are wrong

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#310]
```
If you use the code-block directive with linenos, include and start-at, the 
line numbers start from 1 instead of the correct line number.

Maybe this should be an option, so the user can choose if numbers should 
start at one or not.

Test case coming.
```

Original issue reported on code.google.com by `roberto.alsina` on 7 Apr 2010 at 1:10

**Comment by lornajane** [comment]
@akrabat did you just fix this? Or can you help me identify which tests this would be?

**Comment by akrabat** [comment]
You're right this is working.

See #663 and #664

Reference PDFs: 

* https://github.com/rst2pdf/rst2pdf/blob/master/rst2pdf/tests/reference/test_issue_310.pdf
* https://github.com/rst2pdf/rst2pdf/blob/master/rst2pdf/tests/reference/test_issue_310_2.pdf
