### ISSUE TITLE
Enhance translation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#326]
```
I did not found which languages rst2pdf had with him, but I'm almost sure that 
en_US is the unique, so, if you guys want, I can help translate to pt_BR.
```

Original issue reported on code.google.com by `helton.d...@gmail.com` on 15 Jun 2010 at 3:04

**Comment by lornajane** [comment]
We don't have the volunteers to add or maintain translations, so closing this issue.  Recommend that translators maintain their own forks if desired (but let us know and we'll link to them!)
