### ISSUE TITLE
directive section-autonumbering is unknown

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#350]
```
version = 0.12.3

.. sectnum:: is handled but not its synonym .. section-autonumbering::


```

Original issue reported on code.google.com by `tmonj...@gmail.com` on 18 Aug 2010 at 12:25

**Comment by ralsina** [comment]
It's section-numbering.

<img width="493" alt="screen shot 2018-11-07 at 17 17 39" src="https://user-images.githubusercontent.com/1579/48158356-138e9400-e2b1-11e8-80da-32cc1e567718.png">
