### ISSUE TITLE
cannot show chinese character

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#377]
```
What steps will reproduce the problem?
1. ubuntu 10.04 with chinese language support.
2. sudo easy_install rst2pdf -> 0.16
3. $ rst2pdf s.rst

What is the expected output? What do you see instead?

suppose to display: 你好!, but only get: SS!

Please answer the following questions, they are *very* important:

* Version of rst2pdf?
0.16
* Version of reportlab?
Version: 2.4-1
* Are you using wordaxe, and if true, what version?
no
* Are you using rst2pdf with Sphinx, and if true, what version?
no
Please provide any additional information below.
s.rst and s.pdf are attenched.
```

Original issue reported on code.google.com by `linjunhalida` on 9 Nov 2010 at 1:09
- Merged into: #12

Attachments:
- [s.rst](https://storage.googleapis.com/google-code-attachments/rst2pdf/issue-377/comment-0/s.rst)
- [s.pdf](https://storage.googleapis.com/google-code-attachments/rst2pdf/issue-377/comment-0/s.pdf)

**Comment by 837278709** [comment]
I still have this problem, so how to change the stylesheet to use a default font that has chinese 
glyphs. I think it is something like "rst2pdf --stylesheets=" right?

**Comment by lornajane** [comment]
I can't read the blog post but from the code snippets I think this would work if you created a stylesheet called `chinese.style` and added at least this content:

```
embeddedFonts : [wqy-zenhei.ttf, msyhbd.ttf, wqy-zenhei.ttf, wqy-zenhei.ttf]

fontsAlias:
    stdBold: wqy-zenhei
    stdFont: msyhbd
    stdItalic: wqy-zenhei
```

Those fonts will also need to be in place on your system. Can you please let us know how it goes? The project maintainers are all English-speaking-only so we don't work much with any other character sets and input on these topics is very welcome.

PS I'd also recommend that you open a new issue when you run into things rather than commenting on an old, closed one. I almost missed this!

**Comment by akrabat** [comment]
We have a test that covers some of this I think in `test_issue_349`. You may need to set the language using `-l zh_cn` on the command line.

**Comment by 837278709** [comment]
> I can't read the blog post but from the code snippets I think this would work if you created a stylesheet called `chinese.style` and added at least this content:
> 
> ```
> embeddedFonts : [wqy-zenhei.ttf, msyhbd.ttf, wqy-zenhei.ttf, wqy-zenhei.ttf]
> 
> fontsAlias:
>     stdBold: wqy-zenhei
>     stdFont: msyhbd
>     stdItalic: wqy-zenhei
> ```
> 
> Those fonts will also need to be in place on your system. Can you please let us know how it goes? The project maintainers are all English-speaking-only so we don't work much with any other character sets and input on these topics is very welcome.
> 
> PS I'd also recommend that you open a new issue when you run into things rather than commenting on an old, closed one. I almost missed this!

Thanks I will open a new issue.

**Comment by 837278709** [comment]
> -l zh_cn

It still will not work.  I will open a new issue. I used shell cmd like this: rst2pdf -l zh_cn -s chinese test.rst out.pdf
