### ISSUE TITLE
Deeply nested lists break spacing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#484]
```
See test case test_lists.pdf the "upper roman" item overlaps the "lists that 
don't start at 1" item.
```

Original issue reported on code.google.com by `roberto.alsina` on 8 Dec 2012 at 4:09

Attachments:
- [test_lists.pdf](https://storage.googleapis.com/google-code-attachments/rst2pdf/issue-484/comment-0/test_lists.pdf)

**Comment by lornajane** [comment]
Duplicate of #439 so closing this one as the other has more discussion.
