### ISSUE TITLE
Conversion problems (list superimpose & bold)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#490]
```
I tried to convert to a pdf the rst and I get a graphical bug with the 
conversion.

Moving to page 2 (Title 4) of the pdf there is 2 problems:
- The first element of the list (first bug) is in bold.
- list 2 and 3 are superimposed.

I think the two problems are linked.

In attachment there is the source rst and the resulting pdf.

I've tried with rst2pdf from my distro (Ubuntu 12.04)
$ rst2pdf --version
0.16
and with version from download:
$ ~/.local/bin/rst2pdf --version
0.93.dev

I get the same bug.

I don't know if I've repportlab.
```

Original issue reported on code.google.com by `petit.ay...@gmail.com` on 11 Mar 2013 at 10:56

Attachments:
- [bug.rst](https://storage.googleapis.com/google-code-attachments/rst2pdf/issue-490/comment-0/bug.rst)
- [bug.pdf](https://storage.googleapis.com/google-code-attachments/rst2pdf/issue-490/comment-0/bug.pdf)

**Comment by diego-XA** [comment]
Any advance on this?  I can confirm this problem and in my opinion it severely cripples the rst2pdf application as you cannot use nested lists without getting odd bold text.

**Comment by diego-XA** [comment]
For what I've seen the problem is that the first list item is interpreted as a definition list so it gets bold.

**Comment by ralsina** [comment]
The bug is in the provided example.

This is a definition list with a list in it:

```
#) The first bug
        - list 1
        - list 2
        - list 3
        - list 4
```

And this is a list with a list in it:

```
#) The first bug

        - list 1
        - list 2
        - list 3
        - list 4
```

It's sort of a corner case of the reStructured text syntax and rst2html actually handles it the same way. The first case generates this HTML:

```
<dt>The first bug</dt>
<dd><ul class="first last">
<li>list 1</li>
<li>list 2</li>
<li>list 3</li>
<li>list 4</li>
```

So, not a rst2pdf bug
