### ISSUE TITLE
Using code-blocks with include fragments output

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#497]
```
Using rst2pdf to render any source code file (styles.py from rst2code used in 
this case)

And this simple rst file:

===========
Source Code
===========

.. code-block:: python
    :include: ./styles.py
    :linenos:

Then when i try to make the pdf file using this command:

rst2pdf code.rst -o code.pdf -s a4

I get the source code fragmented in the pdf file.


* Version of rst2pdf?
 0.93

* Version of reportlab?
 2.7

* Are you using wordaxe, and if true, what version?
 no
* Are you using rst2pdf with Sphinx, and if true, what version?
 no
Please provide any additional information below.

```

Original issue reported on code.google.com by `andrex...@gmail.com` on 5 Jun 2013 at 4:35

Attachments:
- [code.rst](https://storage.googleapis.com/google-code-attachments/rst2pdf/issue-497/comment-0/code.rst)
- [code.pdf](https://storage.googleapis.com/google-code-attachments/rst2pdf/issue-497/comment-0/code.pdf)
- [code.bat](https://storage.googleapis.com/google-code-attachments/rst2pdf/issue-497/comment-0/code.bat)
- [styles.py](https://storage.googleapis.com/google-code-attachments/rst2pdf/issue-497/comment-0/styles.py)

**Comment by ralsina** [comment]
Doesn't seem to be happening anymore.
[x.pdf](https://github.com/rst2pdf/rst2pdf/files/2557577/x.pdf)
