### ISSUE TITLE
Improve counter usage

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#522]
```
I need to re-use a table or image number multiple times, once in the 
introductory text, once under the table/image as a caption, and maybe another 
time as a link to it.


But every time I use :counter:`table` the counter increases by 1.

How can I freeze the counter for as long as I need to use the same one? In this 
case at least 2 times. 
Or maybe: How can I get the last counter number?




* Version of rst2pdf: 0.93
```

Original issue reported on code.google.com by `adi.cump...@gmail.com` on 13 Jan 2015 at 10:45

Attachments:
- [Untitled.jpg](https://storage.googleapis.com/google-code-attachments/rst2pdf/issue-522/comment-0/Untitled.jpg)

**Comment by ralsina** [comment]
There is no way (currently) to use a counter without bumping it at the same time.

I am not sure how this would work, really, so closing as won't fix.
