### ISSUE TITLE
Relative URI for template background image

### ISSUE THREAD

**Issue by oliverfields** [rst2pdf/rst2pdf#533]
When specifying background image setting for pageTemplates in .style files it would be useful if the path could be relative. This would avoid having to hardcode path, e.g. when packaging.

Here is small, and perhaps naive patch, that does this. I added it to createpdf.py on line 1004.

1001a1002,1006

> ```
>         # If relative URI look relative to cwd
>         if not uri.startswith(os.sep):
>             uri = os.path.join(os.getcwd(), uri)
> ```

Thanks for excellent package, use this a lot:)

**Comment by lornajane** [comment]
I _think_ this was fixed by #672 but please re-open and tell us if not!
