### ISSUE TITLE
use texlib

### ISSUE THREAD

**Issue by flying-sheep** [rst2pdf/rst2pdf#536]
[akuchling/texlib](/akuchling/texlib) is pretty awesome for not having ugly ragged MS Word style blocktext.

[brandon-rhodes/python-bookbinding](/brandon-rhodes/python-bookbinding) uses it but its documentation is too non-existant to tell if it’s of any use for us.

**Comment by lornajane** [comment]
I'm not clear what the benefits of this recommendation are, so we're unlikely to action it any time soon ... closing the issue for now but discussion is always welcome.
