### ISSUE TITLE
So what do we do with the wiki?

### ISSUE THREAD

**Issue by pmaupin** [rst2pdf/rst2pdf#539]
The conversion drops it, like a little turd, right in the middle of the network graph.

Do we want a wiki?  If so, using github, or elsewhere?

If we want to keep the info in the wiki branch, we can add it as another subdirectory under the main repo.

**Comment by pmaupin** [comment]
https://github.com/morgant/finishGoogleCodeGitHubWikiMigration

**Comment by lornajane** [comment]
I'm not sure if the wiki still exists ....? Closing but if you can point me at the original source I'll happily revisit.

**Comment by akrabat** [comment]
@lornajane @pmaupin is referring to the [`wiki`](https://github.com/rst2pdf/rst2pdf/tree/wiki) branch. I assume that it arrived as part of the migration from Google Code.

A quick look suggests that there's nothing we care about there.
