### ISSUE TITLE
The website

### ISSUE THREAD

**Issue by ralsina** [rst2pdf/rst2pdf#540]
It's currently hosted in my VPS, it's Nikola-based. I am happy to continue hosting it and offering a reasonable mechanism for deployment to anyone that asks.

Or it could be moved to GH pages. Or redone.

**Comment by pmaupin** [comment]
If we leave it there for now, that would be awesome -- one less thing to think about at the start.  Does that setup actually use the wiki branch on github, or is that branch not used for anything right now?  (You can see it on the graph here.)

https://github.com/rst2pdf/rst2pdf/network

Like I said, I could toast it or could make it a subdirectory under the main branch if there is anything there we want to keep.

**Comment by lornajane** [comment]
This is complete. https://rst2pdf.org/ now points to https://github.com/rst2pdf/rst2pdf.github.io and is a github pages site.
