### ISSUE TITLE
Remove buildout

### ISSUE THREAD

**Issue by aquavitae** [rst2pdf/rst2pdf#542]
Everything buildout does can now be done more consistently and more easily with virtualenv, pip and setuptools, so we way as well remove it, add a requirements.txt file and update setup.py (if necessary).

**Comment by glenfant** [comment]
@aquavitae : bad idea ! zc.buildout has recipes to build and configure things that are out of the scope of pip and setuptools.

**Comment by pmaupin** [comment]
zc.buildout cost me many hours by placing things in the wrong order.  I don't understand it and it doesn't work right.  What else does it have to recommend it?

**Comment by oz123** [comment]
This definitely needs to be done. Builtout didn't win the hearths of the Python community and developers expect a setup.py work flow whether we like it or not.

Also, builtout seems quite neglected...

**Comment by stephenfin** [comment]
From what I can tell, this is no longer an issue with modern rst2pdf and this issue can therefore be closed.
