### ISSUE TITLE
Is it possible to place current date / time in a document

### ISSUE THREAD

**Issue by zobbo** [rst2pdf/rst2pdf#546]
Title says it all I guess. I've spent a few hours learning rst2pdf this morning and this is the only place I've hit a brick wall. 

Many thanks for the software - any advice gratefully received.

**Comment by ralsina** [comment]
Yes, check http://docutils.sourceforge.net/docs/ref/rst/directives.html#date

**Comment by zobbo** [comment]
I'm so dim - thank you!!!
