### ISSUE TITLE
Blank rst file generates a PDF with zero pages

### ISSUE THREAD

**Issue by lamby** [rst2pdf/rst2pdf#547]
Was expecting it to generate a single, blank page.

(Alternative title: cannot generate a blank PDF..)

**Comment by lamby** [comment]
Hit this again recently; any interest in this?

**Comment by akrabat** [comment]
I'm pretty sure we'd take a fix!

**Comment by lamby** [comment]
> I'm pretty sure we'd take a fix!

Oh, good to know. Do you think you could see your way to writing one?

**Comment by akrabat** [comment]
I'm unlikely to get to it in the near future.

**Comment by Ocramius** [comment]
@lamby consider sending a patch :+1:
