### ISSUE TITLE
Missing scheme in --inline-links handling

### ISSUE THREAD

**Issue by valholl** [rst2pdf/rst2pdf#549]
As reported on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=796959

> it seems that the handling of the --inline-links option is a bit incomplete:
> 
> https://sources.debian.net/src/rst2pdf/0.93-4/rst2pdf/genpdftext.py/#L94
> 
> only lists http:// and ftp://. Obviously missing is https, but there are other.

I've checked that this is still the case in master: https://github.com/rst2pdf/rst2pdf/blob/master/rst2pdf/genpdftext.py#L94

**Comment by ralsina** [comment]
Yep.
