### ISSUE TITLE
some commands are ignored on tables.

### ISSUE THREAD

**Issue by cnf** [rst2pdf/rst2pdf#559]
Hi, I don't know how active this project still is, but here goes...

if you have something like this in your style:

```
styles:
  mytable:
    commands: []
      [ALIGN, [0, 0], [-1, -1], RIGHT]
      [TEXTCOLOR, [0, 0], [-1, -1], red]
```

ALIGN and TEXTCOLOR are ignored. most other commands seem to work fine though.

**Comment by ralsina** [comment]
Well, not very active :-)

IIRC you will need to apply those to the elements inside the cell, and not
to the cell themselves, because the text is in paragraphs, which are 100%
width, so aligning them does nothing.

**Comment by cnf** [comment]
hi!
How would I do that? Those commands are passed to Reportlab TableStyle. Also, why would that stop TEXTCOLOR from working?

I tried making a .. style:: but i could not get that to work either.

**Comment by ralsina** [comment]
On Mon, Nov 30, 2015 at 10:10 AM Frank Rosquin <notifications@github.com>
wrote:

> hi!
> How would I do that?
>

Applying a class to the contents of the cell.


> Those commands are passed to Reportlab TableStyle. Also, why would that
> stop TEXTCOLOR from working?
>

Because TEXTCOLOR affects bare strings and not paragraphs.


> I tried making a .. style:: but i could not get that to work either.
>

Now that's a separate problem :-)

**Comment by cnf** [comment]
How would you apply a class to the contents of a cell?

And my understanding of the ReportLab docs is still that my original style should work. It is right in their documentation.

**Comment by pmaupin** [comment]
This uses reportlab, but it isn't reportlab :-)

Here is an example (from working code) that applies classes to cell contents:

            .. class:: headertable

            +--------------------+-------------------------------------------+
            | .. class:: txtbold |   .. class:: txtred                       |
            |                    |                                           |
            | Mnemonic:          |   %s|
            +--------------------+-------------------------------------------+
            | .. class:: txtbold |   .. class:: txtred                       |
            |                    |                                           |
            | Address:           |   %s|
            +--------------------+-------------------------------------------+
            | .. class:: txtbold |   .. class:: txtred                       |
            |                    |                                           |
            | Power Up Default:  |   %s|
            +--------------------+-------------------------------------------+

(Note that after the strings are filled in, the bars on the right are lined up.)

**Comment by cnf** [comment]
ah, that indeed did it!

I dare say getting this from the docs isn't easy :p 

Thanks for the help.

**Comment by ubmarco** [comment]
Hi,
commenting on a 5 year old issue. Does setting the class for cells also work for the `list-table` directive? I did not manage to right-align certain cells.
Thanks
