### ISSUE TITLE
Literal blocks do not shink with newer versions of ReportLab

### ISSUE THREAD

**Issue by stoggi** [rst2pdf/rst2pdf#560]
Even when running `rst2pdf` with `--fit-literal-mode=shrink` literal blocks to not shrink when they spill over the page edge.

It looks like in ReportLab the function [_listWrapOn](https://github.com/Distrotech/reportlab/blob/d13001d514bf6cb767fd2e626dd96ce0337bbc8a/src/reportlab/platypus/flowables.py#L568) behaves differently now. There is a configuration parameter for reportlab `listWrapOnFakeWidth` which needs to be set to `False` for `_listWrapOn` to return the correct width.

Current workaround, is to create `reportlab_settings.py` in the same directory (or on your Python path) with the following:

```
listWrapOnFakeWidth = False
```

rst2pdf --version
0.93.dev-r0

reportlab.**version**
'3.2.0'

[literal-block.txt](https://github.com/rst2pdf/rst2pdf/files/46896/literal-block.txt)
[literal-block.pdf](https://github.com/rst2pdf/rst2pdf/files/46897/literal-block.pdf)

**Comment by stoggi** [comment]
We may be able to simply set ``fakeWidth=False`` in [``flowables.py:729``](https://github.com/rst2pdf/rst2pdf/blob/4b7e03e203148be8a2068c6474a08b847f26b670/rst2pdf/flowables.py#L729):

    self.width, self.height = _listWrapOn(self.content, maxWidth, None, fakeWidth=False)

Although, I am unsure what fakeWidth is for, and what impact this would have.

**Comment by tanimani** [comment]
:+1:

**Comment by martini5468** [comment]
I am running into the same issue. Using ``--fit-literal-mode`` with any options has no effect. I am running:
rst2pdf --version
0.93.dev-r0

reportlab==3.3.0

@stoggi  - is there a workaround for that?

**Comment by stoggi** [comment]
@martini5468 try creating a file called `reportlab_settings.py` in your current working directory with the following:

    listWrapOnFakeWidth = False

**Comment by stoggi** [comment]
Hm, just tested with ReportLab 3.3.0, and it can't find `reportlab_settings.py` in my current directory either. It has to be on your Python path so that `from reportlab_settings import *` will work. It might be a difference in how reportlab is imported from rst2pdf.

You can create `~/.reportlab_settings` in your home directory instead. That does seem to work for me (note, no extension).

Check out [rl_config.py](https://bitbucket.org/rptlab/reportlab/src/fe660f227cac655c5e8b0e816615470ec17da996/src/reportlab/rl_config.py?at=ReportLab_3_3_0) to see how the settings file is found.

**Comment by martini5468** [comment]
@stoggi - This works exactly as expected. Thanks for your help.

**Comment by JuanManuel18** [comment]
@stoggi set fakeWidth=False in flowables.py:729 works for me

Thanks

**Comment by ralsina** [comment]
I wish I knew what line 729 in flowables.py was in 2017 :-)

**Comment by ralsina** [comment]
Fix in https://github.com/rst2pdf/rst2pdf/pull/703
