### ISSUE TITLE
code blocks not copyable because indentation gets lost.

### ISSUE THREAD

**Issue by AvdN** [rst2pdf/rst2pdf#563]
Whenever I have a code block in my .rst file like:

```
``script`` section::

  script
    /usr/bin/docker start -a devpi-server
  end script
```

this gets rendered visually ok, but there are no spaces before `/usr/...` when I select the code piece
from the resulting PDF. For this example the code still works when copied, but for python snippets losing the proper indentation is really a nuisance.

**Comment by ralsina** [comment]
Indeed the copy/paste of code blocks is weeeeeird.

**Comment by lornajane** [comment]
I would love to be wrong about this, but after some research it looks like this is a PDF feature (see https://superuser.com/questions/198392/how-to-copy-text-out-of-a-pdf-without-losing-formatting). I'm closing but we'd love to hear that this is in fact possible and how to acheive it!!
