### ISSUE TITLE
Generating Indices fails when used with Spinx 1.4.1

### ISSUE THREAD

**Issue by JorjMcKie** [rst2pdf/rst2pdf#568]
this is an example output:

```
$ sphinx-build -b pdf source build/pdf
Running Sphinx v1.4.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [pdf]: targets for 26 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
processing PyMuPDF... index intro changes installation tutorial classes colorspace device displaylist document identity irect link linkdest matrix outline page pixmap point rect textpage textsheet functions vars app1 app2 [ERROR] pdfbuilder.py:130 too many values to unpack
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\rst2pdf\pdfbuilder.py", line 122, in write
    appendices=opts.get('pdf_appendices', self.config.pdf_appendices) or [])
  File "c:\python27\lib\site-packages\rst2pdf\pdfbuilder.py", line 209, in assemble_doctree
    index_nodes=genindex_nodes(genindex)
  File "c:\python27\lib\site-packages\rst2pdf\pdfbuilder.py", line 385, in genindex_nodes
    for entryname, (links, subitems) in entries:
ValueError: too many values to unpack
FAILED
build succeeded.
$
```

Setting ``pdf_use_index = False`` in ``conf.py`` will get the document created - without index.
I know that this same rst2pdf version worked with Sphinx 1.3.1.

**Comment by fgerstenberg** [comment]
i came across the same problem a while ago. It seems the new Sphinx version reports an additional field in its index entries.
currently line 385 in pdfbuilder.py reads as following:
`        for entryname, (links, subitems) in entries:
            if links:
                output.append('`%s <#%s>`_'%(entryname,nodes.make_id(links[0][1])))
                for i,link in enumerate(links[1:]):
                    output[-1]+=(' `[%s] <#%s>`_ '%(i+1,nodes.make_id(link[1])))
                output.append('')`
But since the second part of entries is now a list of length 3, you get the ValueError. Making the following changes will solve the error and should be compatible with the old format as well:
`        for entryname, add_info in entries:
            links = add_info[0]
            subitems = add_info[1]
            if links:
                output.append('`%s <#%s>`_'%(entryname,nodes.make_id(links[0][1])))
                for i,link in enumerate(links[1:]):
                    output[-1]+=(' `[%s] <#%s>`_ '%(i+1,nodes.make_id(link[1])))
                output.append('')`
This will simply drop the additional field. In every case i tested it had the value _None _anyway.

**Comment by JorjMcKie** [comment]
Works! Great tip!
Thanks a lot.

**Comment by mixmastamyk** [comment]
Having this problem now, why is the bug closed?

**Comment by fgerstenberg** [comment]
I dont know. Seems like the OP was satisfied with my workaround and closed it. If you ran into the same problem, you might want to reopen it or open a new issue.

**Comment by mixmastamyk** [comment]
Yep, probably should be open, editing sources is doable in a pinch, but not a long-term solution.  I made the edits, but had another crash error, and noticed this project seems to be abandoned or on hiatus at least.

So I've given up on pdf output with my sphinx docs for now, but may give the latex route a try when I try again.  Up to y'all.

**Comment by pmaupin** [comment]
Yeah, "on hiatus."

Not enough hours in the day for everything that needs to be done...

**Comment by KonstantinShemyak** [comment]
This would be closed by #576.

**Comment by OrlandoArcapix** [comment]
I've just hit this bug with the latest pip releases of Sphinx and rst2pdf:

```
Sphinx==1.6.7
rst2pdf===0.93.dev-r0
```
(and using sphinx theme `cloud-sptheme==1.9.4`).

The patch above from @fgerstenberg fixed it though:
```
--- /Users/username/Library/Python/2.7/lib/python/site-packages/rst2pdf/pdfbuilder.py.dist	2018-04-25 19:39:19.000000000 +0100
+++ /Users/username/Library/Python/2.7/lib/python/site-packages/rst2pdf/pdfbuilder.py	2018-04-25 19:40:13.000000000 +0100
@@ -382,7 +382,10 @@
     for key, entries in genindexentries:
         #from pudb import set_trace; set_trace()
         output.append('.. cssclass:: heading4\n\n%s\n\n'%key) # initial
-        for entryname, (links, subitems) in entries:
+#        for entryname, (links, subitems) in entries:
+        for entryname, add_info in entries:
+            links = add_info[0]
+            subitems = add_info[1]
             if links:
                 output.append('`%s <#%s>`_'%(entryname,nodes.make_id(links[0][1])))
                 for i,link in enumerate(links[1:]):
```

**Comment by akrabat** [comment]
The approach I'm taking at the moment is to get the Travis CI tests to a state where we know what doesn't work and have that documented. Then I'll work with @ralsina to get a new release into PyPi.

**Comment by ralsina** [comment]
@akrabat happy to help with the release.

**Comment by akrabat** [comment]
Thanks @ralsina.

I want to at least fix the line numbers issue (test_issue_310) and maybe it's worth getting a 0.94 out, so we can find out what's really broken since the last release!
