### ISSUE TITLE
Error installing rst2pdf

### ISSUE THREAD

**Issue by magick93** [rst2pdf/rst2pdf#570]
I am getting the following error when trying to install rst2pdf when using pip. I then tried the other method to install - using git clone then running the python command. This also resulted in an error.

**Using git and build locally**

> Installing rst2pdf script to /usr/local/bin
> Installed /usr/local/lib/python2.7/site-packages/rst2pdf-0.93.dev_r0-py2.7.egg
> Processing dependencies for rst2pdf===0.93.dev-r0
> Searching for pdfrw
> Reading https://pypi.python.org/simple/pdfrw/
> Download error on https://pypi.python.org/simple/pdfrw/: unknown url type: https -- Some packages may not be found!
> Couldn't find index page for 'pdfrw' (maybe misspelled?)
> Scanning index of all packages (this may take a while)
> Reading https://pypi.python.org/simple/
> Download error on https://pypi.python.org/simple/: unknown url type: https -- Some packages may not be found!
> No local packages or download links found for pdfrw
> error: Could not find suitable distribution for Requirement.parse('pdfrw')

**Using Pip**

> $ sudo pip install rst2pdf
> [sudo] password for anton: 
> Traceback (most recent call last):
>   File "/usr/local/bin/pip", line 9, in <module>
>     load_entry_point('pip==7.0.3', 'console_scripts', 'pip')()
>   File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 558, in load_entry_point
>   File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 2682, in load_entry_point
>   File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 2355, in load
>   File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 2361, in resolve
>   File "/usr/local/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/**init**.py", line 15, in <module>
>     from pip.vcs import git, mercurial, subversion, bazaar  # noqa
>   File "/usr/local/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/vcs/subversion.py", line 9, in <module>
>     from pip.index import Link
>   File "/usr/local/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/index.py", line 30, in <module>
>     from pip.wheel import Wheel, wheel_ext
>   File "/usr/local/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/wheel.py", line 35, in <module>
>     from pip._vendor.distlib.scripts import ScriptMaker
>   File "/usr/local/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/_vendor/__init__.py", line 92, in load_module
>     raise ImportError("No module named '%s'" % (name,))
> ImportError: No module named 'pip._vendor.distlib.scripts'

**Comment by ralsina** [comment]
This looks like a weird local setup issue, and it was 2 years ago. Closing.
