### ISSUE TITLE
unexpected escape within table's quotes

### ISSUE THREAD

**Issue by GabrielGanne** [rst2pdf/rst2pdf#571]
Hi,

The following table content below has its '\' char disappearing during pdf generation.
Since I explicitly put it between quote, I expected the content to be left untouched.

<pre>
.. csv-table::
   :header: "HeaderName"
   :quote: |

   |test\escape|
</pre>

So I have :

<pre>
"test\escape" => "testescape"
"test\\escape" => "test\escape"
</pre>

Regards,

**Comment by ralsina** [comment]
rst2pdf behaves exactly like rst2html here, so "expected behaviour".

<img width="144" alt="screen shot 2018-11-07 at 11 38 27" src="https://user-images.githubusercontent.com/1579/48137860-b9c2a580-e281-11e8-9d89-9df80b471f2d.png">
