### ISSUE TITLE
rst2pdf triggers font build every time it is used

### ISSUE THREAD

**Issue by ldesousa** [rst2pdf/rst2pdf#572]
Every time I use rst2pdf (0.93.dev-r0) I receive back this warning:

$ rst2pdf main.rst -b1 -s basic.style
/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

rst2pdf is functioning but it takes about one minute to compile even the simplest of files.

**Comment by oesteban** [comment]
This warning has been around back since one update of matplotlib. It is issued by any app when they ```import matplotlib```.

**Comment by ralsina** [comment]
Not a rst2pdf bug then.
