### ISSUE TITLE
Fix md5sum for tests 

### ISSUE THREAD

**Issue by oz123** [rst2pdf/rst2pdf#586]
Here is how to do it:

cd into tests, run:

```
./autotest.py  input/numbered_links.txt
```

This will spit something like:

```
Program coverage exit code: PASS (0)   elapsed time: 00.5 seconds

Cumulative execution time is 00.5 seconds

Validity of file numbered_links.pdf checksum '227d294438ba13cd82b3a8c4e821eb45' is unknown.


--------------------- >> end captured stdout << ----------------------
```

Open the file `tests/output/numbered_links.pdf` with a pdfviewer and see if it is fine, and the content described in `input/numbered_links.txt` makes sense with the pdf created. If so run again:

```
./autotest.py -u good input/numbered_links.txt
```

and then `git diff` will show you that it updated the list of known md5sum: 

```
diff --git a/rst2pdf/tests/md5/numbered_links.json b/rst2pdf/tests/md5/numbered_links.json
index b8800c0..7dadba1 100644
--- a/rst2pdf/tests/md5/numbered_links.json
+++ b/rst2pdf/tests/md5/numbered_links.json
@@ -4,6 +4,7 @@ bad_md5 = [

 good_md5 = [
         '1c6210e63ea3fa10bb75654b25ab363d',
+        '227d294438ba13cd82b3a8c4e821eb45',
         '80d98fac64c38665c9f7309eac7a6630',
         'acd27fe880468c001e385c021cd0dfee',
         'sentinel'
lines 1-37/37 (END)
```

add the file to commit and test more files.

**Comment by lornajane** [comment]
Thanks for this!  I used these instructions to update the docs `/docs/DEVELOPERS.rst` on how to run the tests and fix or supply new md5s.  We've now got all tests passing or skipped, and a separate request open for help with the skipped ones (see #660 ) so I'll now close this issue in favour of that one.
