### ISSUE TITLE
Merging #581 messes up test case numbered links

### ISSUE THREAD

**Issue by oz123** [rst2pdf/rst2pdf#587]
This is really bad ...

Unicode vs Bytes stuff ... gripes... :-/

**Comment by oesteban** [comment]
I can take a look on this. Could you provide some more specific information about what is happening?

**Comment by oz123** [comment]
If you run the test like in travis, you will see what I mean. Basically, I don't feel comfortable continuing with new features (Python3 support being a major feature) without having the test suite run...

**Comment by oesteban** [comment]
Ok, I'll look at this. I understand your concern, however IMHO one of the biggest fails of Python 3 is that we always let it for the last feature to add. It'd be a lot easier if we (all programmers) coded Python 3 and then struggle to make it python 2 compatible.

I think the following is be aligned with both facets (tests and python 3): we first fix the tests so they run in both python 2 and 3 (this will require refactoring the tests deeply), and then we worry about the code.

We could have an experimental branch for all of this, until it is stable enough to merge into master.
