### ISSUE TITLE
SyntaxError - line 695 of createpdf.py

### ISSUE THREAD

**Issue by dylanmc** [rst2pdf/rst2pdf#600]
New user here, just did a `sudo pip3 install rst2pdf`, and tried to create the rst-cheatsheet from https://github.com/ralsina/rst-cheatsheet, and got this error:

```
$ rst2pdf rst-cheatsheet.rst -s cheatsheet
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/rst2pdf", line 7, in <module>
    from rst2pdf.createpdf import main
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/rst2pdf/createpdf.py", line 695
    except ValueError, v:
                     ^
SyntaxError: invalid syntax
```

This is on MacOS 10.12, but googling showed a windows user on StackOverflow with the same issue:

http://stackoverflow.com/questions/40305369/i-get-syntaxerror-for-rst2pdf-command-after-installing-rst2pdf-in-windows-7

**Comment by KeiOtori** [comment]
Same problem, and not the only. Looks like pip package is broken.

**Comment by dylanmc** [comment]
I'm pretty sure this is a Python3 vs. 2 issue. I tweaked the file to get rid of this error, and got another, and kept going for a while, but never got it working. Someone with better Python 2 -> Python 3 fu should do this.

**Comment by jflalande** [comment]
Same error here. From git source ends with the same issue.

**Comment by jflalande** [comment]
It seems that rst2pdf does not like to be executed by python3 (read this on several post, not sure it is true). Thus, I suggest to remove the install files from python3 lib dir, then force installation for python2:

`
sudo pip3 uninstall rst2pdf
sudo pip2.7 install rst2pdf --upgrade
`
works fine know here.

**Comment by holdenweb** [comment]
This is at best a workaround. If someone competent (_e.i._, not me) wants to fix this with real Python 3 support I will happily donate a copy of "Python in a Nutshell" (for which I wrote the chapter on migration and coexistence) as a combination of inducement and reward.

**Comment by akrabat** [comment]
@holdenweb : My current plan is to have two separate code bases: `v1` for the Python 2 only version of rst2pdf and `v2` for the Python 3 only version.

This is on the assumption that Python 3 is the future and we can deprecate the Python 2 version and that trying to maintain support for both in one code base complicates life and prevents us from take full advantage of v3.

Thoughts?

**Comment by holdenweb** [comment]
I suppose that depends on your intentions about supporting new functionality in the Python 2 version. If features are to be added for both versions then you would probably find it easier to maintain a dual-version codebase. If at some stage (presumably quite soon) you are prepared to drop support for Python 2 then a separate 3-only release might be appropriate. Python 3 is the future, but many programs are surprisingly easy to adapt for a dual-language environment. You might consider recasting your Python 2 so that a reasonably efficient 2to3 translation exists.

If you send a snail mail address to steve@holdenweb.com I'll be happy to ship you a free copy of _Python in a Nutshell_ to help your migration.

**Comment by ramonsuarez** [comment]
This is still happening today. The workaround by @jflalande did not work for me. Anybody has an idea on how to make it work? Thanks

**Comment by akrabat** [comment]
@ramonsuarez Are you using Python 2.7?

**Comment by holdenweb** [comment]
Referring to this specific issue, a simple rewrite of the offending line to `except ValueError, as v:` should render it 2.7/3.x comatible at source level.

**Comment by ramonsuarez** [comment]
@akrabat No, python 3

**Comment by akrabat** [comment]
As of today, rst2pdf is a Python 2 project.

**Comment by oz123** [comment]
This is a Python3 \ Python2 issue. Unfortunately, Python3 isn't supported yet.
