### ISSUE TITLE
Sphinx can't import extension rst2pdf.pdfbuilder

### ISSUE THREAD

**Issue by ghost** [rst2pdf/rst2pdf#603]
I'm trying to use sphinx to generate pdfs, and it can't find the pdfbuilder extension.
The command I'm using is `sphinx-build -ab pdf . ../sphinx-build`. Sphinx-build version is 1.4.8, and rst2pdf version is 0.93.dev-r0 (installed via pip. python version 2.7.10, macOS Sierra 10.12.1).
I read the Sphinx section of the manual, and added the default config options to my conf.py. Yet running sphinx-build results in the following error:

```
Extension error:
Could not import extension rst2pdf.pdfbuilder (exception: No module named pdfbuilder)
```

**Comment by spencer-rig** [comment]
Also confirmed that the same thing happens when I install rst2pdf via github (as described in the Readme).

**Comment by nyarbin** [comment]
The cause appears to be that rst2pdf is carrying along version 0.6.2 of Tenjin, rather than the more modern [1.1.1](https://pypi.python.org/pypi/Tenjin/). Tenjin itself doesn't seem to have been touched in 4 years, so someone might want to fork that.

**Comment by cogitas3d** [comment]
I solved installing rst2pdf in my Ubuntu Linux:

`sudo apt-get install rst2pdf`

**Comment by lornajane** [comment]
This doesn't seem to be an issue now (rst2pdf 0.98 is Python 3 and we've updated most of the dependency requirements too. Please re-open if you see it again though!)
