### ISSUE TITLE
Support TOC Subheaders in PDF

### ISSUE THREAD

**Issue by rogersachan** [rst2pdf/rst2pdf#605]
## Details

* Project URL: https://docs.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/docs/
* Read the Docs username (if applicable): 

## Expected Result

Subheaders rendered in TOC

## Actual Result

Did not render

## Images of Proof

![ddd](https://cloud.githubusercontent.com/assets/7173984/21736936/6e9a1c36-d442-11e6-9962-f63e416555ac.PNG)

![dddd](https://cloud.githubusercontent.com/assets/7173984/21736946/8484b7d6-d442-11e6-8668-dd0d30d0a040.PNG)

**Comment by ralsina** [comment]
Those images look suspiciously like sphinx rendering HTML and LaTex, so, probably not rst2pdf related?
