### ISSUE TITLE
Broken Python2 support with Python3

### ISSUE THREAD

**Issue by netrounds-joakim** [rst2pdf/rst2pdf#608]
This commit breaks Python2 support by using stuff like `__next__`

https://github.com/rst2pdf/rst2pdf/commit/c395a25f9f571c68613852c0a9c857be195a771d

Is development of this project abandoned, or are you officially dropping Python2 support? otherwise these changes should be reverted, or made to work properly in Python 2 as well.

This is just one issue relating to broken Python2 support, some others:
https://github.com/rst2pdf/rst2pdf/pull/607
https://github.com/rst2pdf/rst2pdf/issues/604  (same as this)
https://github.com/rst2pdf/rst2pdf/issues/596

**Comment by akrabat** [comment]
As per #618, `master` is reset back to Python 2.

Hopefully, in the future, moving to Python 3 will be done much more carefully…
