### ISSUE TITLE
Error in rst2pdf with python 3.6 and sphinx

### ISSUE THREAD

**Issue by vikrantrathore** [rst2pdf/rst2pdf#609]
While adding rst2pdf as extension for sphinx for Python 3.6.0 it has following error:

```
Running Sphinx v1.5.3

Exception occurred:
  File "/Users/test123/projects/lib/python3.6/site-packages/sphinx/application.py", line 512, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/Users/test123/projects/lib/python3.6/site-packages/rst2pdf/pdfbuilder.py", line 129
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by dresber** [comment]
I have the same error but with python 3.5.2 

Here is the error.log

> # Sphinx version: 1.5.3
> # Python version: 3.5.2 (CPython)
> # Docutils version: 0.13.1 release
> # Jinja2 version: 2.9.5
> # Last messages:
> 
> # Loaded extensions:
> Traceback (most recent call last):
>   File "c:\envs\python35_64bit_li_can_mst_emu\lib\site-packages\sphinx\cmdline.py", line 295, in main
>     opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
>   File "c:\envs\python35_64bit_li_can_mst_emu\lib\site-packages\sphinx\application.py", line 199, in __init__
>     self.setup_extension(extension)
>   File "c:envs\python35_64bit_li_can_mst_emu\lib\site-packages\sphinx\application.py", line 512, in setup_extension
>     mod = __import__(extension, None, None, ['setup'])
>   File "c:\\envs\python35_64bit_li_can_mst_emu\lib\site-packages\rst2pdf\pdfbuilder.py", line 129
>     except Exception, e:
>                     ^
> SyntaxError: invalid syntax

**Comment by troyhoffman** [comment]
Sorry, but from readme.rst:

"It does not support Python 3"
