### ISSUE TITLE
PageBreak in nested lists broken / "AttributeError: MyPageBreak instance has no attribute 'width'"

### ISSUE THREAD

**Issue by rkoe** [rst2pdf/rst2pdf#610]
Sometimes it's necessary to make a PageBreak in a nested list. But this unfortunately does not work, but fails with the exception "AttributeError: MyPageBreak instance has no attribute 'width'".

Details:

- PageBreak in a list works
- Spacer in a nested list works
- PageBreak in a nested list (instead of the Spacer) fails

Example:

> `Pagebreak in a list: works`
>
> `- page 1`
> 
> `.. raw:: pdf`
> 
> `    PageBreak`
> 
> `- page 2`
> 
> `-------- `
>
> `Spacer in a nested list: works`
> 
> `- point 1`
> 
> `  - page 1`
> 
> `  .. raw:: pdf`
> 
> `    Spacer 0,5`
> 
> `  - page 2`
> 
> `- point 2`
> 
> `-------- `
>
> `Pagebreak in a nested list: fails with AttributeError`
> 
> `- point 1`
> 
> `  - page 1`
> 
> `  .. raw:: pdf`
> 
> `    PageBreak`
> 
> `  - page 2`
> 
> `- point 2`

**Comment by ralsina** [comment]
Sadly, this is not really doable because of reportlab limitations, a PageBreak flowable can't be nested like this.
