### ISSUE TITLE
'BuildeEnvironment' object has no attribute 'modules'

### ISSUE THREAD

**Issue by forzenheart** [rst2pdf/rst2pdf#613]
when i run rst2pdf with sphinx
In my conf.py,
when i write this:

pdf_documents=[('index', u'mydoc', u'mydoc', u'author'),]

then call 

make pdf,

i got  'BuildeEnvironment' object has no attribute 'modules'.
[ERROR] pdfbuilder.py:106  'BuildeEnvironment' object has no attribute 'modules'.

**Comment by forzenheart** [comment]
sphinx version 1.5.1
rst2pdf version 0.12.2
platform: windows

**Comment by akrabat** [comment]
I cannot reproduce with the information here. I suspect that it's been fixed, but if it's still a problem, please reopen and include a full set of files required to reproduce. Thanks.
