### ISSUE TITLE
Project update: Plan to release rst2pdf 0.94

### ISSUE THREAD

**Issue by akrabat** [rst2pdf/rst2pdf#618]
All,

@pmaupin very kindly has given me access to the project; thanks!

My current plan is to sort out a bug fix release that tidies up whatever bugs are important to anyone (that we can fix in the current codebase!) and see if we can get out a 0.94 release at some point in the short-ish term. 

I'm not planning to move mountains and get a version out that supports Python 3 quite yet as I need to find my feet first, but I feel we can fix some niggles without doing major surgery at the same time!

**Comment by pmaupin** [comment]
It's time-consuming no matter what.  There is a tool in pdfrw (maybe in
rst2pdf too?) that invokes imagemagick and/or okular and/or acroread to
allow you to compare two different PDFs, and then allows you to mark new
data for the PDF.

But to work around some of the reportlab version-change issues, pdfrw
re-filters the data through itself.  That's only for the few tests in the
reportlab directory (examples/rl1 and examples/rl2).  If you do that, there
will be fewer changes to have to examine.

As rst2pdf can make use of pdfrw and it's already a dependency, you could
certainly use pdfrw for tests in a similar fashion.

Regards,
Pat

**Comment by ralsina** [comment]
Putting it here because I don't know where else ... I created a bunch of PRs. I am fairly confident they are ok ... should I just start merging them?

**Comment by lornajane** [comment]
Honestly now there are a few of us around, I suggest we try to have a second reviewer wherever possible - not least because it will help us newcomers visit more of the codebase and get to know different bits of the project better.

**Comment by ralsina** [comment]
Ok, so I got impatient and merged the bugfix ones. Sorry about doing it unconsulted but I am pretty excited about rst2pdf nowadays for some reason :-)

**Comment by akrabat** [comment]
I'm back in the office today from 10 days of travel. Hoping to go through the PR queue over the next few evenings.

**Comment by ralsina** [comment]
Sorry @akrabat @lornajane I was not trying to make anyone feel bad about not reviewing, if it came across that way I wholeheartedly apologize

**Comment by akrabat** [comment]
Oh, I love the enthusiasm  :) 

You're doing some awesome work on the project, and I'm sorry that I managed to pick this time to be away.

**Comment by akrabat** [comment]
@ralsina I think we're in a good position to release 0.94 to wherever pip will find it.

How do I go about doing this?

**Comment by ralsina** [comment]
I can probably do it :-)

If you want to take a shot, I would:

* Update version numbers in the code / changelog
* Make a tag
* Make a release in GH
* Upload it to pypi.org (if you don't have permission, then we should fix
this too)

**Comment by akrabat** [comment]
Thanks. I'll have a go and shout when things go wrong. Would be useful to know the process.

**Comment by ralsina** [comment]
Since the last release was ages ago, everything written about it would be
out of date anyway

**Comment by akrabat** [comment]
@ralsina Can you add me as a collaborator to the pypi.org project please?

On the PyPI website, select the project, choose manage and then collaborators on the left. My username is `akrabat`.

**Comment by ralsina** [comment]
Done

**Comment by akrabat** [comment]
> Done

Thanks!

**Comment by akrabat** [comment]
0.94 released! 

* PyPI: https://pypi.org/project/rst2pdf/0.94/
* Tag: https://github.com/rst2pdf/rst2pdf/releases/tag/0.94
