### ISSUE TITLE
Reinstate Travis for master

### ISSUE THREAD

**Issue by akrabat** [rst2pdf/rst2pdf#621]
We need to re-instate Travis tests for `master`. At a minimum, It needs to test for Python 2.7 with ReportLap 3.4.0.

For this to happen, every test needs to be run and the output PDF manually checked. If okay, then the hash needs to be updated using `cd tests; python setmd5.py good output/{name-of-test.pdf} `.

**Comment by akrabat** [comment]
Initial work on this here: https://github.com/rst2pdf/rst2pdf/compare/master...akrabat:travis?expand=1

**Comment by alexwlchan** [comment]
I had a quick go at getting Travis running against master here, based on some stuff in the dev branch, but I have no idea how complete a test coverage it might be getting. This was a quick on-the-train-to-work job: https://github.com/alexwlchan/rst2pdf/pull/3

Most of the tests fail with unknown MD5 hashes: https://travis-ci.org/alexwlchan/rst2pdf/builds/297502572

**Comment by akrabat** [comment]
I couldn't get dev to work with python 2, so that's interesting. I got this far with `master`: https://github.com/rst2pdf/rst2pdf/compare/master...akrabat:travis?expand=1

**Comment by alexwlchan** [comment]
> I couldn't get dev to work with python 2, so that's interesting

I didn’t try to get dev running with Python 2, but Travis is running against that branch so I tried to cherry-pick the bits that looked useful from a dev..master diff.

I really don’t know much about the project yet, so this could be totally wrong!

**Comment by akrabat** [comment]
Very strange. I'll have to look at what's going on with my setup!

As per, #618, I think that getting a release out from master is the logical next step though. 

Maybe dev is stable enough to release from though?

**Comment by akrabat** [comment]
Ah, your green-travis branch is from master, which explains why it works :)

**Comment by akrabat** [comment]
In order to minimise overlap of work, I've raised PR #624. The first 15 tests pass and the remainder need md5 hashes updated. Please raise PRs against my `travis` branch to fix things.

**Comment by lornajane** [comment]
If anyone has time to try this on their own machine, I am using this two-line setup to compare my test outcomes with the ones listed above.
[officialfail.txt](https://github.com/rst2pdf/rst2pdf/files/1937254/officialfail.txt) is the list above in a text file.

From `/rst2pdf/tests` try this:

```
nosetests -i regulartest -i sphinxtest 2>&1 | grep "FAIL: " | cut -d' ' -f2 > myfailure.txt
wc -l myfailure.txt
diff officialfailure.txt myfailure.txt
```

This will show how many failed tests you have (there are 47 failures in the official list above) and then how your output differs (if at all).

For me the output looks like this:

```
$ wc -l myfailure.txt
47 myfailure.txt
$ diff officialfail.txt myfailure.txt 
1d0
< test_fancytitles.txt
9a9
> test_issue_311.txt
17a18
> test_issue_73.txt
23d23
< test_uml_extension.txt
```

This means that I have 2 extra passing tests: fancytitles and uml_extension - but also 2 additional failures issue_311 and issue_73 that I will try to look more closely at.

**Comment by akrabat** [comment]
With #656 & #659, Travis now passes! 

Issue #660 covers what to do about the tests that are skipped.
