### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by akrabat** [rst2pdf/rst2pdf#622]
Personally, I like and have used the [Contributor Covenant](https://www.contributor-covenant.org) on other projects.

Does anyone disagree or have another preference?

/ht @oesteban

**Comment by pmaupin** [comment]
Informal systems can be problematic.  But formal systems can be problematic, as well.  Have you had experiences which lead you to believe that adding this formality at this stage will be useful and/or necessary?

**Comment by akrabat** [comment]
The main advantage I've seen has been clarity of expectations. Anecdotally, we've had devs say to us privately that they only considered submitting a PR because the CoC gave them the confidence that they wouldn't be attacked in the comments.

Practically, given the current essentially dormant status of this project, it's not "necessary", but it doesn't hurt to explicitly state that the project's values and knows how to deal with problems.

**Comment by akrabat** [comment]
Totally happy to go with the Python one - makes total sense to do so.
