### ISSUE TITLE
SyntaxError in pdfbuilder.py

### ISSUE THREAD

**Issue by kevin-wyx** [rst2pdf/rst2pdf#642]
https://github.com/rst2pdf/rst2pdf/blob/master/rst2pdf/pdfbuilder.py#L915

```python
    return {
        'version', rst2pdf.version,
        'parallel_read_safe': True,
        'parallel_write_safe': False,
    }
```

Should be ":" after version not ","

**Comment by akrabat** [comment]
Fixed by https://github.com/rst2pdf/rst2pdf/pull/644
