### ISSUE TITLE
Create a project website/landing page

### ISSUE THREAD

**Issue by lornajane** [rst2pdf/rst2pdf#648]
Create a simple website with GitHub pages on the main repo.  It should use a simple, clean template and include information about:
 - what the project is (for)
 - download/installation/setup instructions for various platforms
 - how to get started creating documents with rst2pdf, with simple starter-pack examples for documents and slide decks
 - other useful resources for working with rst2pdf
 - a section on showing what we all made with rst2pdf
 - how to contribute to this website!

**Comment by oz123** [comment]
Probably not a bad idea.

**Comment by oz123** [comment]
@akrabat there is still the original site. Should this replace it? does anyone know what is with @ralsina ?

**Comment by akrabat** [comment]
As far as I know, the original site is http://rst2pdf.ralsina.me which contains a landing page and the manual in HTML form.

It appears to use [Nikola](https://github.com/getnikola/nikola) which uses rst, which presumably allowed it to easily render the manual.

**Comment by oz123** [comment]
Is it possible to link to a new home page ? I would love to hear a comment from @ralsina .

**Comment by ralsina** [comment]
Sure, what do you need?

**Comment by oz123** [comment]
Hi, how can new content be deployed for the website? For example...

**Comment by ralsina** [comment]
It's probably a better idea to just setup rst2pdf.github.io and deploy there. I can setup a redirect on my server.

**Comment by oz123** [comment]
@ralsina I agree, but it sounds better when it comes from you.
@lornajane the way is now clear, would you like to take care of the page?

**Comment by lornajane** [comment]
I can certainly get things started.  I won't have permission to create the repo but if someone can do that and then either configure for github pages or give me enough access to do that myself, I can begin from that point.

**Comment by akrabat** [comment]
> I can certainly get things started. I won't have permission to create the repo but if someone can do that and then either configure for github pages or give me enough access to do that myself, I can begin from that point.

Done. https://github.com/rst2pdf/rst2pdf.github.io

**Comment by ralsina** [comment]
Cool :-)

Setting up the redirect now.

**Comment by lornajane** [comment]
The page now exists and also contains a copy of the PDF manual.  Some working examples are next on my list, feel free to open issues for other things that should be included.
