### ISSUE TITLE
Add an Issue Template

### ISSUE THREAD

**Issue by shreyasbapat** [rst2pdf/rst2pdf#649]
We probably need an issue template to make all the issues more uniform and posting an issue more user friendly

**Comment by shreyasbapat** [comment]
You can check this: 
https://github.com/poliastro/poliastro/blob/master/ISSUE_TEMPLATE.md

**Comment by akrabat** [comment]
The old Google Code project asked these questions:

* Version of rst2pdf?
* Version of reportlab?
* Are you using wordaxe, and if true, what version?
* Are you using rst2pdf with Sphinx, and if true, what version?


We should probably ask which version of Python too.

**Comment by shreyasbapat** [comment]
Do you mind if I make a Pull Request?

**Comment by akrabat** [comment]
> Do you mind if I make a Pull Request?

Go for it!
