### ISSUE TITLE
Line numbers are incorrect

### ISSUE THREAD

**Issue by akrabat** [rst2pdf/rst2pdf#662]
`test_issue_310` is failing. This needs to be investigated and solved.

**Comment by ralsina** [comment]
The code blocks support in rst2pdf predates reSt's so it could maybe just be deleted.

**Comment by akrabat** [comment]
This may be a case of me not understanding the test!

```
.. code-block:: text
   :linenos:
   :include: include
   :linenos_offset:
   :start-at: Line 3
```

I didn't realise that you could put the text of the line, rather than the line number in `start-at`…

**Comment by ralsina** [comment]
What happens if you start at line 0? It may just be a case of an off-by-one :-)

**Comment by akrabat** [comment]
There is no `Line 0` in [include](https://github.com/rst2pdf/rst2pdf/blob/master/rst2pdf/tests/input/include)…

**Comment by akrabat** [comment]
The other problem is:

```
.. code-block:: text
   :linenos:
   :include: include
   :linenos_offset:
   :start-after: Lin
```

produces line numbers that are off by one too:

![screen shot 2018-05-03 at 08 45 47](https://user-images.githubusercontent.com/33135/39565043-64b945e2-4eae-11e8-921f-3866929fa90e.png)
