### ISSUE TITLE
Acrobat Reader cannot open generated pdf with too many chapters

### ISSUE THREAD

**Issue by Kamil-D** [rst2pdf/rst2pdf#666]
Subject: Acrobat Reader cannot open generated pdf with too many chapters

I encountered a problem with opening pdf generated by Sphinx 'make pdf' command. As it turned out I can open file on the browser or by another pdf reader but the problem is when using Adobe Acrobat Reader. An error on Adobe software is - "There was an error processing a page. There was a problem reading this document (15)".
I made an investigation and I discovered that mentioned error occurs only when document has too many chapters (not regardless of the level of nesting). I thought that the problem is with some marks with whom Adobe can't handle but no.
To sum up - this is probably some kind of rst2pdf bug. Have you got any clues how to solve this problem for this moment?
If there is any possibility to get previous version of rst2pdf using "pip"?

I found quite similar issue on the stackoverflow but the given solution doesn't work in my case (setting uppdf_break_level to 0).
https://stackoverflow.com/questions/25838717/sphinx-pdf-output-is-bad-how-do-i-chase-down-the-cause

Please check attached "Sample Sphinx.zip" file - there are all project files.

Procedure to reproduce the problem
Just add a new one chapter on the "one.rst" or "two.rst" file and generate pdf file. Then an error will show up during opening .pdf in Acrobat Reader.

Environment info
OS: Windows 7 (64 bit)
Python version: 2.7.9
Sphinx version: 1.7.3
Rst2pdf version: 0.93.dev-r0
Extra tools: Google Chrome 66.0.3359.139, Adobe Acrobat Reader DC 18.009.20044.55097 (the newest one)

[Sample Sphinx.zip](https://github.com/rst2pdf/rst2pdf/files/1999802/Sample.Sphinx.zip)

Best Regards,
Kamil

**Comment by akrabat** [comment]
@Kamil-D Is this with the latest GitHub version or with the version installed via pip?

**Comment by Kamil-D** [comment]
@akrabat I've just updated my comment - I included rst2pdf version. Thank you for very fast response! :)

**Comment by akrabat** [comment]
Logically, setting `pdf_toc_depth` in `conf.py` should reduce the number of chapter entries, but it didn't seem to do anything.

**Comment by lornajane** [comment]
Since we couldn't replicate this issue, I'm going to close for now because I'm not sure how we would fix this. If there's more information or it happens again please do let us know.
