### ISSUE TITLE
Two-column layout with single column header?

### ISSUE THREAD

**Issue by tehKaiN** [rst2pdf/rst2pdf#676]
I'm kinda new to .rst, so perhaps it's a silly one. I've done something like that:

``` rst
.. raw:: pdf

    PageBreak twoColumn

Header 3
-------------

Lorem ipsum dolor sit amet...

.. raw:: pdf

    PageBreak oneColumn
```

But I get "Header 3" in first column, and I'd like to only have paragraphs placed in twoColumn, so that text won't appear aside the header. How can I achieve something like that? Plz don't tell me that it's impossible, because I **really** don't want to use LaTeX.

![columns](https://user-images.githubusercontent.com/16180344/42633552-230e6504-85e1-11e8-9516-4370493a8c72.PNG)

**Comment by akrabat** [comment]
I set up a new page style that I call `TPage`:

```
    TPage:
        frames: []
            [0%, 75%, 100%, 20%]
            [0%, 0%, 49%, 79%]
            [51%, 0%, 49%, 79%]
        showHeader: false
        showFooter: true
```

This sets up a "bar" along the top that's 100% wide for the title and then two equal sized columns.


Example of use:

```rst
.. raw:: pdf

    PageBreak TPage


Header 3
========

.. raw:: pdf

   FrameBreak

Lorem ipsum dolor sit amet...


.. raw:: pdf

    PageBreak oneColumn

```

**Comment by tehKaiN** [comment]
Thanks!
