### ISSUE TITLE
Problem with some fonts like: hindi, korean, telugo, etc

### ISSUE THREAD

**Issue by cogitas3d** [rst2pdf/rst2pdf#677]
Hi!

I tryied to use Rst2PDF to output a PDF, all run well, but when I open the file appear it:

![captura de tela de 2018-07-15 21-17-30](https://user-images.githubusercontent.com/2422483/42740364-8139d376-8874-11e8-839b-9cb93fcc4074.png)

Do you know how can I solve it?

A big hug!

**Comment by ralsina** [comment]
That looks like the font you are using by default has no coverage for those
languages.

You could try switching to a font with higher coverage such as Noto.

**Comment by cogitas3d** [comment]
Hi @ralsina !

Thank you very much!

**Comment by ralsina** [comment]
Did it work? :)
