### ISSUE TITLE
linkColor tag doesn't set link color when converting rst to pdf

### ISSUE THREAD

**Issue by avolkov** [rst2pdf/rst2pdf#682]
Unable to override default linkColor tag value when specifying value in the the stylesheet

Created an rst document with a link (ie test@test.com) that loads a stylesheet with linkColor tag set to anything other than navy. Convert rst document with pdf. All the links will still have default color set to navy.

I.e

test.rst:

test@test.com

Test.style:

{
   "linkColor: "white"
}

rst2pdf test.rst -s slides.style

I think there's an issue in the sequence of how stylesheets are loaded in rst2pdf/styles.py readSheets method. It looks like existing values loaded through default style sheets don't get properly overridden by custom sheets. I'll add a patch later 

I tried specifying linkColor in a different places in slides.style, including top level, but the linkColor style doesn't seem to get overriden

**What is the expected output? What do you see instead?**
When specifying linkColor at the top level of slides.style that gets loaded into rst2pdf, all links in the resulting pdf file should be of color specified by linkColor tag

🖥 **Versions**

`python -V`
Python 2.7.14

`pip freeze | grep rst2pdf`
rst2pdf==0.93.dev0
`pip freeze | grep reportlab`
reportlab==3.5.6

`pip freeze | grep Sphinx`

(Optional) wordaxe version :

Which operating system are you using?
Debian buster/sid
**Additional information**

I want tag linkColor to work

linkColor tag will work

**Comment by avolkov** [comment]
Never mind, I can't reproduce the issue any more.

**Comment by akrabat** [comment]
This works for me:

test.pdf:
```
test@test.com
```

test.style:
```
{
"linkColor": "orange"
}
```

command:
```
rst2pdf test.rst -s test.style
```

Note that I had to correct your style sheet as it's missing a closing `"` after `linkColor` before the colon.

**Comment by q2dg** [comment]
I'd want to note that "linkColor" isn't even mentioned in official manual (https://rst2pdf.org/static/manual.html)

**Comment by sachin-suresh-rapyuta** [comment]
I defined my styles in .yaml file and `linkColor` works. However, the link color for `ref` doesn't work with this style.
