### ISSUE TITLE
remove smartypants

### ISSUE THREAD

**Issue by oz123** [rst2pdf/rst2pdf#694]
During my work on porting the code to python3 I noticed the module `rst2pdf/smartypants.py`.
This module is available as a [pypi package][1], and it seems to be maintained and ported to Python3.
Does anyone object me removing it from the code base and adding this to requirements.txt?

[1]: https://pypi.org/project/smartypants/

**Comment by ralsina** [comment]
I think that's a great idea. It was not packaged at the time :-)

**Comment by akrabat** [comment]
Agreed. Using someone else's work is nearly always my preference to maintaining it myself!

**Comment by oz123** [comment]
I looked into this a little bit, and it turns out, it's not just deletion and changing the imports.
This is because smartypants from pypi has done some changes to support Python3, I see
alot of errors like this:
```
   File "...Software/rst2pdf/venv2/lib/python2.7/site-packages/smartypants.py", line 198, in smartypants
*     do_quotes = attr & Attr.q
* TypeError: unsupported operand type(s) for &: 'str' and 'int'
```
Hence, I first intend to finish what I started in  https://github.com/rst2pdf/rst2pdf/pull/691 and then remove smarty pants.
