### ISSUE TITLE
remove tenjin? replace? 

### ISSUE THREAD

**Issue by oz123** [rst2pdf/rst2pdf#696]
The code base also has a template engine Tenjin.
It's seems that upstream has a version ported to Python3.2

Also, I still don't understand what is it used for. Maybe @ralsina  can explain in a sentence or two.

**Comment by ralsina** [comment]
It's used to render the cover from a template at least. Probably nothing
else.

Nowadays it's probably better to just use jinja2 or maybe just template
strings: https://docs.python.org/2/library/string.html#template-strings

**Comment by oz123** [comment]
The templates that are found in the source code contain some logic (if ... else ) which is more than just string substitution. Hence, I think Jinja2 is the way to go.

**Comment by akrabat** [comment]
jinja2 has the benefit of being widely used, so makes sense to me.
