### ISSUE TITLE
Formatting of the codebase is bad

### ISSUE THREAD

**Issue by ralsina** [rst2pdf/rst2pdf#711]
It's mostly my own fault, too!

But yes, really bad. Now that we have tools like black ... how about a PR that reformats the whole thing?

I can do it if needed.

**Comment by akrabat** [comment]
To be honest, I'd rather we got it running on latest ReportLab and other dependencies with the tests passing first.

Reformatting to a known standard isn't a bad idea, but I really want 0.94 published and working on on a modern Python 2.7.

**Comment by ralsina** [comment]
Ok, can you add a list of things in the 0.94 issue? I can work on it (long weekend!)

**Comment by oz123** [comment]
I also believe that it's better to fix this issue gradually.

**Comment by oz123** [comment]
> Ok, can you add a list of things in the 0.94 issue? I can work on it (long weekend!)

Removing smarty-pants and making sure rson works with python3 would be good.

Also, rson isn't really well documetd, maybe cson could replace it? This would be a breaking change though... https://github.com/avakar/pycson/
