### ISSUE TITLE
Random numbers displayed in CLI output

### ISSUE THREAD

**Issue by akrabat** [rst2pdf/rst2pdf#712]
Since I last pulled a few weeks ago something is outputting random numbers when I compile my rst file:

```
rst2pdf presentation.rst \
        -b1 \
        --fit-background-mode=scale \
        --smart-quotes=0 \
        --fit-literal-mode=overflow \
        -s style-gap.style,style-main.style \
        -s style-blackbg.style,style-blackbg-rka-code.style \
        --output="../presentation.pdf" \
        -e preprocess 
2824
927
581
1355
907
342
1309
[Finished in 5.2s]
```

Can someone find and remove them please? :)

**Comment by ralsina** [comment]
Tghis is the bad commit, fixing in a bit

https://github.com/rst2pdf/rst2pdf/search?q=4cf680047ebe2af4328479b2a1ae5bc20a08b081&type=Commits

**Comment by akrabat** [comment]
I was confident you'd find it faster than I would! 👍

**Comment by akrabat** [comment]
Though, it really should go through a PR!

**Comment by ralsina** [comment]
`git bisect` is good at this :-)

If it were more than removing a `print()` I would have done a PR, but sure, next time.
