### ISSUE TITLE
We are missing reference artifacts

### ISSUE THREAD

**Issue by ralsina** [rst2pdf/rst2pdf#716]
There are a number of test cases where:

1. The test passes in master
2. We have no reference artifact

That means we can't use @lornajane 's script to automatically check for visual differences when upgrading reportlab.

So: one-time-thing, I will do a PR to add reference artifacts in those cases.

Additionally, we have artifacts without a known good checksum!

```
BAD ARTIFACT: unknown  reference/test_issue_349.pdf
BAD ARTIFACT: unknown  reference/test_issue_175.pdf
BAD ARTIFACT: unknown  reference/sphinx-issue251.pdf
```

I will check those manually and add the checksum if they are ok, or remove the artifact instead.

**Comment by akrabat** [comment]
Yep. This is the situation for the tests I fixed yesterday.

Essentially, I manually checked the PDF against the rST file and then added it to reference/.

**Comment by akrabat** [comment]
It didn't occur to me to find them from master and add them :)
