### ISSUE TITLE
Sphinx 1.8.0+ changes sphinx-issue168

### ISSUE THREAD

**Issue by akrabat** [rst2pdf/rst2pdf#721]
From Sphinx 1.8.0+, `:linenothreshold: 5` isn't working when defined like this:

```rst

.. highlight:: python
   :linenothreshold: 5

.. code-block:: python
   
   "This has more than 5 lines, so it has linenos"
   "This has more than 5 lines, so it has linenos"
   "This has more than 5 lines, so it has linenos"
   "This has more than 5 lines, so it has linenos"
   "This has more than 5 lines, so it has linenos"
   "This has more than 5 lines, so it has linenos"
   "This has more than 5 lines, so it has linenos"
```

With Sphinx 1.7.9 or lower, this code block has line numbers, but with Sphinx 1.8.0 or higher, it doesn't.

**Comment by ralsina** [comment]
Does it work in the html sphinx builder?

**Comment by ralsina** [comment]
With sphinx 1.7.9 it doesn't even work in HTML. I think this is just broken in sphinx.

<img width="882" alt="screen shot 2019-01-09 at 09 37 28" src="https://user-images.githubusercontent.com/1579/50899895-398bfe00-13f2-11e9-8381-079a24e5303f.png">

**Comment by akrabat** [comment]
In Sphinx 1.8.0+, the `self.document` passed to `PDFWriter` method is missing the `highlightlang` node, so the `visit_highlightlang` function is never called.

**Comment by akrabat** [comment]
https://github.com/sphinx-doc/sphinx/pull/5508 is the where it was fixed. Sphinx 2.0+ required.
