### ISSUE TITLE
Support pdfTeX

### ISSUE THREAD

**Issue by Evidlo** [rst2pdf/rst2pdf#734]
I glanced through the manual and issues for any information on this, but couldn't find anything.  Is there any support for pdftex instead of matplotlib's TeX rendering engine?

**Comment by akrabat** [comment]
I don't believe there is support for pdftex. Can you summarise what you see as the advantages of supporting it?

**Comment by akrabat** [comment]
Thanks. That sounds like something we should certainly look into.

**Comment by ralsina** [comment]
Well, if you want to support TeX you can just use rst2latex :-)

The only reason the matplotlib tex subset is supported is to have *some* math support without installing TeX

**Comment by Evidlo** [comment]
One of the main reasons I like rst2pdf is that I can stylize using CSS.  I don't think I can do this rst2latex.

**Comment by ralsina** [comment]
You already can render rst via latex. It's included by default in docutils.

**Comment by lornajane** [comment]
I am not sure we have a clear use case for this so I will close the issue BUT I want to make super clear that a contribution of this type of functionality would be really welcome in this project and would get good attention :)
