### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by akrabat** [rst2pdf/rst2pdf#742]
We need to decide how to do Python 3 support.

The two options I see are:

1. Two separate codebase where the Python 2 version is in maintenance mode and the Python 3 version is actively worked out.
2. One codebase that supports both Python 2 and 3.

If we go with option 1, then I think that we should get the current Python 2 code to 1.0 and then start a new branch for Python 3 which will be 2.0. The intention would for 1.0 would be to only fix bad bugs, so it's essentially a stable release that those people on Python 2 can continue to use.

Alternatively, option 2 suggests that 1.0 will run on both Python 2 and Python 3. This limits our options for using Python 3 syntax and features though which could be a problem going forward.

To my mind, it all depends on how many Python 2 installations there will be after 1st January 2020 which is when Python 2 is end of life? See also #537.

## Packaging 

We also need to think about packaging. Ideally most users should install rst2pdf via their package manager, so that's apt/yum on Linux, Home-brew on Mac and "something" on Windows! I presume we need to be on the system installed Python for the native package manager?

Related to this, I went to a lightning talk at FOSDEM on [Snapcraft](https://snapcraft.io) and I think we need to be here and probably in other app-stores if there are any others? I'll open a separate issue on this.

Thoughts?

**Comment by flying-sheep** [comment]
The porting process is also worth consideration.

Porting to 2+3 gradually while maintaining function is slower but one is never in fear of having made wrong assumptions. We’d start blacklisting everything for python 3 CI, then gradually port submodules, while enabling their tests.

Porting to 3 while breaking everything means we get to the end faster. We’ll benefit more from new idioms even while porting. But there’s a risk that everything ends up too broken and the porting branch will be abandoned.

**Comment by ralsina** [comment]
On Tue, Feb 12, 2019 at 8:46 AM Philipp A. <notifications@github.com> wrote:

> The porting process is also worth consideration.
>
> Porting to 2+3 gradually while maintaining function is slower but one is
> never in fear of having made wrong assumptions. We’d start blacklisting
> everything for python 3 CI, then gradually port submodules, while enabling
> their tests.
>
> Porting to 3 while breaking everything means we get to the end faster.
> We’ll benefit more from new idioms even while porting. But there’s a risk
> that everything ends up too broken and the porting branch will be abandoned.
>
>
Considering the size of the codebase and how much effort is going into
this... rewriting all things as idiomatic python 3 is never going to happen.

What I would do (and I am even willing to actually do!) is to make it a 2&3
codebase. In fact, I sort of have done that!

If you look at https://github.com/rst2pdf/rst2pdf/pull/740 you can see a
small changeset that, except for the setup.py changes, could be merged into
the current master and probably break nothing, but makes the codebase
py3-compatible (in the sense that it works, not in the sense that it works
perfectly)

I would think releasing a py2-only 1.0 would be not-great. A py2+3 1.0
would be great. And then we can deprecate py2 immediately after and release
rst2pdf 2.0 in a few months with the only main feature being that it's
py3-only (and, hopefully, that it is properly formatted and runs
pylint/flake8 as part of the testsuite)

From then forward, new code is not required to work with py2, and old ugly
code can be fixed opportunistically.

**Comment by akrabat** [comment]
I'm good with `1.0` being Python 2 & 3 compatible.

**Comment by akrabat** [comment]
With #744, we rst2pdf now works on both Python 2 and Python 3!
