### ISSUE TITLE
Deprecate svg2rlg?

### ISSUE THREAD

**Issue by ralsina** [rst2pdf/rst2pdf#745]
It's py2-only, not widely used, and inkscape gives much better results (although yes, it's a pain in OSX)

**Comment by akrabat** [comment]
We have some svg tests that aren't passing (they are marked as to be ignored) too, so we need to work in this area anyway.

There's aPy3 port [here](https://github.com/aquavitae/svg2rlg), but doesn't seem very active.

**Comment by ralsina** [comment]
Also, for testing purposes, I am thinking it may be useful to mock inkscape
so we don't depend on it being a specific version.
Just creating a "fake" inkscape that always returns the same PDF :-)

**Comment by lornajane** [comment]
Would we use this every time? I think it's quite helpful that we all have different versions of inkscape and could run the tests in different environments as needed. If I upgrade inkscape and that causes a problem, I'd like to know that there's a problem when I run the tests, not when my PDF won't build correctly.

**Comment by ralsina** [comment]
@akrabat svglib looks promising! Will try to do a PR for it.

**Comment by akrabat** [comment]
> If I upgrade inkscape and that causes a problem, I'd like to know that there's a problem when I run the tests, not when my PDF won't build correctly.

We definitely need it work this way.

**Comment by ralsina** [comment]
My main concern is that I have never, ever, been able to make inkscape work in my mac. That means I can never successfully run the test suite which adds a lot of friction.

**Comment by akrabat** [comment]
I'm happy to have a switch that can be enabled for locally testing with a mocked Inkscape output.

I can't remember how I installed Inkscape on my Mac mind you.
