### ISSUE TITLE
Unexplained padding on images results in new page

### ISSUE THREAD

**Issue by akrabat** [rst2pdf/rst2pdf#753]
Given `presentation.rst`:

```rst
.. image:: coffee.jpg
    :height: 9cm

.. raw:: pdf

   PageBreak aPage

.. image:: coffee.jpg
    :height: 9cm
```

with `slides.style`:

```
pageSetup:
    width: 16cm
    height: 9cm
    margin-top: 0cm
    margin-bottom: 0cm
    margin-left: 0cm
    margin-right: 0cm
    margin-gutter: 0cm
    spacing-header: 0cm
    spacing-footer: 0cm
    firstTemplate: aPage

pageTemplates:
    aPage:
        frames: []
            [0cm, 0cm, 100%, 100%]
        showHeader : false
        showFooter : false
```

and I create a PDF using:

```
rst2pdf -s slides.style presentation.rst -o presentation.pdf
```

I get a PDF with three pages and the two image pages do not have the image full screen.

![preview-of-pdf](https://user-images.githubusercontent.com/33135/53235265-50786e00-3689-11e9-9146-8474f837b788.png)

Where is this padding/margin coming from and how do we remove it?

Coffee image here: https://akrabat.com/stuff/coffee.jpg

**Comment by akrabat** [comment]
Note. Setting the `frame` to be:

```
[0cm, -0.2cm, 100%, 9.4cm]
```

solves the problem - or at least gets the output that I'm looking for!

![preview-of-pdf-oversized-frame](https://user-images.githubusercontent.com/33135/53235653-430fb380-368a-11e9-8221-3e9103c7d03e.png)

**Comment by ralsina** [comment]
Looking at the default stylesheet:

The image class inherits from bodytext, which has a "spaceBefore: 6" that
is probably points, and google tells me it amounts to 0.211cm so maybe
that's the culprit? :-)

**Comment by akrabat** [comment]
Adding 

```
styles:
    image:
        spaceBefore: 0
        spaceAfter: 0
```

to `slides.style` doesn't help.

**Comment by akrabat** [comment]
The output has these warnings:

```
[WARNING] image.py:465 image /Users/rob/Projects/python/test-images/coffee.jpg is too tall for the frame, rescaling
[WARNING] image.py:468 availHeight 243.118110236
[WARNING] image.py:469 ratio 0.75
[WARNING] image.py:470 width 182.338582677
[WARNING] image.py:465 image /Users/rob/Projects/python/test-images/coffee.jpg is too tall for the frame, rescaling
[WARNING] image.py:468 availHeight 243.118110236
[WARNING] image.py:469 ratio 0.75
[WARNING] image.py:470 width 182.338582677
```

I wonder if it's related to the rescaling?

**Comment by ralsina** [comment]
Using --show-frame-boundary shows the frame does cover the whole page, so the frame is ok.
Indeed it seems we are rescaling it too much:

````
[INFO] image.py:426 Image /Users/ralsina/code/rst2pdf/t/coffee.jpg size calculated:  6.750000cm by 9.000000cm [near line UNKNOWN in file presentation.rst]
[DEBUG] basenodehandler.py:172 rst2pdf.basenodehandler.NodeHandler.elemdispatch: docutils.nodes.document
[DEBUG] basenodehandler.py:173 rst2pdf.basenodehandler.NodeHandler.elemdispatch: [near line UNKNOWN in file UNKNOWN]
[DEBUG] basenodehandler.py:175 rst2pdf.basenodehandler.NodeHandler.elemdispatch: <document source="presentation.rst"/>
[DEBUG] basenodehandler.py:178
[INFO] createpdf.py:662 Starting build
[WARNING] image.py:465 image /Users/ralsina/code/rst2pdf/t/coffee.jpg is too tall for the frame, rescaling
```

**Comment by ralsina** [comment]
At the point where the warning is triggered, the available height is 243.1181102362205 points (8.57cm) and the image is 255.11811023622047 points tall (9cm), so these are the same mystery 12 points, 6 on top, 6 on bottom.

**Comment by ralsina** [comment]
So, the answer seems to be "spaceBefore and spaceAfter do nothing in this case and I wonder why"

**Comment by ralsina** [comment]
So, it seems like our SmartFrame object has 6pt paddings all around. Looking to see where they are set and how to change them.

**Comment by ralsina** [comment]
And that's the problem. Those paddings can't be changed.

Here's how SmartFrame is defined:

```python
class SmartFrame(Frame):
    """A (Hopefully) smarter frame object.

    This frame object knows how to handle a two-pass
    layout procedure (someday).

    """

    def __init__(self, container, x1, y1, width, height,
            leftPadding=6, bottomPadding=6, rightPadding=6, topPadding=6,
            id=None, showBoundary=0, overlapAttachedSpace=None, _debug=None):
```

And this is the place where the frame for the page is created:

```python
        self.frames = []
        for frame in self.template['frames']:
            self.frames.append(SmartFrame(self,
                styles.adjustUnits(frame[0], self.tw) + x1,
                styles.adjustUnits(frame[1], self.th) + y1,
                styles.adjustUnits(frame[2], self.tw),
                styles.adjustUnits(frame[3], self.th),
                    showBoundary=self.show_frame))
```

I have checked that by adding extra arguments there this is fixed (see attached PDF) so the fix appears to be adding more options in frame definitions and passing them along here.
[presentation.pdf](https://github.com/rst2pdf/rst2pdf/files/2896777/presentation.pdf)

**Comment by ralsina** [comment]
Working on it...

**Comment by ralsina** [comment]
So, a more extensive test shows this is still buggy, so marking this as WIP
