### ISSUE TITLE
Update pygments stylesheets

### ISSUE THREAD

**Issue by ralsina** [rst2pdf/rst2pdf#761]
We are currently using stylesheets that were generated with the pygments current version of circa 2012. Unsurprisingly, lots have changed in the past 7 years:

* Pygments supports more color schemes
* Pygments stylesheets have more classes
* Some of the class names have changed
* Docutils now uses the long class names for code styling

So, this needs fixing:

* [ ] Update the tool to generate stylesheets from pygments
* [ ] Add the missing color schemes
* [ ] Use (as much as possible) the code highlighter from docutils instead of rst2pdf's own

This is far from trivial, but I sort of know how to do it, so assigning to me.

**Comment by lornajane** [comment]
I'm watching very closely, I'd love to have been able to convert my custom pygments styles over but could never quite figure it out!

**Comment by ralsina** [comment]
@lornajane the current tool kinda sucks but I can do a better one now, since hopefully I am a better programmer than I was in 2009 :-)

**Comment by akrabat** [comment]
I didn't realise there was a current tool!

**Comment by ralsina** [comment]
@akrabat I will add it to the docs somewhere

**Comment by lornajane** [comment]
I'd still love to get the tool and/or help with updating the stylesheets. @ralsina Did you add it to the docs? Do you want to just braindump here and then one of us can run with it?

**Comment by lornajane** [comment]
@ralsina Any more hints on generating pygments stylesheets? I am chomping at the bit for direction here (or if I just should improvise, please say)

**Comment by lornajane** [comment]
We updated to newly generated pygments styles and I can't see us making changes to the syntax highlighting without a much better understand of what problem we are solving and why so I'll close this as I think the main aim was achieved.
