### ISSUE TITLE
Internal links (TOC, sections and figures) have been broken since reportlab updated to 3.5.19

### ISSUE THREAD

**Issue by shamilsan** [rst2pdf/rst2pdf#772]
When updating reportlab from 3.5.18 to 3.5.19, internal links become unusable.

**Description of problem**

Check whether reportlab installed has the version 3.5.19.

RST file: toc.rst
```
===============================
Document with Table of Contents
===============================

-------
Example
-------

.. contents:: Table of Contents
   :depth: 2

Heading 1
=========

Normal, **Bold**, *Italic*.

Heading 2
---------

``Mono``.

Heading 3
~~~~~~~~~

.. code:: python

  #!/usr/bin/env python

  print("Hello, world!")
```

Run: `rst2pdf toc.rst`

Open toc.pdf and try to click to table of contents items.

**What is the expected output? What do you see instead?**
When downgrading reportlab to 3.5.18, links in table of contents work well, but after upgrading they become like `heading-1-...` etc and don't work.

🖥 **Versions**

`python -V`
Python 2.7.16

`pip freeze | grep rst2pdf`
rst2pdf==0.94

`pip freeze | grep reportlab`
reportlab==3.5.19

`pip freeze | grep Sphinx`

(Optional) wordaxe version :

Which operating system are you using?

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.04
DISTRIB_CODENAME=disco
DISTRIB_DESCRIPTION="Ubuntu 19.04"
Linux 5.0.0-13-generic #14-Ubuntu SMP Mon Apr 15 14:59:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Additional information**

I guess this commit breaks the compatibility:
https://bitbucket.org/rptlab/reportlab/commits/c46115a85b61f4822026e72f5949a4fb1b63ba73

**Comment by akrabat** [comment]
PDFs that don't work:

toc.pdf is the generated PDF from the above rest:
[toc.pdf](https://github.com/rst2pdf/rst2pdf/files/3244596/toc.pdf)

Test issue 110: click the links in the footer to go back:
[test_issue_110.pdf](https://github.com/rst2pdf/rst2pdf/files/3244597/test_issue_110.pdf)
