### ISSUE TITLE
NameError when accessing reportlab.Version

### ISSUE THREAD

**Issue by ranjeethmahankali** [rst2pdf/rst2pdf#773]
NameError when accessing reportlab.Version

**Description of problem**
We are using rst2pdf as part of our build pipeline which stopped running properly since last week. This is the error we get:

`$ rst2pdf --stylesheets=<style> <rst file>
Traceback (most recent call last):
  File "c:\users\rmahanka\appdata\local\continuum\anaconda2\envs\py27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\rmahanka\appdata\local\continuum\anaconda2\envs\py27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\rmahanka\AppData\Local\Continuum\anaconda2\envs\py27\Scripts\rst2pdf.exe\__main__.py", line 5, in <module>
  File "c:\users\rmahanka\appdata\local\continuum\anaconda2\envs\py27\lib\site-packages\rst2pdf\createpdf.py", line 91, in <module>
    from rst2pdf import flowables
  File "c:\users\rmahanka\appdata\local\continuum\anaconda2\envs\py27\lib\site-packages\rst2pdf\flowables.py", line 895, in <module>
    if reportlab.Version == '2.1':
NameError: name 'reportlab' is not defined`

The command is:
`rst2pdf --stylesheets=myStyle.style myFile.rst`
But it looks like this happens no matter what I try to do with rst2pdf

I guess insert an import statement inside flowables.py ? I tried this and it makes the problem go away but this is not feasible because our build pipeline runs on a fresh docker image which installs rst2pdf everytime using pip.

**What is the expected output? What do you see instead?**

🖥 **Versions**

`python -V
Python 2.7.15`

`pip freeze | grep rst2pdf
rst2pdf==0.94`

`pip freeze | grep reportlab
reportlab==3.5.21`

`pip freeze | grep Sphinx`

(Optional) wordaxe version :

Which operating system are you using?
First saw the issue on linux but then managed to replicate it in windows as well.

**Additional information**

**Comment by ranjeethmahankali** [comment]
Is there anyone else out there who managed to find a temporary work around for this ? Because any attempt to use rst2pdf results in the same error.

**Comment by akrabat** [comment]
Can you grab the latest version of `master` as that has the fix (#771)? Alternatively, we tested 0.94 with reportlab 3.5.12, so try pinning to that version of reportlab?

**Comment by ranjeethmahankali** [comment]
Ok, pinning the reportlab version got our pipelines working again.

We install rst2pdf using pip on a docker container (fresh start on each run), so I cannot get the master branch - I am tied to whatever is on pip. The version of reportlab we got is whatever pip installed as a dependency of rst2pdf. Targetting the older version of reportlab like you suggested fixed the problem for now.

Thanks for the temporary work around !

**Comment by akrabat** [comment]
That's great news.

There's a couple of things in master due to the the Python 3 support that I want to check out before I do a 0.95, but hopefully it'll be soon.

**Comment by akrabat** [comment]
@ranjeethmahankali I've released [0.94.1](https://github.com/rst2pdf/rst2pdf/releases/tag/0.94.1) which is 0.94 to fix this.

`pip install rst2pdf` should now work again for you without pinning the reportlab version..

**Comment by ranjeethmahankali** [comment]
> @ranjeethmahankali I've released [0.94.1](https://github.com/rst2pdf/rst2pdf/releases/tag/0.94.1) to fix this.
> 
> `pip install rst2pdf` should now work again for you without pinning the reportlab version..

Thanks for the fix !
