### ISSUE TITLE
Document use of pipx

### ISSUE THREAD

**Issue by akrabat** [rst2pdf/rst2pdf#784]
One issue with python command line tools in general is that non-Pythonistas install everything into the global python and then the tool doesn't necessarily have the same set of dependencies that it was tested with.

For _rst2pdf_, this is a particular issue with ReportLab (and possibly Sphinx, though that's used by developers who maybe know what they are doing?)

One solution looks to be [_pipx_](https://pipxproject.github.io/pipx/) that installs python command line tools into their own isolated venv, so that the dependencies are also isolated and predictable.

It's a Python 3.6+ thing and now that rst2pdf is nearly supported on Python 3, I think we should test pipx and if it works, document it our preferred way to install and run _rst2pdf_.

**Comment by akrabat** [comment]
Mind you, [PEP-582](https://www.python.org/dev/peps/pep-0582/) looks like an simple solution for Python 3.8.

**Comment by akrabat** [comment]
See also: https://shiv.readthedocs.io/en/latest/

**Comment by lornajane** [comment]
I can't see us doing this, python packaging has moved on and I don't hear much about pipx. Closing.
