### ISSUE TITLE
Stylesheet path and example stylesheets

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#79]
```
By now I have a collection of stylesheets that I swap in and out
depending on the kind of document I'm making.  For example, I turn on
fontconfig-serif when I'm rendering a document with Unicode box art,
because my implementation of the Courier font doesn't support those
glyphs.

It's quite tedious to write on the command-line

    rst2pdf -s ~/.rst2pdf/twocolumn.json,$HOME/.rst2pdf/twelvepoint.json,$HOME/.rst2pdf/serif.json

I think it'd be more covenient if I could just type

    rst2pdf -s twocolumn,twelvepoint,serif

and rst2pdf would look in one or more sensible places -- i.e. a
user-configurable stylesheet folder list, similar to the existing font
folder list.

Also, I notice that there are now some example pygments-affecting
stylesheets in the svn repo.  Would you like to include the following
as well?  Then a Debian user could just do "apt-get install rst2pdf"
and then "rst2pdf -s twocolumn" and get two-column output, without
having to understand the JSON format used by rst2pdf stylesheets.

They'd also serve as useful examples for users who wanted to create
their own stylesheets, rather than creating a complete stylesheet with
--print-stylesheet and then just changing one line.

::::::::::::::
double-sided.json
::::::::::::::
{"pageSetup": {"margin-gutter": "2cm"}}
::::::::::::::
twelvepoint.json
::::::::::::::
{"styles": [["base", {"fontSize": 12}]]}
::::::::::::::
twocolumn.json
::::::::::::::
{"pageSetup": {"margin-left": "1cm",
               "margin-right": "1cm",
               "firstTemplate": "twoColumn"}}

::::::::::::::
serif.json
::::::::::::::
{"fontsAlias": {"stdFont": "Times-Roman",
                "stdBold": "Times-Bold",
                "stdItalic": "Times-Italic",
                "stdBoldItalic": "Times-BoldItalic" }}
::::::::::::::
freetype-sans.json
::::::::::::::
{"fontsAlias": {"stdFont": "Sans",
                "stdBold": "Sans-Bold",
                "stdItalic": "Sans-Italic",
                "stdBoldItalic": "Sans-BoldItalic",
                "stdMono": "Monospace",
                "stdMonoItalic": "Monospace-Italic",
                "stdMonoBold": "Monospace-Bold",
                "stdMonoBoldItalic": "Monospace-BoldItalic",
                "stdSerif": "Serif-Roman"},
 "styles": [["base", {"fontSize": 8}]]}
::::::::::::::
freetype-serif.json
::::::::::::::
{"fontsAlias": {"stdFont": "Serif",
                "stdBold": "Serif-Bold",
                "stdItalic": "Serif-Italic",
                "stdBoldItalic": "Serif-BoldItalic",
                "stdMono": "Monospace",
                "stdMonoItalic": "Monospace-Italic",
                "stdMonoBold": "Monospace-Bold",
                "stdMonoBoldItalic": "Monospace-BoldItalic",
                "stdSerif": "Serif-Roman"},
 "styles": [["base", {"fontSize": 8}]]}

```

Original issue reported on code.google.com by `trentb...@gmail.com` on 8 Oct 2008 at 3:04

**Comment by sachin-suresh-rapyuta** [comment]
I am getting confused where to define the actual custom styles and what is its file format (.styles or .json)? 
Here is my current folder structure:

`/home/sachin/Workspace/Sootballs/pa-amr/docs/.rst2pdf/config/rst2pdf.conf`

```
# This is an example config file. Modify and place in ~/.rst2pdf/config

[general]
# A comma-separated list of custom stylesheets. Example:

# A comma-separated list of custom stylesheets. Example:
# stylesheets="fruity.json,a4paper.json,verasans.json"
stylesheets="paamr.json"

# A colon-separated list of folders to search for stylesheets. Example:
# stylesheet_path="~/styles:/usr/share/styles"
# stylesheet_path="~/Workspace/Sootballs/pa-amr/docs/paamr.style"
stylesheet_path="../styles/paamr.style"   //CONFUSED HERE: Is this how to define styles?
```

In `paamr.style` - Defining my custom styles.

```
# List any fonts you would like to embed in the PDF here
  embeddedFonts: []

  # Default page setup.  Can be overridden by including other
  # stylesheets with -s

  pageSetup:
    size: A4
    width: null
    height: null
    margin-top: 2cm
    margin-bottom: 2cm
    margin-left: 2cm
    margin-right: 2cm
    margin-gutter: 0cm
    spacing-header: 5mm
    spacing-footer: 5mm
```

Or Should I define my custom style in `/home/sachin/Workspace/Sootballs/pa-amr/docs/_styles/paamr.json`

```
{
    "fontsAlias": {
      "stdFont": "Times-Roman",
      "stdBold": "Times-Bold",
      "stdItalic": "Times-Italic",
      "stdBoldItalic": "Times-BoldItalic"
    }
  }
```

**Comment by akrabat** [comment]
With version 0.99, the preferred format for style sheet files is yaml.

Stylesheets to use are specified in two places:

1. Using the `-s` parameter to rst2pdf. e.g. `rst2pdf -s paamr`
2. The `stylesheets` option in the config file.

You can specify a comma separated list of stylesheets in both places.

When running rst2pdf, it will then resolve the stylesheet name to a specific file. 

rst2pdf will look in a set list of directories. For each directory in the list, it will then look for a filename which is the stylesheet name with an extension added. ('.yaml', '.yml', '.style' or 'json', in that order).

The directories searched are in this order:

1. The directory specified using `--stylesheet_path`
2. The directory specified in the option `stylesheet_path` in the config file
3. The current directory
4. The directory: `~/.rst2pdf/styles`
5. The styles folder within rst2pdf's installation folder.

i.e. `rst2pdf -s paamr --stylesheet_path=~/my-rst2pdf-styles` with no config file, will (on my computer) search for a valid file in this order:

* `~/my-rst2pdf-styles/paamr.yaml`
* `~/my-rst2pdf-styles/paamr.yml`
* `~/my-rst2pdf-styles/paamr.style`
* `~/my-rst2pdf-styles/paamr.json`
* `./paamr.yaml`
* `./paamr.yml`
* `./paamr.style`
* `./paamr.json`
* `~/.rst2pdf/styles/paamr.yaml`
* `~/.rst2pdf/styles/paamr.yml`
* `~/.rst2pdf/styles/paamr.style`
* `~/.rst2pdf/styles/paamr.json`
* `/opt/homebrew/lib/python3.9/site-packages/rst2pdf/styles/paamr.yaml`
* `/opt/homebrew/lib/python3.9/site-packages/rst2pdf/styles/paamr.yml`
* `/opt/homebrew/lib/python3.9/site-packages/rst2pdf/styles/paamr.style`
* `/opt/homebrew/lib/python3.9/site-packages/rst2pdf/styles/paamr.json`

It will stop searching as soon as it finds the first matching file.

Notes:

* If you specify an extension, rst2pdf won't look for files with the alternative extensions. e.g. if you specify `-s paamr.json`, then it will not look for `paamr.yaml`.
* The `stylesheet_path` option is expect to be a directory, not a filename.

**Comment by sachin-suresh-rapyuta** [comment]
> With version 0.99, the preferred format for style sheet files is yaml.
> 
> Stylesheets to use are specified in two places:
> 
> 1. Using the `-s` parameter to rst2pdf. e.g. `rst2pdf -s paamr`
> 2. The `stylesheets` option in the config file.
> 
> You can specify a comma separated list of stylesheets in both places.
> 
> When running rst2pdf, it will then resolve the stylesheet name to a specific file.
> 
> rst2pdf will look in a set list of directories. For each directory in the list, it will then look for a filename which is the stylesheet name with an extension added. ('.yaml', '.yml', '.style' or 'json', in that order).
> 
> The directories searched are in this order:
> 
> 1. The directory specified using `--stylesheet-path`
> 2. The directory specified in the option `stylesheet_path` in the config file
> 3. The current directory
> 4. The directory: `~/.rst2pdf/styles`
> 5. The styles folder within rst2pdf's installation folder.
> 
> i.e. `rst2pdf -s paamr --stylesheet-path=~/my-rst2pdf-styles` with no config file, will (on my computer) search for a valid file in this order:
> 
> * `~/my-rst2pdf-styles/paamr.yaml`
> * `~/my-rst2pdf-styles/paamr.yml`
> * `~/my-rst2pdf-styles/paamr.style`
> * `~/my-rst2pdf-styles/paamr.json`
> * `./paamr.yaml`
> * `./paamr.yml`
> * `./paamr.style`
> * `./paamr.json`
> * `~/.rst2pdf/styles/paamr.yaml`
> * `~/.rst2pdf/styles/paamr.yml`
> * `~/.rst2pdf/styles/paamr.style`
> * `~/.rst2pdf/styles/paamr.json`
> * `/opt/homebrew/lib/python3.9/site-packages/rst2pdf/styles/paamr.yaml`
> * `/opt/homebrew/lib/python3.9/site-packages/rst2pdf/styles/paamr.yml`
> * `/opt/homebrew/lib/python3.9/site-packages/rst2pdf/styles/paamr.style`
> * `/opt/homebrew/lib/python3.9/site-packages/rst2pdf/styles/paamr.json`
> 
> It will stop searching as soon as it finds the first matching file.
> 
> Notes:
> 
> * If you specify an extension, rst2pdf won't look for files with the alternative extensions. e.g. if you specify `-s paamr.json`, then it will not look for `paamr.yaml`.
> * The `--stylesheet-path` param & `stylesheet_path` config option are expected to be a directory, not a filename.

Thanks for the reply @akrabat , I just edited by reply with few issues and "how-to", as I coudnt find them in the rst2pdf official doc.

**Comment by sachin-suresh-rapyuta** [comment]
@akrabat , please let me know if there was a workaround found for the above "how-to"? I am still struggling to figure how to add a custom logo to my yaml file and remove the blank page after the table of contents.

**Comment by akrabat** [comment]
@sachin-suresh-rapyuta, I'm not a user of Sphinx and use rst2pdf in some rather specific ways, so haven't come across these issues directly. I'll try and write some simple projects soon to see if I can walk through the code and work out what's happening.
