### ISSUE TITLE
Status of python3 support

### ISSUE THREAD

**Issue by sergiopasra** [rst2pdf/rst2pdf#796]
Hello, I'm the maintainer of the rst2pdf package in Fedora. As the end of maintenance of Python2 approaches, Fedora will retire most of the python2 packages in Fedora 32 (Fedora 31 is to be released around November this year).

My question is what is the status of the Python 3 support.  Does the code in github works with python 3.7? Is there a tracker bug for the support?

Also, I offer my help, I know Python

**Comment by akrabat** [comment]
Hi,

The `master` branch works with with Python 3. There's a few bugs that need ironing out: #795, #789 & #785 in particular.

It would be good to get the Python 3 version out in September.

**Comment by lornajane** [comment]
This is great, hi @sergiopasra :) We'd really appreciate more python input and an eye on what else we need to be ready to make this Python 3 release and make sure it is ready to be packaged for use elsewhere. We think we're close!

**Comment by advance512** [comment]
This is what I get with the latest version on pip:
```
$ pip install rst2pdf
Collecting rst2pdf
  Downloading https://files.pythonhosted.org/packages/7a/28/3c7e1d6d68165dc74a5b65ed3d2150caaeabb49952d38f639e97d37d6984/rst2pdf-0.93.tar.gz (1.3MB)
     |████████████████████████████████| 1.3MB 606kB/s 
Requirement already satisfied: setuptools in /home/user/place/.venv/lib/python3.6/site-packages (from rst2pdf) (42.0.2)
Requirement already satisfied: docutils in /home/user/place/.venv/lib/python3.6/site-packages (from rst2pdf) (0.15.2)
Collecting reportlab>=2.4
  Downloading https://files.pythonhosted.org/packages/e4/e9/c38f4537064cd4e28fb9e39edc3611ff6c65aa8871b537e55721ca9f9fda/reportlab-3.5.32-cp36-cp36m-manylinux1_x86_64.whl (2.6MB)
     |████████████████████████████████| 2.6MB 1.7MB/s 
Requirement already satisfied: Pygments in /home/user/place/.venv/lib/python3.6/site-packages (from rst2pdf) (2.0.2)
Collecting pdfrw
  Downloading https://files.pythonhosted.org/packages/c0/84/af442c4458756bb0c0d2424102d1200616f3ff9b82c48aaa130e08549bf6/pdfrw-0.4-py2.py3-none-any.whl (69kB)
     |████████████████████████████████| 71kB 7.4MB/s 
Collecting pillow>=4.0.0
  Downloading https://files.pythonhosted.org/packages/10/5c/0e94e689de2476c4c5e644a3bd223a1c1b9e2bdb7c510191750be74fa786/Pillow-6.2.1-cp36-cp36m-manylinux1_x86_64.whl (2.1MB)
     |████████████████████████████████| 2.1MB 1.7MB/s 
Building wheels for collected packages: rst2pdf
  Building wheel for rst2pdf (setup.py) ... done
  Created wheel for rst2pdf: filename=rst2pdf-0.93.dev0-cp36-none-any.whl size=202047 sha256=d4f868fc4c30bb51f6d52378e7d533d5c7589dc40da6aae611f0b67f3b4a6738
  Stored in directory: /home/alon/.cache/pip/wheels/52/25/f5/4e6685141fa3bc22fca8ba583c585dfc96c6d2df9c726d3bf6
Successfully built rst2pdf
Installing collected packages: pillow, reportlab, pdfrw, rst2pdf
Successfully installed pdfrw-0.4 pillow-6.2.1 reportlab-3.5.32 rst2pdf-0.93.dev0
$ rst2pdf Project801.rst Project801_2.pdf
Traceback (most recent call last):
  File "/home/user/place/.venv/bin/rst2pdf", line 5, in <module>
    from rst2pdf.createpdf import main
  File "/home/user/place/.venv/lib/python3.6/site-packages/rst2pdf/createpdf.py", line 695
    except ValueError, v:
                     ^
SyntaxError: invalid syntax
```

**Comment by stancel** [comment]
This will install the rst2pdf package that works with Python3:

**`pip install git+https://github.com/rst2pdf/rst2pdf.git`**

I had these in my notes as well. Don't remember if I needed to execute these beforehand or was just making a note of them. Thought I would include them here just in case.
`pip install git+https://github.com/glasserc/rst2wp.git`

`pip install argparse`

`pip install python-magic`

`pip install xdg`

**Comment by tbpassin** [comment]
Yes, it works, but that depends on which modules get invoked.  I can build a nice document, but there are still many files that can't be imported or run with Python 3.7+.  My comment at #825 mentions some of the kinds of things that are still lurking.

**Comment by lornajane** [comment]
Just a note to say that the recent 0.97 release should be good to go on Python3

**Comment by gurtner-it** [comment]
Also have a look at this discussion, if you have some errors with python3 and rst2pdf:

https://groups.google.com/forum/#!topic/sphinx-users/TKG9bR8-YJ4

**Comment by akrabat** [comment]
Thanks for replying to that Google groups topic @ralsina !

**Comment by akrabat** [comment]
Python 3 is now supported.

**Comment by sachin-suresh-rapyuta** [comment]
What is the command to generate the PDF after installing the above pip packages?
I am still using `rst2pdf index.rst file.pdf`, but I still get the error: **Unknown directive type "toctree"**
