### ISSUE TITLE
Incorrect versions on Pypi ?

### ISSUE THREAD

**Issue by Lucas-C** [rst2pdf/rst2pdf#799]
Hello

I am struggling to install a version of `rst2pdf` compatible with Python 3.6.

Using the latest version of `pip`, the latest version of `rst2pdf` seems to be `0.93.dev0`:
```
$ pip install -U rst2pdf
...
Successfully installed rst2pdf-0.93.dev0
```

However that is not what appears on Pypi: https://pypi.org/project/rst2pdf/#history

And version `0.93.dev0` is not compatible with Python 3, as it contains Python 2 specific bits of syntax like this one: https://github.com/rst2pdf/rst2pdf/blob/0.93/rst2pdf/createpdf.py#L695

Moreover I cannot explictely install version `0.94` or `0.94.1`:
```
$ pip install -U rst2pdf==0.94.1
Looking in links: file:///home/lucas_cimon/.pip-wheelhouse
Collecting rst2pdf==0.94.1
  ERROR: Could not find a version that satisfies the requirement rst2pdf==0.94.1 (from versions: 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.8.1, 0.9, 0.10.1, 0.11, 0.12, 0.12.1, 0.12.2, 0.13.1, 0.14, 0.14.1, 0.16, 0.90, 0.91, 0.93)
ERROR: No matching distribution found for rst2pdf==0.94.1
```

Could you please help me here ?

**Comment by akrabat** [comment]
Hi,

All the versions in PyPI are Python 2 only. `master` on GitHub should be compatible with Python 3 though.

**Comment by Lucas-C** [comment]
Using `pip install git+https://github.com/rst2pdf/rst2pdf.git` did the trick for me.
As far as I'm concerned, this issue can be closed.
Out of curiosity, why not releasing this Python 3 compatible version on Pypi ?

**Comment by akrabat** [comment]
That's great.

> Out of curiosity, why not releasing this Python 3 compatible version on Pypi ?

Mostly because I would like to get to the bottom of #795, #789 and #785 first.
