### ISSUE TITLE
strange usage of justified text

### ISSUE THREAD

**Issue by williehallock802** [rst2pdf/rst2pdf#803]
If it matters, I am using the current tip of the master branch (25713408) because I needed Python 3 support. 

I have some rst content which looks like:

```
another section:

   ``this is rather long paragraph which needs this kind of markup. the pdf
   converter does not handle this well at least when it spans multiple
   lines inserting some strange spacing.``
```

When using this plug in, it renders the text as being justified. This seems to be a strange choice and a bug. The standard, default html renderer does not do this.

![From Clipboard](https://user-images.githubusercontent.com/55203841/65542416-22883000-dedd-11e9-8919-a4647ce84407.png)

**Comment by EricG-Personal** [comment]
The situation is a bit simpler to replicate using just a fixed-space literal ( `` ). For some reason, rst2pdf chooses to justify the text inside of the literal. I am looking at the code, but have yet to determine exactly where this is happening or why. Was there a reason for this? It doesn't seem like this is something one would want to do for a literal.

**Comment by akrabat** [comment]
At a guess, it's the block quote that's justified.

**Comment by akrabat** [comment]
Checking the default stylesheet, (`rst2pdf --print-stylesheet`),  it's the `bodytext` style defaults to justified and everything else picks up from there.

If you create a style file containing:

```
styles:
    bodytext:
        alignment: TA_LEFT
```

and run with `rst2pdf test.rst -s test.style`, then your literal block quote with literal text is left aligned.

![Screenshot 2019-09-26 at 08 22 19](https://user-images.githubusercontent.com/33135/65667025-c89b7d80-e036-11e9-8b60-4ff1f4fa471e.png)

**Comment by akrabat** [comment]
Closing as answered.
