### ISSUE TITLE
Sphinx builder execution failing in Windows

### ISSUE THREAD

**Issue by haschdl** [rst2pdf/rst2pdf#806]
After installing from `master` and running Sphinx 2.2.0 `make pdf`, an exception is thrown from https://github.com/rst2pdf/rst2pdf/blob/25713408cbe8da5be0f12f1176b11fddd1d95774/rst2pdf/findfonts.py#L225

**Description of problem**
- Install rst2pdf and configure a Sphinx 2.2.0 project
- Run `make pdf`
- Build fails at `findfonts.py` (see above)

🖥 **Versions**
python 3.6.6
Sphinx 2.2.0

Which operating system are you using?
Windows 10

**Additional information**
This prevents all Windows users from using rst2pdf

**Comment by haschdl** [comment]
I will fork and try to simply replace `_winreg` with `winreg` and see if Sphinx build succeeds. I suspect there might be other Windows incompatibilities.

**Comment by akrabat** [comment]
Thanks for the report. As you've guessed I'm not a Windows user, so that platform doesn't get the same level of attention, especially as we haven't worked out how to do Windows CI so that we can run the tests in Windows.

**Comment by akrabat** [comment]
Out of interest, have you just started to use rst2pdf and how did you hear about it?

**Comment by haschdl** [comment]
I’m a big Sphinx fan and rst2pdf is a nice to addition to the documentation toolset. 
I think I just searched for Sphinx PDF. 
Today I needed to generate a subset of the Sphinx documentation in PDF. I used pandoc in the past to generate a 1 page export of a single rst file, but this time I need to generate from a folder.
