### ISSUE TITLE
rst2pdf thinks code block language argument is required, specification says it is optional

### ISSUE THREAD

**Issue by rartino** [rst2pdf/rst2pdf#819]
According to the code element section of the reStructuredText Directives page:

- https://docutils.sourceforge.io/docs/ref/rst/directives.html#code

A code element has one **optional** directive argument, the "formal language".

Yet, rst2html throws an error for a code element without a language element, e.g.:
```
optimade.rst:2305: (ERROR/3) Error in "code" directive:
1 argument(s) required, 0 supplied.
```

Expected output: no error, perhaps a warning.

**Versions**
- Python 2.7.15+
- rst2pdf===0.93.dev-r0
- reportlab==3.4.0
- OS: Ubuntu 18.04.3 LTS

**Comment by akrabat** [comment]
Thank for the report. PR #823 will allow the language to be optional.

**Comment by ralsina** [comment]
Just as an excuse: the code block implementation in rst2pdf predates the
docutils code block directive by like 5 years ;)

**Comment by lornajane** [comment]
rst2pdf is the trailblazer, we know!
