### ISSUE TITLE
Python 3.8 Success

### ISSUE THREAD

**Issue by tbpassin** [rst2pdf/rst2pdf#825]
This is not an issue to report a problem, but to report success. I can see that the Master branch has made a lot of progress since I last installed rst2pdf using pip.  I have found a few small issues and submitted pull requests on them.

Using my cloned code base with these fixes, I have been able to build a pdf document with Python 3.8 using a Sphinx workflow.  The document contains 68 pages, and is not very complicated.  It only has a TOC, a few internal links, some URL links, and some graphics.  Simple or not, though, it builds.  I have been building versions of this document for several years with Python 2.7, so I'm rally happy to get it working with 3.8.   The computer system is Windows 10/Python 3.8/Sphinx 2.2/ ReportLab 3.5.32.

It doesn't look all that great, though, so I will have to learn more about styles.

**Comment by tbpassin** [comment]
I forgot to include one important thing.  To build my document successfully, I also had to fix an issue with a module from jinja2.  The file is *loaders.py*.   I posted a fix for it at jinja issue 767 (https://github.com/pallets/jinja/issues/767).  

There could still be a problem with how template paths are presented to jinja2 (i.e., with the wrong path separators), but at least the module doesn't raise an unhandled exception any more.

**Comment by tbpassin** [comment]
I'm not going to say that the document build I  succeeded with covers all code paths.  There are still plenty of 2/3 issues on the Master branch.  Simple ones I know about are:

    replace *unicode* type with *str*
    replace  *basestring* with *str*
    import some modules using syntax from the absolute_import module from __future__.
    change the import paths for urllib imports

So there's still work ahead.  Also, I'm using Windows, and *autotest* doesn't run on it, so I don't have much test coverage.

**Comment by maphew** [comment]
_Comment to add xref, the PR's are #824  and #826_

**Comment by lornajane** [comment]
I'm not sure we need to keep this issue open but I love this success report :)

Also @tbpassin the tests now run with pytest, in case you want to try that out on Windows too
