### ISSUE TITLE
rst2pdf not working on RHEL 8

### ISSUE THREAD

**Issue by sharuzzaman** [rst2pdf/rst2pdf#827]
Installed rst2pdf in RHEL 8, using most Python packages provided by yum/rpm, but the application is not working

1. execute pip3 install --user rst2pdf
2. application correctly installed
3. execute rst2pdf sample.rst, error message shown

[sahmatra@sahmatra ~]$ rst2pdf sample.rst 
Traceback (most recent call last):
  File "/home/sahmatra/.local/bin/rst2pdf", line 11, in <module>
    load_entry_point('rst2pdf==0.93.dev0', 'console_scripts', 'rst2pdf')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/sahmatra/.local/lib/python3.6/site-packages/rst2pdf/createpdf.py", line 695
    except ValueError, v:
                     ^
SyntaxError: invalid syntax

[sahmatra@sahmatra ~]$ pip3 install --user rst2pdf
Requirement already satisfied: rst2pdf in ./.local/lib/python3.6/site-packages
Requirement already satisfied: setuptools in /usr/lib/python3.6/site-packages (from rst2pdf)
Requirement already satisfied: docutils in /usr/lib/python3.6/site-packages (from rst2pdf)
Requirement already satisfied: reportlab>=2.4 in /usr/lib64/python3.6/site-packages (from rst2pdf)
Requirement already satisfied: Pygments in /usr/lib/python3.6/site-packages (from rst2pdf)
Requirement already satisfied: pdfrw in ./.local/lib/python3.6/site-packages (from rst2pdf)
Requirement already satisfied: pillow>=2.4.0 in /usr/lib64/python3.6/site-packages (from reportlab>=2.4->rst2pdf)
Requirement already satisfied: pip>=1.4.1 in /usr/lib/python3.6/site-packages (from reportlab>=2.4->rst2pdf)

[sahmatra@sahmatra ~]$ which python3
/usr/bin/python3
[sahmatra@sahmatra ~]$ python3 --version
Python 3.6.8

**What is the expected output? What do you see instead?**
The application should be working

🖥 **Versions**

`python -V`

[sahmatra@sahmatra ~]$ python3 -V
Python 3.6.8

`pip freeze | grep rst2pdf`

[sahmatra@sahmatra ~]$ pip3 freeze | grep rst2pdf
rst2pdf==0.93.dev0

`pip freeze | grep reportlab`

[sahmatra@sahmatra ~]$ pip3 freeze | grep reportlab
reportlab==3.4.0

`pip freeze | grep Sphinx`

not installed

(Optional) wordaxe version :

not installed

Which operating system are you using?

Red Hat Enterprise Linux 8

**Additional information**

**Comment by lornajane** [comment]
Thanks for letting us know about this. The current release is for python 2, if you want to use rst2pdf with python 3 then the `master` branch should work... Hopefully instructions in the readme are all you need but let us know if you have questions!

We're on a variety of operating systems but not RHEL as far as I know so it is good to hear about your experiences.

**Comment by akrabat** [comment]
@sharuzzaman I have just released a new version of rst2pdf [0.95](https://pypi.org/project/rst2pdf/0.95/ which supports Python 3.

Please try again with `pip3 install --user rst2pdf` and let us know if `rst2pdf --version` works.

**Comment by sharuzzaman** [comment]
I reinstalled rst2pdf using pip3 install --user rst2pdf and it works well.

Here is the version output:

[sahmatra@sahmatra ~]$ rst2pdf --version
0.95

There is an error message when using Arial font. I will open another ticket for that.

As of now, this issue is resolved.

Thank you.
