### ISSUE TITLE
error message when using Arial font

### ISSUE THREAD

**Issue by sharuzzaman** [rst2pdf/rst2pdf#832]
When using custom stylesheet with Arial font, there is an error message about error processing the font Arial, but the PDF is correctly generated afterwards.

**Description of problem**

rst2pdf -s simple.style sample.rst -vv

[sahmatra@sahmatra ~]$ rst2pdf -s simple.style sample.rst -vv 
[INFO] createpdf.py:1578 Importing extension module 'vectorpdf'
[INFO] languages.py:39 Language 'en_US' not supported by Docutils, using 'en' instead.
[INFO] styles.py:81 Using stylesheets: simple.style
[INFO] styles.py:114 FontPath:['/usr/share/fonts', '.', '/home/sahmatra/.local/lib/python3.6/site-packages/rst2pdf/fonts']
[INFO] styles.py:115 StylePath:['.', '/home/sahmatra/.local/lib/python3.6/site-packages/rst2pdf/styles', '/home/sahmatra/.rst2pdf/styles']
[INFO] findfonts.py:289 Trying to embed Arial
[ERROR] styles.py:314 Error processing font Arial: 'loca'
[ERROR] styles.py:315 Registering Arial as Helvetica alias
[INFO] findfonts.py:289 Trying to embed Arial
[INFO] findfonts.py:330 Registering font: arial from /usr/share/fonts/msttcore/arial.ttf
[INFO] findfonts.py:330 Registering font: arialbd from /usr/share/fonts/msttcore/arialbd.ttf
[INFO] findfonts.py:330 Registering font: ariali from /usr/share/fonts/msttcore/ariali.ttf
[INFO] findfonts.py:330 Registering font: arialbi from /usr/share/fonts/msttcore/arialbi.ttf
[INFO] findfonts.py:343 Embedding via findTTFont as ['arial', 'arialbd', 'ariali', 'arialbi']
[INFO] findfonts.py:289 Trying to embed Arial-Bold
[INFO] findfonts.py:343 Embedding via findTTFont as ['arial', 'arialbd', 'ariali', 'arialbi']
[INFO] languages.py:39 Language 'en_US' not supported by Docutils, using 'en' instead.
[INFO] createpdf.py:639 Starting build
[INFO] createpdf.py:1110 Page 1 [1]

Not using custom stylesheet will default to Helvetica font, and does not show the error message

**What is the expected output? What do you see instead?**
Should not show the error message about Arial font

🖥 **Versions**

`python -V`

[sahmatra@sahmatra ~]$ python3 -V
Python 3.6.8

`pip freeze | grep rst2pdf`

[sahmatra@sahmatra ~]$ pip3 freeze | grep rst2pdf
rst2pdf==0.95

`pip freeze | grep reportlab`

[sahmatra@sahmatra ~]$ pip3 freeze | grep reportlab
reportlab==3.4.0

`pip freeze | grep Sphinx`

not installed

(Optional) wordaxe version :

not installed

Which operating system are you using?

Red Hat Enterprise Linux 8

**Additional information**

Arial font was installed using msttcorefonts. 

[sahmatra@sahmatra ~]$ ls /usr/share/fonts/msttcore/
andalemo.ttf  ariblk.ttf    cambriab.ttf  candara.ttf   consolai.ttf  constan.ttf   corbelz.ttf  fonts.dir     georgiaz.ttf  timesi.ttf    trebuc.ttf    webdings.ttf
arialbd.ttf   calibrib.ttf  cambriai.ttf  candaraz.ttf  consola.ttf   constanz.ttf  courbd.ttf   fonts.scale   impact.ttf    times.ttf     verdanab.ttf
arialbi.ttf   calibrii.ttf  cambriaz.ttf  comicbd.ttf   consolaz.ttf  corbelb.ttf   courbi.ttf   georgiab.ttf  tahoma.ttf    trebucbd.ttf  verdanai.ttf
ariali.ttf    calibri.ttf   candarab.ttf  comic.ttf     constanb.ttf  corbeli.ttf   couri.ttf    georgiai.ttf  timesbd.ttf   trebucbi.ttf  verdana.ttf
arial.ttf     calibriz.ttf  candarai.ttf  consolab.ttf  constani.ttf  corbel.ttf    cour.ttf     georgia.ttf   timesbi.ttf   trebucit.ttf  verdanaz.ttf

[sahmatra@sahmatra ~]$ fc-match arial
arial.ttf: "Arial" "Regular"

[customstylesheet.zip](https://github.com/rst2pdf/rst2pdf/files/4012132/customstylesheet.zip)

**Comment by akrabat** [comment]
Can you test if this happens with rst2pdf version 0.94.1 too?

**Comment by akrabat** [comment]
Also, could you provide instructions on how to install msttcorefonts on a new installation of RHEL?

**Comment by akrabat** [comment]
As a point to note, this error doesn't happen on Ubuntu 18.04:

```
$ fc-match arial
Arial.ttf: "Arial" "Regular"

$ rst2pdf -s simple.style sample.rst -vv
[INFO] createpdf.py:1578 Importing extension module 'vectorpdf'
[INFO] languages.py:39 Language 'en_US' not supported by Docutils, using 'en' instead.
[INFO] styles.py:81 Using stylesheets: simple.style
[INFO] styles.py:114 FontPath:['.', '/home/vagrant/.local/lib/python3.6/site-packages/rst2pdf/fonts']
[INFO] styles.py:115 StylePath:['.', '/home/vagrant/.local/lib/python3.6/site-packages/rst2pdf/styles', '/home/vagrant/.rst2pdf/styles']
[INFO] findfonts.py:289 Trying to embed Arial
[INFO] findfonts.py:330 Registering font: Arial from /usr/share/fonts/truetype/msttcorefonts/Arial.ttf
[INFO] findfonts.py:330 Registering font: Arial_Bold from /usr/share/fonts/truetype/msttcorefonts/Arial_Bold.ttf
[INFO] findfonts.py:330 Registering font: Arial_Italic from /usr/share/fonts/truetype/msttcorefonts/Arial_Italic.ttf
[INFO] findfonts.py:330 Registering font: Arial_Bold_Italic from /usr/share/fonts/truetype/msttcorefonts/Arial_Bold_Italic.ttf
[INFO] findfonts.py:343 Embedding via findTTFont as ['Arial', 'Arial_Bold', 'Arial_Italic', 'Arial_Bold_Italic']
[INFO] findfonts.py:289 Trying to embed Arial-Bold
[INFO] findfonts.py:343 Embedding via findTTFont as ['Arial', 'Arial_Bold', 'Arial_Italic', 'Arial_Bold_Italic']
[INFO] languages.py:39 Language 'en_US' not supported by Docutils, using 'en' instead.
[INFO] createpdf.py:639 Starting build
[INFO] createpdf.py:1110 Page 1 [1]
```

**Comment by akrabat** [comment]
Also works on Fedora 31:

```
$ fc-match arial
arial.ttf: "Arial" "Regular"

$ rst2pdf -s simple.style sample.rst -vv
[ERROR] createpdf.py:1404 [Errno 2] No such file or directory: 'sample.rst'
[vagrant@localhost ~]$
[vagrant@localhost ~]$ cd /vagrant
[vagrant@localhost vagrant]$ rst2pdf -s simple.style sample.rst -vv
[INFO] createpdf.py:1578 Importing extension module 'vectorpdf'
[INFO] languages.py:39 Language 'en_US' not supported by Docutils, using 'en' instead.
[INFO] styles.py:81 Using stylesheets: simple.style
[INFO] styles.py:114 FontPath:['.', '/usr/local/lib/python3.7/site-packages/rst2pdf/fonts']
[INFO] styles.py:115 StylePath:['.', '/usr/local/lib/python3.7/site-packages/rst2pdf/styles', '/home/vagrant/.rst2pdf/styles']
[INFO] findfonts.py:289 Trying to embed Arial
[INFO] findfonts.py:330 Registering font: arial from /usr/share/fonts/msttcore/arial.ttf
[INFO] findfonts.py:330 Registering font: arialbd from /usr/share/fonts/msttcore/arialbd.ttf
[INFO] findfonts.py:330 Registering font: ariali from /usr/share/fonts/msttcore/ariali.ttf
[INFO] findfonts.py:330 Registering font: arialbi from /usr/share/fonts/msttcore/arialbi.ttf
[INFO] findfonts.py:343 Embedding via findTTFont as ['arial', 'arialbd', 'ariali', 'arialbi']
[INFO] findfonts.py:289 Trying to embed Arial-Bold
[INFO] findfonts.py:343 Embedding via findTTFont as ['arial', 'arialbd', 'ariali', 'arialbi']
[INFO] languages.py:39 Language 'en_US' not supported by Docutils, using 'en' instead.
[INFO] createpdf.py:639 Starting build
[INFO] createpdf.py:1110 Page 1 [1]
```

**Comment by lornajane** [comment]
Since we haven't been able to replicate this, I'll close for now but do re-open and let us know if there's more information about this?
