### ISSUE TITLE
rst2pdf/0.95: unable to run tests

### ISSUE THREAD

**Issue by sandrotosi** [rst2pdf/rst2pdf#835]
```
$ PYTHONPATH=. python3 setup.py test
running test
running egg_info
writing rst2pdf.egg-info/PKG-INFO
writing dependency_links to rst2pdf.egg-info/dependency_links.txt
writing entry points to rst2pdf.egg-info/entry_points.txt
writing requirements to rst2pdf.egg-info/requires.txt
writing top-level names to rst2pdf.egg-info/top_level.txt
reading manifest file 'rst2pdf.egg-info/SOURCES.txt'
writing manifest file 'rst2pdf.egg-info/SOURCES.txt'
running build_ext
test_rst2pdf (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_rst2pdf (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_rst2pdf
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'rst2pdf.tests.test_rst2pdf'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
```

how do you run tests?

**Comment by akrabat** [comment]
```
$ pip install nose coverage
$ pip install -r requirements.txt
$ pip install -e .[tests,sphinx,images,svgsupport,aafiguresupport,mathsupport,rawhtmlsupport]
$ nosetests -v -i regulartest -i sphinxtest
```

(from [Running Tests](https://github.com/rst2pdf/rst2pdf/blob/master/doc/DEVELOPERS.rst#running-tests))

**Comment by lornajane** [comment]
We already have an issue open to "make the tests less weird" #739 which I hope will help with issues like this one

**Comment by akrabat** [comment]
We should make  `python3 setup.py test` do something useful - either run nosetests or output instructions on what to do.

**Comment by normanlorrain** [comment]
I'm working on towards a PR that would enable use of pytest.  Not sure it's ready yet, but FYI it's here: 
[(github)](https://github.com/normanlorrain/rst2pdf).  Tested on Python 3.8.1, on Linux (Windows WSL)

It reuses the existing tests (md5, output, etc), and yields a report like: 

> 
> ...
> tests/input/test_stylesheet_includes.txt::tests/input/test_stylesheet_includes.txt PASSED                        [ 95%]
> tests/input/test_svg.txt::tests/input/test_svg.txt FAILED                                                        [ 95%]
> tests/input/test_svg_alignment.txt::tests/input/test_svg_alignment.txt FAILED                                    [ 95%]
> tests/input/test_table_1.txt::tests/input/test_table_1.txt PASSED                                                [ 96%]
> tests/input/test_table_classes.txt::tests/input/test_table_classes.txt PASSED                                    [ 96%]
> 
> ...
> 
> ====== 15 failed, 258 passed, 2 skipped in 119.62s (0:01:59) ================

**Comment by akrabat** [comment]
That's great to hear @normanlorrain.
