### ISSUE TITLE
inkscape_r2p Can Assume The Wrong Location for Inkscape.exe on Windows

### ISSUE THREAD

**Issue by tbpassin** [rst2pdf/rst2pdf#839]
In working on an unrelated issue, I got a failure by inkscape_r2p to run the inkscape.exe executable on Windows.
```
d:\>py38 -m rst2pdf.createpdf -e inkscape D:\Tom\git\rst2pdf\rst2pdf\tests\input\test_inkscape.txt
... part of stack trace elided ...
File "D:\Tom\git\rst2pdf\rst2pdf\extensions\inkscape_r2p.py", line 54, in __init__
    exitcode, out, err = InkscapeImage.run_cmd(cmd)
  File "D:\Tom\git\rst2pdf\rst2pdf\extensions\inkscape_r2p.py", line 107, in run_cmd
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "c:\python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "c:\python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```
It turned out that the extension program had thought that inkscape.exe would be at ```c:\Program Files\Inkscape\inkscape.exe```.  But I had the 32-bit version installed, which is at ```c:\Program Files (x86)\Inkscape\inkscape.exe```.   After I installed the 64-bit version in the standard location, the test succeeded. 

But for some computers, it might be somewhere else, perhaps not even on the C:\ drive.  I would think that the program could do a better job of calculating the path, or at least testing it to see if it's right.  Or there could be a configuration setting to say where the executable is.  Failing that, there should be some documentation that inkscape.exe needs to be in the standard location.  But documentation like that, it's easy for a user to never notice.  So a code solution would be better.

I don't know if any other extensions compute where an executable file is, but if there are, they should be looked at too.

**Comment by tbpassin** [comment]
I see in the code that the path to inkscape.exe is found as follows:
```python
if sys.platform.startswith('win'):
    # note: this is the default "all users" install location,
    # we might want to provide an option for this
    progname = os.path.expandvars(r'$PROGRAMFILES\Inkscape\inkscape.exe')
else:
    progname = 'inkscape'
```
The 32-bit path would be
```python
 os.path.expandvars(r'$ProgramFiles(x86)\Inkscape\inkscape.exe')
```

It would be easy to check each path:
```python
_trial_path = os.path.expandvars(r'$PROGRAMFILES\Inkscape\inkscape.exe')
_really_there = os.path.exists(_trial_path)
if not _really_there:
    _trial_path = os.path.expandvars(r'$ProgramFiles(x86)\Inkscape\inkscape.exe')
    _really_there = os.path.exists(_trial_path)
if _really_there:
    progname = _trial_path
else:
   # Do something else to find it, or bail ...

**Comment by lornajane** [comment]
rst2pdf no longer has support for inkscape, so this issue can't be fixed. Closing.
