### ISSUE TITLE
Support for Markdown

### ISSUE THREAD

**Issue by espetro** [rst2pdf/rst2pdf#845]
Hey there,

Thanks for making this awesome library to get from markup text to pdf! I am willing to use it in a webapp where I write the content in markdown.

Is there a way to reuse a component of the library (e.g. `rst2pdf.html2pdf` ?) to transpile from Markdown to PDF (or Markdown to Rst to PDF) ?

Thanks in advance!

**Comment by ralsina** [comment]
You can use pandoc to go md -> rst and then rst2pdf.

Or you can use pandoc to go md -> pdf but that will produce something that
looks like LaTeX :-)

**Comment by ralsina** [comment]
Or https://pypi.org/project/m2r/

**Comment by phaustin** [comment]
Also worth tracking:

https://github.com/ExecutableBookProject/sphinx-jupyter-book-theme

and the pagedown and bookdown projects from Rstudio:

https://resources.rstudio.com/rstudio-conf-2019/pagedown-creating-beautiful-pdfs-with-r-markdown-and-css

**Comment by lornajane** [comment]
Some great suggestions here! I'll close the issue though as we're unlikely to introduce markdown support anytime soon.
