### ISSUE TITLE
AttributeError: 'PDFWriter' object has no attribute 'custom_cover'

### ISSUE THREAD

**Issue by gurtner-it** [rst2pdf/rst2pdf#860]
Cant' create PDF's anymore, earlier I could but then I guess I messed up my python installation on my mac...

I run this command:
`sphinx-build -D language=de -b pdf /Applications/MAMP/htdocs/sakkadentrainer/doc/ /Applications/MAMP/htdocs/sakkadentrainer_medical_doc/pdf/de/`

`/usr/local/bin/sphinx-build:11: RemovedInSphinx20Warning: `sphinx.main()` has moved to `sphinx.cmd.build.main()`.
  sys.exit(main())
Sphinx v1.8.5 in Verwendung
Lade Übersetzungen [de]…erledigt
Lade pickle Umgebung...erledigt
building [mo]: targets for 0 po files that are out of date
building [pdf]: targets for 23 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
processing Sakkadentrainer_Dokumentation_de_v1.0... 
index 
faq 
medical_product 
registration 
payment 
login 
pw_forgot 
general_training 
car 
train 
dot 
img1 
img3 
statistics 
statistics_details 
settings 
settings_profile 
settings_general 
settings_display 
settings_exercises 
settings_change_pwd 
settings_del 
eyetracking 
resolving references...
done
writing Sakkadentrainer_Dokumentation_de_v1.0... 
[ERROR] pdfbuilder.py:149 'PDFWriter' object has no attribute 'custom_cover'
Traceback (most recent call last):
  File "/Users/beatgurtner/Library/Python/2.7/lib/python/site-packages/rst2pdf/pdfbuilder.py", line 146, in write
    docwriter.write(doctree, destination)
  File "/Library/Python/2.7/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/Users/beatgurtner/Library/Python/2.7/lib/python/site-packages/rst2pdf/pdfbuilder.py", line 595, in translate
    log.error("Can't find cover template %s, using default"%self.custom_cover)
AttributeError: 'PDFWriter' object has no attribute 'custom_cover'
FAILED
build abgeschlossen.
`

**Description of problem**
Don't know the steps to reproduce the problem... (sorry)

I tried reinstalling rst2pdf. This worked without any errors.

I tried reinstalling pdfbuilder:
Could only uninstall it. When I wanted to reinstall it I got this error:

```
pip install pdfbuilder
ERROR: Could not find a version that satisfies the requirement pdfbuilder (from versions: none)
ERROR: No matching distribution found for pdfbuilder
```

🖥 **Versions**

`python -V`
Python 2.7.10

`pip freeze | grep rst2pdf`
rst2pdf==0.96

`pip freeze | grep reportlab`
reportlab==3.5.42

`pip freeze | grep Sphinx`
Sphinx==1.8.5

Which operating system are you using?
MacOS Mojave 10.14.1 (18B75)

**Comment by gurtner-it** [comment]
I think I solved the problem with those steps:

    brew upgrade sphinx-doc
    pip3 install -U sphinx
    pip3 install sphinx-rtd-theme
    pip3 install --user rst2pdf

But now I really am confused, wether now I use python3 or 2 :D

Anyway, my script seems to be running again

**Comment by akrabat** [comment]
Thanks for the update @gurtner-it. I'm glad you solved it.
