### ISSUE TITLE
Prevent pagebreak after heading following a table

### ISSUE THREAD

**Issue by smay4finger** [rst2pdf/rst2pdf#861]
When a table is following a header, a pagebreak is not prevented. 

**What is the expected output? What do you see instead?**
I expect heading and table on the same page. Instead it's on two different pages.

🖥 **Versions**

`python -V`
Python 3.6.9

`pip freeze | grep rst2pdf`
rst2pdf==0.96

`pip freeze | grep reportlab`
reportlab==3.5.42

Which operating system are you using?
Linux Mint 19.3

**Comment by lornajane** [comment]
I'm sorry, rst2pdf doesn't currently have support for widows and orphans on most content types. What you see is the expected behaviour until someone contributes this feature :(

**Comment by smay4finger** [comment]
Ok, thanks for looking into that. UnfortunatelyI'm not being able to contribute that.
