### ISSUE TITLE
Explain how to mark new known good md5s in tests

### ISSUE THREAD

**Issue by lornajane** [rst2pdf/rst2pdf#865]
We updated the instructions for running the tests but not for marking the md5 hashes as good or not, so the instructions for working with the tests are not complete enough for a new contributor at this point.

Solution: extend the `doc/DEVELOPERS.rst` file to include updated instructions (look at older versions of the file, we moved from autotest to pytest and these instructions got lost along the way)

**Comment by stephenfin** [comment]
I think this can be closed now, since we're no longer using the checksum-based machinery? (:raised_hands:)

**Comment by akrabat** [comment]
> I think this can be closed now, since we're no longer using the checksum-based machinery? (🙌)

Agreed.

Also https://github.com/rst2pdf/rst2pdf/pull/872 adds better info to `docs/DEVELOPERS.rst` on how to test.
