### ISSUE TITLE
rst2pdf 0.97  in PyPI doesn't include LICENSE.txt

### ISSUE THREAD

**Issue by sergiopasra** [rst2pdf/rst2pdf#866]
Hi, the tarball in PYPI doesn't include the file LICENSE.txt, The inclusion of the license file is required by the text of the license itself

```
The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.
```

**Comment by sergiopasra** [comment]
You could also include README.rst and other relevant files in the tarball.

**Comment by stephenfin** [comment]
FYI, we can fix this by configuring `[metadata] license_file` in `setup.cfg` ([source](https://github.com/pypa/setuptools/pull/1536))

**Comment by akrabat** [comment]
> FYI, we can fix this by configuring `[metadata] license_file` in `setup.cfg` ([source](https://github.com/pypa/setuptools/pull/1536))

This doesn't pick up `CHANGES` though, so I added to `MANIFEST.in` which seems to.

There's definitely a situation here where there's many ways to do the same thing and *it's really confusing*!

**Comment by stephenfin** [comment]
Unfortunately packaging has long been a weakness of Python, alongside things like performance. Setuptools and the general work of the [PyPA](https://www.pypa.io/en/latest/) has improved things massively but there have been a trail of failed experiments and modified best practices left in its wake. Hopefully we'll all eventually settle on a "best approach" (I for one welcome our new [poetry](https://python-poetry.org) overlords) but I wouldn't count on it.
