### ISSUE TITLE
'inkscape' called with invalid argument

### ISSUE THREAD

**Issue by stephenfin** [rst2pdf/rst2pdf#869]
We have [conditionals](https://github.com/rst2pdf/rst2pdf/blob/1ba08758e0c8d3bf78868c313bf21d1132fdb73c/rst2pdf/extensions/inkscape_r2p.py#L62-L64) to handle differences in arguments between Inkscape 1.x and previous versions. Those conditionals state that Inkscape 1.x uses an `--export-file` parameter. However, this is not a valid parameter on the Inkscape 1.0 package on Fedora 31 and looking at the release notes [prove](https://wiki.inkscape.org/wiki/index.php/Release_notes/1.0#Command_Line) that the correct incantation to be `--export-filename`. This [seems to have been a late-breaking change](https://gitlab.com/inkscape/inkscape/-/commit/57793737d53b4187c2474f25f1f6be7a6f118533) that I suspect wasn't present in any of the release candidates, hence why we didn't spot it before.

```
$ inkscape --version
Inkscape 1.0 (4035a4fb49, 2020-05-01)
    Pango version: 1.44
$ sudo dnf info inkscape
Installed Packages
Name         : inkscape
Version      : 1.0
Release      : 2.fc31
Architecture : x86_64
Size         : 188 M
Source       : inkscape-1.0-2.fc31.src.rpm
Repository   : @System
From repo    : updates
Summary      : Vector-based drawing program using SVG
URL          : https://inkscape.org/
License      : GPLv2+ and CC-BY
Description  : Inkscape is a vector graphics editor, with capabilities similar to
             : Illustrator, CorelDraw, or Xara X, using the W3C standard Scalable Vector
             : Graphics (SVG) file format.  It is therefore a very useful tool for web
             : designers and as an interchange format for desktop publishing.
             : 
             : Inkscape supports many advanced SVG features (markers, clones, alpha
             : blending, etc.) and great care is taken in designing a streamlined
             : interface. It is very easy to edit nodes, perform complex path operations,
             : trace bitmaps and much more.
```

**Comment by akrabat** [comment]
Ooh! Good catch. I'm still on a pre-release of 1.0 from January…
