### ISSUE TITLE
Review default style sheet

### ISSUE THREAD

**Issue by akrabat** [rst2pdf/rst2pdf#884]
We should review the default style sheet and maybe improve it.

The current one needs to be available so that people who have based their styles off of it can just add `-s {old name}.style` in order to continue getting what they expect. (We'll obviously need com up with a name for the old default style - preferably one that lends itself to becoming a series.

We should keep the current default styles as `legacy` so that people can build their current docs.

**Comment by lornajane** [comment]
The current default stylesheet produces `document1.pdf` attached and I have also included `document`1-pandoc.pdf` to show the default pandoc output (pretty sure this is not what we are aiming for though!).

(Created from the `document1.rst` source file in the website project)
[document1.pdf](https://github.com/rst2pdf/rst2pdf/files/5792661/document1.pdf)
[document1-pandoc.pdf](https://github.com/rst2pdf/rst2pdf/files/5792663/document1-pandoc.pdf)

**Comment by nfraprado** [comment]
Nice comparison.

I can see that rst2pdf's page is slightly skinnier than pandoc's. Pandoc's looks more like an A4 which should be the default for rst2pdf IMO.

Another thing is that the document title should probably have more space after it, like pandoc.

The big margins and serif fonts in pandoc's document gives it a LaTeX/Scientific Paper feel, which I wouldn't think would be a good default for rst2pdf, though it would be nice to include that as a built-in style.

**Comment by lornajane** [comment]
I started looking at some options, the default is A4 but the margins make it seem completely different! There are also really really limited choices on fonts, so how about the attached?
[document1.pdf](https://github.com/rst2pdf/rst2pdf/files/5845601/document1.pdf)

**Comment by nfraprado** [comment]
That's a great start, although I'm not fond of the gray colored titles, as they seem too washed out.

I think we should really test this using a more complete sample document, with multiple pages, sections, and at least the most used rst constructs. There's only so much we can check in a simple document like that one.

**Comment by habamax** [comment]
You could also check asciidoctor-pdf defaults for inspiration.

## Without title page 

```
= PDF Documents: From your Text Editor

First para is Abstract and has a bigger font by default.

Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Maecenas feugiat fermentum pretium. Cras eu dolor imperdiet justo mattis
pulvinar. Cras nec lectus ligula. Proin elementum luctus elit, a tincidunt quam
facilisis non. Nunc quis mauris non turpis finibus luctus. Maecenas ante
sapien, sagittis quis accumsan in, feugiat quis sem. Praesent et auctor libero.


== Further Sections, Headings, etc

Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Maecenas feugiat fermentum pretium. Cras eu dolor imperdiet justo mattis
pulvinar. Cras nec lectus ligula. Proin elementum luctus elit, a tincidunt quam
facilisis non. Nunc quis mauris non turpis finibus luctus. Maecenas ante
sapien, sagittis quis accumsan in, feugiat quis sem. Praesent et auctor libero.

```

[adoc-pdf-no-title.pdf](https://github.com/rst2pdf/rst2pdf/files/5980296/adoc-pdf-no-title.pdf)


## With title page

```
= PDF Documents: From your Text Editor
Maxim Kim
v0.1, 2021-02-15 : Draft
:doctype: book

First para is Abstract and has a bigger font by default.

Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Maecenas feugiat fermentum pretium. Cras eu dolor imperdiet justo mattis
pulvinar. Cras nec lectus ligula. Proin elementum luctus elit, a tincidunt quam
facilisis non. Nunc quis mauris non turpis finibus luctus. Maecenas ante
sapien, sagittis quis accumsan in, feugiat quis sem. Praesent et auctor libero.


== Further Sections, Headings, etc

Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Maecenas feugiat fermentum pretium. Cras eu dolor imperdiet justo mattis
pulvinar. Cras nec lectus ligula. Proin elementum luctus elit, a tincidunt quam
facilisis non. Nunc quis mauris non turpis finibus luctus. Maecenas ante
sapien, sagittis quis accumsan in, feugiat quis sem. Praesent et auctor libero.
```

[adoc-pdf-title.pdf](https://github.com/rst2pdf/rst2pdf/files/5980312/adoc-pdf-title.pdf)

**Comment by lornajane** [comment]
More complex document ... how about the manual (it's missing it's coverpage but this is the rst2pdf without any extras)?
[manual.pdf](https://github.com/rst2pdf/rst2pdf/files/5998309/manual.pdf)

**Comment by lornajane** [comment]
Just to keep everyone in the loop
[Uploading manual.pdf…]()
, here's the updated manual. I'm finishing up the related changes for this PR so this is a good time to decide if there's more to change!

**Comment by lornajane** [comment]
Update again: #988  has been merged, so I'll close this. Take the master branch for a test drive if you'd like to see what we eventually went with.
