### ISSUE TITLE
Website references incorrect python version

### ISSUE THREAD

**Issue by GadgetSteve** [rst2pdf/rst2pdf#892]
**Description of problem**
The web site states on the opening page:
## Install rst2pdf
rst2pdf requires Python 2 (upgrade to Python 3 is a work in progress).

However the repository states in readme.rst:
## Installation
rst2pdf supports Python 3.6 or greater. Version 0.97 was the last version to support Python 2.7.

Read the first few lines of https://rst2pdf.org/

Edit or regenerate the github pages.

**What is the expected output? What do you see instead?**
N/A

🖥 **Versions**

`python -V`

`pip freeze | grep rst2pdf`

`pip freeze | grep reportlab`

`pip freeze | grep Sphinx`

(Optional) wordaxe version :

Which operating system are you using?

**Additional information**

**Comment by akrabat** [comment]
Thanks @GadgetSteve, I've raised a [PR](https://github.com/rst2pdf/rst2pdf.github.io/pull/19) to fix it.

**Comment by lornajane** [comment]
The linked PR is merged now, so I'll close. Thanks for the report and the fix!
