### ISSUE TITLE
Custom Cover Page Creation, Useage, and Settings

### ISSUE THREAD

**Issue by jasonnovich** [rst2pdf/rst2pdf#893]
I would like my PDF output to use a custom cover page of my own design.

**Description of problem**

No steps to recreate the issue.
I would like to better understand how to use the custom cover page options in the --custom-cover switch and what needs to be in the *.tmpl file. The cusom cover page needs a logo and other information that changes each time the document goes through a release cycle.

I haven't since I am not sure if this is possible.

**What is the expected output? What do you see instead?**
A custom cover page of my own design. What is output in the PDF is a standard cover page.

🖥 **Versions**

`python -V`
Python 3.8.2
`pip freeze | grep rst2pdf`

`pip freeze | grep reportlab`

`pip freeze | grep Sphinx`

(Optional) wordaxe version :

Which operating system are you using?
Windows 10

**Additional information**

**Comment by lornajane** [comment]
The custom covers are a little bit of a limited feature but I think you can adapt this to do what you need.

If you create the `cover.tmpl` file in the same directory as the `rst` source, it will automatically be included. If you call it `something-else.tmpl` then you can add it by doing something like `rst2pdf --custom-cover=something-else.tmpl input.rst`.

The template file should contain the rst source that you would like to have on that page. It can also use the main title of your document as `{{title}}` for the coverpage.

I'm not exactly sure on the other details but if you can have a try and let us know how you get on, and what specific questions you have, I think it would be good to know what worked for you (or not!) and update the docs with that info.

**Comment by NicolasBln16** [comment]
Hello! 
I would like to know if it's possible to add an image to the cover page template. I have modified the cover by adding the text that I want but I would like to know how to add a png file to the template in order to custom my pdf cover page.

**Comment by akrabat** [comment]
Hey @NicolasBln16,

Yes, you can certainly use an image on the cover page as our manual does exactly this. 

See [cover.tmpl](https://github.com/rst2pdf/rst2pdf/blob/master/doc/assets/cover.tmpl#L3-L4).

**Comment by NicolasBln16** [comment]
Thank you for your answer. Do you need to modify the pdfbuilder.py file of rst2pdf in order for it to work?

**Comment by lornajane** [comment]
You shouldn't need to modify anything since the feature is present (at least for the manual). I think you have what you need here so I'll close but don't hesitate to come back to us if you have any more questions on this!
