### ISSUE TITLE
pdfrw is unmaintained

### ISSUE THREAD

**Issue by nbourdau** [rst2pdf/rst2pdf#895]
**Description of problem**

It seems that pdfrw is not maintained: https://github.com/pmaupin/pdfrw/issues/191 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=958362. Hence Debian has started to remove it from its repo for the upcoming release. 
The problem is that it means to remove rst2pdf as well and this I would hope it won't happen.

**possible solution?**

The use of pdfrw seems not very wide spread in the rst2pdf codebase. I am not expert of rst2pdf source code but it looks used only here: rst2pdf/extensions/vectorpdf_r2p.py

Do you think the use of pdfrw could be replaced by something else, be it by reimplementing the feature used, importing the needed code, or replace for a maintained dependency?

**Comment by lornajane** [comment]
Thanks so much for posting this here! I am not sure how to make sure this project gets notified when things happen in the distro projects, but this was very helpful. We'll try to figure out what we can do and keep updating this issue with information.

**Comment by akrabat** [comment]
I will remove the pdfrw dependency and hence the inkscape, plantuml and vectorpdf extensions and then we can release a 0.98.

**Comment by pmaupin** [comment]
Sorry, I've been very busy, but if anybody else would like to step up to
maintain pdfrw, I can certainly advise.

Thanks,
Pat

**Comment by pmaupin** [comment]
BTW, pdfrw works fine on Python 3 < 3.8, so it should not be the same sort
of nightmare as moving rst2pdf to Python 3.

**Comment by akrabat** [comment]
[Version 0.98](https://pypi.org/project/rst2pdf/0.98/) is now released.

**Comment by akrabat** [comment]
To complete the circle, Debian have now [packaged 0.98](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962651#24)

**Comment by nbourdau** [comment]
Thanks everyone! :-)
