### ISSUE TITLE
Test pass even when PDF's are different

### ISSUE THREAD

**Issue by akrabat** [rst2pdf/rst2pdf#910]
The tests can pass even if the PDFs are different.

I've been looking at `pytest input/sphinx-issue183`. On the cover page, the date is `April 29, 2018`, which is hard coded via the `today` setting in `input/sphinx-issue183/conf.py`.

If I set `today` to a variety of different dates, sometimes the test passes even though the date on the cover page is not the correct date.

Tests:

* `today = 'August 28, 2020'` => Test Passes
* `today = 'May 28, 2020'` => Test Passes
* `today = 'January 15, 1488'` => Test Passes
* `today = 'September 28, 2020'` => Test Fails

**Comment by lornajane** [comment]
I don't have a `today` setting in my `conf.py` for this test, I think the date is always the current date when I run the tests

**Comment by akrabat** [comment]
> I don't have a `today` setting in my `conf.py` for this test, I think the date is always the current date when I run the tests

That's correct. There was a `today` in the `conf.py` until we merged #855 which removed it by accident. That PR passed the tests though, so no-one spotted it.

PR #909 restores the `today` setting to the affected tests, but we really need the tests to fail reliably when something like this happens.
