### ISSUE TITLE
Version 0.98 does not compile documents using pdf figures

### ISSUE THREAD

**Issue by nathanjsmith** [rst2pdf/rst2pdf#914]
Version 0.97 and earlier allowed inclusion of pdf files as images in figures. 0.98 produces an error stating that the image is broken or in an unknown format.

**Description of problem**

Create a trivial rst file with a figure that points to a pdf file:

```
Lorem ipsum dolor

.. figure: test.pdf

   Figure :counter:`figure`. Test figure
```

Run it through rst2pdf 0.98. It will print an error "[ERROR] image.py:285 The image (c:\users\name/test.pdf, near line UNKNOWN in file UNKNOWN) is broken or in an unknown format"

Downgrade to rst2pdf 0.97 and the file will compile correctly. Looking at the 0.98 changelog, I suspect this has to do with removing pdfrw support.

**What is the expected output? What do you see instead?**

See above. All documentation using pdf figures is broken.

🖥 **Versions**

`python -V`
Python 3.8.3

`pip freeze | grep rst2pdf`
0.98

`pip freeze | grep reportlab`
3.5.49

Which operating system are you using?

Windows 10

**Additional information**

We considered switching to svg for these images, but the svg support did not correctly render many of our images. Also, the conversion required that we import the pdf images into Inkscape and then export them to svg, which was tedious. We very much prefer to have images in pdf so that they can be stored in vector format.

**Comment by lornajane** [comment]
Thanks for the issue, this is all useful information. Sadly the PDF functionality relied on a library called pdfrw which is itself no longer maintained. We would definitely be open to having PDF support added back into the library if someone knows another library that they could use though, it does seem a shame to lose the feature!

**Comment by nathanjsmith** [comment]
I don't know what the requirements are, but in reading about pdfrw, I found an article (https://www.binpress.com/manipulate-pdf-python/) comparing it to pdfminer, which is actively maintained in the https://github.com/pdfminer/pdfminer.six project. Perhaps that project is a possible replacement for pdfrw.

**Comment by lornajane** [comment]
Thanks for sharing the resources, we'd be happy to have an alternative tool in the project to re-add the PDF support but it's not a priority at this time I'm afraid. So I'll close, but if you need it, add it and we'll do our best to get it in!

**Comment by micw** [comment]
Hello,
I hit this issue today. Even if that's not on the priority list, would you please leave the issue open until it's resolved?

Thank you,
Michael.

**Comment by lornajane** [comment]
Ah, perhaps I was too polite there. We won't be fixing this issue ourselves, but patches would be welcome.
