### ISSUE TITLE
except code path never reached in createpdf.py:add_extensions

### ISSUE THREAD

**Issue by dkriegner** [rst2pdf/rst2pdf#920]
If I read the code [here](https://github.com/rst2pdf/rst2pdf/blob/228411388f481ea32888b9a958f800f2be2450df/rst2pdf/createpdf.py#L1815) correctly the expcept code is never executed since all ImportError are caught inside the try statement. 

This is somehow unfortunate since the resulting error message in case one attempts to load non-existing extensions is not very relevant 
```
[ERROR] pdfbuilder.py:149 local variable 'module' referenced before assignment
Traceback (most recent call last):
  File "/home/dk/.local/lib/python3.7/site-packages/rst2pdf/pdfbuilder.py", line 107, in write
    createpdf.add_extensions(dummy())
  File "/home/dk/.local/lib/python3.7/site-packages/rst2pdf/createpdf.py", line 1595, in add_extensions
    if hasattr(module, 'install'):
UnboundLocalError: local variable 'module' referenced before assignment
```

I stumbled across this due to the recent removal of pdfrw/vectorpdf. sorry for not providing example code showing the issue, but i hope if you look into your code its clear what I mean.

**Comment by lornajane** [comment]
Thanks for letting us know. I'm not sure we've got enough information here to improve the situation but a test case or even a pull request with a fix would be really welcome.

**Comment by dkriegner** [comment]
Sorry, I am not sure what you mean by not having enough information? 
If you read the code starting [here:](https://github.com/rst2pdf/rst2pdf/blob/228411388f481ea32888b9a958f800f2be2450df/rst2pdf/createpdf.py#L1809)

        _names = [firstname, modname]
        try:
            for _name in _names:
                try:
                    module = import_module(_name, 'rst2pdf')
                except ImportError:
                    continue
        except ImportError as e:
            if str(e).split()[-1].replace("'", '') not in [firstname, modname]:
                raise
            raise SystemExit(
                '\nError: Could not find module %s '
                'in sys.path [\n    %s\n]\nExiting...\n'
                % (modname, ',\n    '.join(sys.path))
            )

You will immediately see that the outer except statement which would cause a clean exit with appropriate error message can never be reached because all `ImportError` are caught by the inner try/except. 

The problem seems was introduced in this [commit](https://github.com/rst2pdf/rst2pdf/commit/c3a7c5c2184f853fcbb61e20829b5c0f9d276c39) by @tbpassin 

Likely it should read (similar to the code structure before the mentioned commit):

        try:
            try:
                module = import_module(firstname, 'rst2pdf')
            except ImportError:
                import_module(modname, 'rst2pdf')
        except ImportError as e:
            if str(e).split()[-1].replace("'", '') not in [firstname, modname]:
                raise
            raise SystemExit(
                '\nError: Could not find module %s '
                'in sys.path [\n    %s\n]\nExiting...\n'
                % (modname, ',\n    '.join(sys.path))
            )

**Comment by stephenfin** [comment]
Yeah, this is definitely valid.
