### ISSUE TITLE
Remove the test_artifacts repo from this org

### ISSUE THREAD

**Issue by lornajane** [rst2pdf/rst2pdf#922]
There is a repo called "test artifacts" but we're not maintaining it since our sample output is in the main rst2pdf now. I will remove it unless anyone thinks that would be a terrible idea.

**Comment by stephenfin** [comment]
![image](https://user-images.githubusercontent.com/1690835/94239715-1d076080-ff0a-11ea-8fe6-135ca4242d8c.png)

**Comment by akrabat** [comment]
I think it can go now. In the past, the reference PDFs were not in this repo, just the md5 checksums, but now we have the references here which is more useful and easier to maintain.

**Comment by lornajane** [comment]
The deed is done!
