### ISSUE TITLE
Rename test files to `.rst` 

### ISSUE THREAD

**Issue by akrabat** [rst2pdf/rst2pdf#923]
Why do all our input test rst files have `.txt` extensions? `.rst` would make it easier for editors to syntax highlight them…

**Comment by stephenfin** [comment]
This is a [docutils recommendation](https://docutils.sourceforge.io/FAQ.html#what-s-the-standard-filename-extension-for-a-restructuredtext-file) that I happen to disagree with. I agree that changing things would make sense.

**Comment by akrabat** [comment]
> This is a [docutils recommendation](https://docutils.sourceforge.io/FAQ.html#what-s-the-standard-filename-extension-for-a-restructuredtext-file) that I happen to disagree with. I agree that changing things would make sense.

Good grief!
