### ISSUE TITLE
Test test_uml_extension fails when plantuml isn't installed

### ISSUE THREAD

**Issue by nfraprado** [rst2pdf/rst2pdf#935]
The `test_uml_extension` test fails when the plantuml binary isn't installed. Since it is not a python package it can't be setup as part of the virtual environment as the other optional dependencies can.

Although it would be nice to test the uml functionality of rst2pdf, it seems bad to have the tests fail because the user didn't have plantuml installed, which is only optional.

What would be the best course of action? Should I delete the test? Or could we conditionally disable the test if it is not installed, perhaps issuing a warning?

**Comment by stephenfin** [comment]
You could check if the executable is present and skip the test if not?

**Comment by nfraprado** [comment]
Thank you for the feedback. I wasn't sure if it would be okay to keep skipping tests (even if it is only when the user doesn't have the program installed), but I too think it is the best alternative.

I went ahead and implemented that in #936.
