### ISSUE TITLE
feature request: table of contents

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [rst2pdf/rst2pdf#938]
I love rst2pdf.  So much easier to use than Sphinx.  But, rst2pdf doesn't seem to have the ability to create a table of contents.  I don't know how hard it would be to add this, but it would be very useful, especially for large documents.

**Comment by stephenfin** [comment]
Can you not use the `.. contents` directive for just this?

**Comment by Phillip-M-Feldman** [comment]
I've gone through the manual at https://rst2pdf.org/static/manual.html but
did not find any mention of this directive.

**Comment by akrabat** [comment]
[`.. contents`](https://docutils.sourceforge.io/docs/ref/rst/directives.html#table-of-contents) is part of reStructured Text and not specific to rst2pdf.

**Comment by lornajane** [comment]
Great news that it's an rst2pdf feature - but if @Phillip-M-Feldman couldn't find it then that's at least a docs gap on our side. I'd like to keep this issue open for now and maybe add an example of a document with a table of contents to https://rst2pdf.org (the repo [rst2pdf.github.io](https://github.com/rst2pdf/rst2pdf.github.io) - we have some in our test suite I think that might work as a starter example.

**Comment by Phillip-M-Feldman** [comment]
I tweaked the basic sample input file--attached--to make it generate a
table of contents, and the result is exactly what I was hoping for.  Thanks!

**Comment by nfraprado** [comment]
Maybe this issue can be closed since @lornajane already added the rst references in the manual and an example to the site?

**Comment by Phillip-M-Feldman** [comment]
Agreed!
