### ISSUE TITLE
Show output progress or partial output to fix "Likely that a flowable is too large for any frame"

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [rst2pdf/rst2pdf#944]
Under fairly random conditions, I'm getting the following error, in which case no .pdf file is generated:

reportlab.platypus.doctemplate.LayoutError: More than 10 pages generated without content - halting layout.  Likely that a flowable is too large for any frame.

I have been unable to reduce this to a simple demonstration case.  Does anyone know why this happens or how to prevent it?

**Comment by lornajane** [comment]
I've seen this happen when an image is larger than a page, so it moves to the next one... But it won't fit there either so it moves to... You get the idea. Try removing or shrinking images, it can probably apply to other elements as well. Hopefully that helps! If you do manage to find a replication case I'd still like to see it, maybe we can improve the error message or try to indicate which thing isn't flowing

**Comment by Phillip-M-Feldman** [comment]
Would it be possible to modify the code to make it write as much of the
output pdf file as possible?  This would at least give an indication of
where things are going wrong.

**Comment by Phillip-M-Feldman** [comment]
I eventually discovered that the problem was caused by a large verbatim block.  I was able to work around the problem by dividing the block into two pieces.  Are verbatim blocks not allowed to be split across pages?  I don't recall seeing any mention of this in the documentation.

**Comment by Phillip-M-Feldman** [comment]
The best process that I've devised for debugging things is bisection search; needless to say, this is slow and cumbersome.  It would be great if rst2pdf provided some indication of where things are going off the rails.

**Comment by akrabat** [comment]
> The best process that I've devised for debugging things is bisection search; needless to say, this is slow and cumbersome. It would be great if rst2pdf provided some indication of where things are going off the rails.

Agreed!  I've sometimes found that `-v` helps, but in general, more diagnostics would be very helpful.

**Comment by Phillip-M-Feldman** [comment]
Is there any way to get partial output, i.e., everything up to the point where the processing failed?

**Comment by lornajane** [comment]
Can we get an example of the block that caused the problem here? And yes, let's also try to get some other debugging available. I discovered we have a `--very-verbose` switch but it's ... yeah, verbose! And I'm absolutely guessing but it looks like it outputs as it reads the PDF and creates the structure of the document, rather than as it tries to fit the pieces onto the pages, so I'm not at all sure it would have helped debug this problem.

**Comment by Phillip-M-Feldman** [comment]
I made a minor change to the document and the problem has now vanished.  If
it recurs, I will submit a sample file.  Thanks!

**Comment by lornajane** [comment]
First step for this I think would be to try to get a replication case next time we see the error. I tried, but I couldn't cause this so perhaps it wasn't my image that caused it.

**Comment by akrabat** [comment]
There isn't much progress information provided by ReportLab when building the PDF. However, PR #1025 hooks into the "onProgress" hook that is available in order output a little more information.

In this example, the output with the `--very-verbose` flag would now contain:

```
INFO] createpdf.py:665 Starting build
[DEBUG] createpdf.py:739 Number of flowables: 6
[DEBUG] createpdf.py:747 Page 1: Flowable 1 <class 'reportlab.platypus.paragraph.Paragraph'>
[DEBUG] createpdf.py:747 Page 1: Flowable 2 <class 'reportlab.platypus.paragraph.Paragraph'>
[DEBUG] createpdf.py:747 Page 1: Flowable 3 <class 'rst2pdf.flowables.MySpacer'>
[DEBUG] createpdf.py:747 Page 1: Flowable 4 <class 'rst2pdf.flowables.DelayedTable'>
[WARNING] image.py:423 Image /Users/rob/Projects/python/rst2pdf/rst2pdf/tests/input/images/background.jpg is too wide for the frame, rescaling
[INFO] createpdf.py:1193 Page 1 [1]
[DEBUG] createpdf.py:747 Page 1: Flowable 4 <class 'rst2pdf.flowables.DelayedTable'>
[INFO] createpdf.py:1193 Page 2 [2]
[DEBUG] createpdf.py:747 Page 2: Flowable 4 <class 'rst2pdf.flowables.DelayedTable'>
[INFO] createpdf.py:1193 Page 3 [3]
[DEBUG] createpdf.py:747 Page 3: Flowable 4 <class 'rst2pdf.flowables.DelayedTable'>
[INFO] createpdf.py:1193 Page 4 [4]
[DEBUG] createpdf.py:747 Page 4: Flowable 4 <class 'rst2pdf.flowables.DelayedTable'>
[INFO] createpdf.py:1193 Page 5 [5]
[DEBUG] createpdf.py:747 Page 5: Flowable 4 <class 'rst2pdf.flowables.DelayedTable'>
[INFO] createpdf.py:1193 Page 6 [6]
[DEBUG] createpdf.py:747 Page 6: Flowable 4 <class 'rst2pdf.flowables.DelayedTable'>
[INFO] createpdf.py:1193 Page 7 [7]
[DEBUG] createpdf.py:747 Page 7: Flowable 4 <class 'rst2pdf.flowables.DelayedTable'>
[INFO] createpdf.py:1193 Page 8 [8]
[DEBUG] createpdf.py:747 Page 8: Flowable 4 <class 'rst2pdf.flowables.DelayedTable'>
[INFO] createpdf.py:1193 Page 9 [9]
[DEBUG] createpdf.py:747 Page 9: Flowable 4 <class 'rst2pdf.flowables.DelayedTable'>
[INFO] createpdf.py:1193 Page 10 [10]
[DEBUG] createpdf.py:747 Page 10: Flowable 4 <class 'rst2pdf.flowables.DelayedTable'>
Traceback (most recent call last):
  File "/Users/rob/.pyenv/versions/rst2pdf-395/bin/rst2pdf", line 33, in <module>
    sys.exit(load_entry_point('rst2pdf', 'console_scripts', 'rst2pdf')())
```

So we can see we're looking for a "DelayedTable" after the first two paragraphs of text. Of course, unfortunately, you still need to know the underlying structure of the doctree that rst2pdf has built and that a figure is a DelayedTable surrounded by two MySpacers.

Hopefully better than what we currently have though!
