### ISSUE TITLE
negative line spacing

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [rst2pdf/rst2pdf#945]
I'm sometimes getting output with negative line spacing, which causes some text to fall on top of other text.  Here's some sample output that shows the problem:

![image](https://user-images.githubusercontent.com/1065412/97796341-fc4bbe00-1bcd-11eb-885d-cc4a69f70470.png)

I have not been able to create a small input file that demonstrates this issue.

**Comment by akrabat** [comment]
As a workaround you may find that adding a comment helps it to flow correctly.

```rst

The constructor method accepts several arguments, not counting *self:*

.. a comment

Method __init__
---------------

```

**Comment by lornajane** [comment]
Closing this as I'm not sure there's more for us to do at this point, but if you have a replication case for us then I'd be happy to see it and re-open
