### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by lornajane** [rst2pdf/rst2pdf#948]
**Description of problem**

There are changes to Travis, we will need to update the project to take account of these.

**Comment by lornajane** [comment]
Migration process to stay with Travis and move to .com https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by akrabat** [comment]
We've migrated to GitHub Actions with PR #951, so this is no longer needed.
