### ISSUE TITLE
latest pip (20.3) cannot install latest rst2pdf (0.93) for python 3.5

### ISSUE THREAD

**Issue by jbernardes** [rst2pdf/rst2pdf#955]
**Description of problem**

`rst2pdf-0.93.tar.gz` is actually `0.93.dev0` version. Latest version of `pip` prohibates this mismatch between archive name and metadata.

```bash
$ pip install --no-cache-dir -U rst2pdf
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Collecting rst2pdf
  Downloading rst2pdf-0.93.tar.gz (1.3 MB)
     |████████████████████████████████| 1.3 MB 1.4 MB/s
ERROR: Requested rst2pdf from https://files.pythonhosted.org/packages/7a/28/3c7e1d6d68165dc74a5b65ed3d2150caaeabb49952d38f639e97d37d6984/rst2pdf-0.93.tar.gz#sha256=3af44283ced19030a8286e8f8d71106ca6c78efe4bc95e9af42d678c363efcbc has different version in metadata: '0.93.dev0'

```
**Workaround 1**
Install a previous version of rst2pdf
```bash
$ pip install --no-cache-dir -U "rst2pdf<0.93"
...
Successfully installed rst2pdf-0.91
```
**Workaround 2**
Use a previous version of pip
```
$ pip install "pip<20.3"
$ pip install --no-cache-dir -U rst2pdf
Collecting rst2pdf
  Downloading rst2pdf-0.93.tar.gz (1.3 MB)
     |████████████████████████████████| 1.3 MB 1.0 MB/s
Building wheels for collected packages: rst2pdf
  Building wheel for rst2pdf (setup.py) ... done
  Created wheel for rst2pdf: filename=rst2pdf-0.93.dev0-py3-none-any.whl size=202045 sha256=a44fc1587e942a4667398141b3da33c4d684ebd30a02f01e42b6dbc627376bfe
  Stored in directory: /private/var/folders/1l/fkv5s8cx78183y29mvbrznn40000gn/T/pip-ephem-wheel-cache-1yuvh_c_/wheels/66/4b/5f/5b6b90fa40887d2e044843bada84e4a0e3378ab1a469a3a22c
Successfully built rst2pdf
Installing collected packages: rst2pdf
Successfully installed rst2pdf-0.93.dev0
```

**Workaround 3**
upgrade python in order to use rst2pdf>0.93 , not a aption if you have to use python 3.5 (e.g with debian stretch)

🖥 **Versions**

`python -V` Python 3.5.9
`pip --version` 20.3
rst2pdf 0.93 / 0.93dev0

Which operating system are you using? Mac os / Linux (debian stretch)

**Comment by lornajane** [comment]
Thanks for posting this and the workarounds, that's helpful. I'd **strongly recommend upgrading Python** when you can, the latest release of rst2pdf is 0.98 supported by Python 3.6 and later. I'll leave this issue open to make it easier to find in case others have unsupported versions and run into the same thing.

**Comment by stephenfin** [comment]
Hmm, actually, perhaps I was too hasty in closing this. The issue seems to be that we have no release that supports Python 3.5 and pip is falling back to 0.93 which is neither compatible with Python 3 nor packaged correctly. As discussed at https://github.com/rst2pdf/rst2pdf/issues/489#issuecomment-737287588, I'm now thinking we might want to release a 0.95.1 release that re-adds support for Python 3.4 and 3.5, just to tide anyone over that's using Ubuntu 16.04. Alternatively, we stay broken and acknowledge that we have no release that supports Python 3.5. Thoughts @lornajane @akrabat ?

**Comment by akrabat** [comment]
Given that 3.5 is a default in a distro, I think pip install should install an rst2pdf that stands a chance of working, so I think releasing a 0.95.1 makes sense. We clearly have no plans to support it in terms of fixes going forwards, but that's okay too as the obvious path is to upgrade your Python if you need a newer rst2pdf.

**Comment by akrabat** [comment]
rst2pdf v 0.95.1 released which will hopefully solve this.
