### ISSUE TITLE
Restrict artifact retention on GitHub to only failed tests

### ISSUE THREAD

**Issue by lornajane** [rst2pdf/rst2pdf#961]
**Description of problem**
When we run the tests, we store ALL the output when in fact we probably only need the files from any failed tests.

**Comment by stephenfin** [comment]
I don't understand how artefact retention works. Assuming it's just saving everything that exists after the build that didn't exist before, then we probably need to solve this via the test suite. Perhaps we can add a check for some environment variable that's present in the CI environment and delete the file in `output` if the test passes. Alternatively, we could always delete these files based on the assumption that a user will rarely, if ever, need to access them?

**Comment by lornajane** [comment]
The retention is done by path, so I first of all set it to retain everything in the output directory. I suggest we detect a failed test and copy the output files for that test to another directory `output_failed` and retain that instead.

**Comment by lornajane** [comment]
Already fixed in #987 , we just didn't tag it correctly
