### ISSUE TITLE
Images using figure directive that are too tall aren't resized and make rst2pdf abort

### ISSUE THREAD

**Issue by nfraprado** [rst2pdf/rst2pdf#966]
When an image that is too tall is included in a document using the `figure` directive, it isn't resized to fit the page and therefore makes rst2pdf abort the document generation.

**Description of problem**

Using the following document:

```
PDF Documents From Your Text Editor
###################################

.. figure:: image.png
```

where `image.png` is an image that is taller than the page. I included the one I was testing here:

[image](https://user-images.githubusercontent.com/43095212/103308861-44326a00-49f2-11eb-8748-21b19286a408.png)

In this document, rst2pdf isn't able to resize the image to fit the page and aborts:

```
Traceback (most recent call last):
  File "/usr/bin/rst2pdf", line 33, in <module>
    sys.exit(load_entry_point('rst2pdf', 'console_scripts', 'rst2pdf')())
  File "/home/nfraprado/cur/git/rst2pdf/rst2pdf/createpdf.py", line 1692, in main
    RstToPdf(
  File "/home/nfraprado/cur/git/rst2pdf/rst2pdf/createpdf.py", line 664, in createPdf
    pdfdoc.multiBuild(elements)
  File "/usr/lib/python3.9/site-packages/reportlab/platypus/doctemplate.py", line 1167, in multiBuild
    self.build(tempStory, **buildKwds)
  File "/usr/lib/python3.9/site-packages/reportlab/platypus/doctemplate.py", line 1080, in build
    self.handle_flowable(flowables)
  File "/home/nfraprado/cur/git/rst2pdf/rst2pdf/createpdf.py", line 815, in handle_flowable
    self.handle_frameEnd()
  File "/usr/lib/python3.9/site-packages/reportlab/platypus/doctemplate.py", line 726, in handle_frameEnd
    self.handle_pageEnd()
  File "/usr/lib/python3.9/site-packages/reportlab/platypus/doctemplate.py", line 668, in handle_pageEnd
    raise LayoutError(ident)
reportlab.platypus.doctemplate.LayoutError: More than 10 pages generated without content - halting layout.  Likely that a flowable is too large for any frame.
```

Changing the `figure` directive to `image`:

```
PDF Documents From Your Text Editor
###################################

.. image:: image.png
```

It succesfully resizes the image and everything works.

**Debugging:**

I dumped some information to investigate it further.

For the document using `figure`:

Doctree dump:

```
<document ids="pdf-documents-from-your-text-editor" names="pdf\ documents\ from\ your\ text\ editor" source="document1.rst" title="PDF Documents From Your Text Editor"><title>PDF Documents From Your Text Editor</title><figure><image uri="image.png"/></figure></document>
```

It is a `<image>` inside a `<figure>`.

Elements dump:

```
[MySpacer(0, 6.0), DelayedTable(
 rowHeights=[unknown],
 colWidths=['100%'],
'[unknown]'
) # end table, MySpacer(0, 0.0)]
```

And that gets converted to a `DelayedTable`. So the first thing would be to double check if that is supposed to be. But it makes sense, since `figure`s have a caption, so perhaps a table is being used to contain both the image and the caption.

The sizes:

```
IMG: 1218.8903225806453 x 4791.4838709677415
Avail: 457.88976377952764 x 71994
```

These sizes are compared to determine if the image should be resized or not. As you can see, the available size is `71994`, which is absurd. The maximum available size should be the page size, which is about `732`. So that's why the figure isn't resized and rst2pdf isn't able to create the pdf.

As a comparison, here are those dumps when using `image`:

Doctree dump:

```
<document ids="pdf-documents-from-your-text-editor" names="pdf\ documents\ from\ your\ text\ editor" source="document1.rst" title="PDF Documents From Your Text Editor"><title>PDF Documents From Your Text Editor</title><image uri="image.png"/></document>
```

Just an `<image>`.

Elements dump:

```
[<rst2pdf.image.MyImage object at 0x7fa79e2ff2b0>]
```

Gets converted to rst2pdf's `MyImage` class.

The sizes:

```
IMG: 1218.8903225806453 x 4791.4838709677415
Avail: 469.88976377952764 x 688.157480314961
[WARNING] image.py:424 Image /home/nfraprado/cur/rst2pdf/img-size/2/image.png is too tall for the frame, rescaling
```

Even though the image size is big, since the available height is right, it gets rescaled and displays correctly.

Here is a traceback of the moment it should resize using `figure` but doesn't (line numbers may be a bit off):
```
Traceback (most recent call last):
  File "/usr/bin/rst2pdf", line 33, in <module>
    sys.exit(load_entry_point('rst2pdf', 'console_scripts', 'rst2pdf')())
  File "/home/nfraprado/cur/git/rst2pdf/rst2pdf/createpdf.py", line 1692, in main
    RstToPdf(
  File "/home/nfraprado/cur/git/rst2pdf/rst2pdf/createpdf.py", line 664, in createPdf
    pdfdoc.multiBuild(elements)
  File "/usr/lib/python3.9/site-packages/reportlab/platypus/doctemplate.py", line 1167, in multiBuild
    self.build(tempStory, **buildKwds)
  File "/usr/lib/python3.9/site-packages/reportlab/platypus/doctemplate.py", line 1080, in build
    self.handle_flowable(flowables)
  File "/home/nfraprado/cur/git/rst2pdf/rst2pdf/createpdf.py", line 768, in handle_flowable
    if frame.add(f, canv, trySplit=self.allowSplitting):
  File "/home/nfraprado/cur/git/rst2pdf/rst2pdf/flowables.py", line 641, in add
    return Frame.add(self, flowable, canv, trySplit)
  File "/usr/lib/python3.9/site-packages/reportlab/platypus/frames.py", line 174, in _add
    w, h = flowable.wrap(aW, h)
  File "/home/nfraprado/cur/git/rst2pdf/rst2pdf/flowables.py", line 252, in wrap
    return self.t.wrap(w, h)
  File "/usr/lib/python3.9/site-packages/reportlab/platypus/tables.py", line 1218, in wrap
    self._calc(availWidth, availHeight)
  File "/usr/lib/python3.9/site-packages/reportlab/platypus/tables.py", line 665, in _calc
    self._calc_height(availHeight,availWidth,W=W)
  File "/usr/lib/python3.9/site-packages/reportlab/platypus/tables.py", line 589, in _calc_height
    dW,t = self._listCellGeom(v,w or self._listValueWidth(v),s)
  File "/usr/lib/python3.9/site-packages/reportlab/platypus/tables.py", line 422, in _listCellGeom
    vw, vh = v.wrapOn(canv, aW, aH)
  File "/usr/lib/python3.9/site-packages/reportlab/platypus/flowables.py", line 125, in wrapOn
    w, h = self.wrap(aW,aH)
  File "/home/nfraprado/cur/git/rst2pdf/rst2pdf/image.py", line 413, in wrap
    raise TypeError("a")
TypeError: a
```

Ignore the type error at the end, I just used it to get a stack dump.

I followed it to find where that ~70k was coming from, and found the following:

In reportlab's platypus/tables.py line 412 (https://hg.reportlab.com/hg-public/reportlab/file/tip/src/reportlab/platypus/tables.py#l412):
```
def _listCellGeom(self, V,w,s,W=None,H=None,aH=72000):
```

The default value for that variable is 72000, and it is used to calculate and return something about the height.

In reportlab's platypus/tables.py line 587:
```
dW,t = self._listCellGeom(v,w or self._listValueWidth(v),s)
```

That's where it is calling that function, and since `aH` isn't passed, the default 72000 is used.

So, after all that, I'm confused on how to go on, so I'm posting my findings here go get some feedback. I'm not sure if the usage of that 72k value is wrong, since that is supposed to be used with tables, and perhaps tables can continue between pages so it's right to have a big value? I'm not sure. Any help would be appreciated.

🖥 **Versions**

`python -V`: 3.9.1

`pip freeze | grep rst2pdf`: 0.98

`pip freeze | grep reportlab`: 3.5.57

Which operating system are you using? Archlinux

**Comment by lornajane** [comment]
This is really valuable information, I'm not sure what to do next either but it's very useful to have a simple replication case.

I notice that I do get a warning which at least says _which_ image is causing the problem, I'm not sure all flowable errors have this much information so it's good that image does.

```
[WARNING] image.py:423 Image /home/lorna/projects/rst2pdf/image.png is too wide for the frame, rescaling
```

My workaround for this is to specify a width property. Not ideal if the source needs to be reusable but in case anyone is running into this before we fix it, try this:

```
.. figure:: image.png
   :width: 2.5cm
```

However I am also keen to understand if we can pass more information to reportlab - one thing to look out for with rst2pdf is that most of the codebase is very old indeed so many of the dependent libraries and other features simply didn't exist when it was created, and there are better ways to do things today.

**Comment by lornajane** [comment]
I was wondering why we had both image and figure, and it turns out that they do different things. The image is just an image, but the figure is an image and a caption. See https://docutils.sourceforge.io/0.4/docs/ref/rst/directives.html#images

**Comment by t-8ch** [comment]
I managed to get a correctly scaled figure by modifying `HandleFigure` to use `reportlab.platypus.figures.ImageFigure` instead of the table.
There are two main issues so far:
* The `reportlabs.platypus.figures` is not a public/documented API of reportlabs
  * The figure functionality could be lifted from reportlabs and copied into rst2pdf (maybe switching it over when it becomes an official API)
* The example image is rendered incorrectly
   * Instead of using `ImageFigure` it may make sense anways to create a custom subclass of `FlexFigure` that works together with the rest of rst2pdf.

The scaling logic from `FlexFigure` has more knowledge about the content to be scaled (one caption, one figure) than the logic from `Table`, so it seems to be more robust.

**Comment by akrabat** [comment]
This is a generic problem with tables as a table with an image that's too tall will also fail and so also affects lists such at numbered, bullets & definitions as well as affecting figures as implemented today. 

The basic issue is that ReportLab assumes that "tall" data in a table cell can be rendered across page boundaries. This is not true for images.

Hence we need `MyImage` to resize the image if it is too tall for page, but as @nfraprado noted, the value of `availHeight` passed to `wrap()` is 72000 (- padding), so we need to get the correct height to it. 

I have a solution in #1024 where the table instance sets `max_page_height` on the image before `wrap()` is called, so that the correct maximum height can be used for resizing.

**Comment by akrabat** [comment]
@t-8ch There is most definitely a case to be made that `.. figure::` should not use a table! If there's a better solution within ReportLab, we should look at it.

Similarly, we should probably look at whether we still need tables for bullet and numbered lists as they are pain to style at the moment.
