### ISSUE TITLE
Sphinx version is outdated, update it and fix side-effects

### ISSUE THREAD

**Issue by lornajane** [rst2pdf/rst2pdf#984]
**Description of problem**

We are pinned to Sphinx 1.8.5 at the moment, which is quite outdated but there are breaking changes from where we are to the newest release. However we always want to keep up with releases so this issue is here to co-ordinate our efforts to update, understand the side effects, update the tests, etc.

This originates from #969 where we updated other libraries but this one caused a problem.

**Comment by akrabat** [comment]
If you have a more recent build than 1.8.5, these tests will fail with a different index or table of contents:

* sphinx-issue172
* sphinx-issue318
* sphinx-issue319
* sphinx-issue320

**Comment by lornajane** [comment]
see also #749

**Comment by lupino3** [comment]
As a data point, rst2pdf works for my project (edumips64) with Sphinx 3.5.4, but breaks with 4.0.2 with the error in #1014.

**Comment by akrabat** [comment]
Fixed when #1020 is merged..
