### ISSUE TITLE
rst2pdf fails to write output to stdout

### ISSUE THREAD

**Issue by olivierfriard** [rst2pdf/rst2pdf#991]
Hello, the following command gives me an error:

```
rst2pdf test.rst -o -

Traceback (most recent call last):
  File "/home/olivier/.virtualenvs/tucc/bin/rst2pdf", line 8, in <module>
    sys.exit(main())
  File "/home/olivier/.virtualenvs/tucc/lib/python3.8/site-packages/rst2pdf/createpdf.py", line 1683, in main
    RstToPdf(
  File "/home/olivier/.virtualenvs/tucc/lib/python3.8/site-packages/rst2pdf/createpdf.py", line 659, in createPdf
    pdfdoc.multiBuild(elements)
  File "/home/olivier/.virtualenvs/tucc/lib/python3.8/site-packages/reportlab/platypus/doctemplate.py", line 1177, in multiBuild
    self.canv.save()
  File "/home/olivier/.virtualenvs/tucc/lib/python3.8/site-packages/reportlab/pdfgen/canvas.py", line 1277, in save
    self._doc.SaveToFile(self._filename, self)
  File "/home/olivier/.virtualenvs/tucc/lib/python3.8/site-packages/reportlab/pdfbase/pdfdoc.py", line 222, in SaveToFile
    f.write(data)
TypeError: write() argument must be str, not bytes
```

I obtained the same error using this command:

```
cat test.rst | rst2pdf 
```

The content of my test.rst file is:

```
Title
###########

Header
============

some text 
```

```
python3 --version
Python 3.8.5
rst2pdf --version
0.98
```

thank you
Best regards
Olivier

**Comment by lornajane** [comment]
I'm not sure `rst2pdf` is intended to be able to write to stdout, the usage hints suggest not (either you supply a filename, or it generates one), so I'm not sure it's a bug. Can you say a little about what you were trying to do and why you'd find this feature useful?

**Comment by olivierfriard** [comment]
The feature is described in the manual. See https://rst2pdf.org/static/manual.html#pipe-usage
It should be very useful for using rst2pdf behind a web server
Thanks
Olivier

**Comment by lornajane** [comment]
I've had a dig around and this looks like a reportlab bug, if you literally dig in and modify that `f.write(data)` to be `f.write(str(data))` then it seems to spit out the PDF. I think some of this changed with the python2 to python3 upgrade, I'm not sure if we can somehow wrap it on our side

**Comment by olivierfriard** [comment]
Yes `f.write(str(data))` works for the stdout but not for creating a file (a bytes-like object is required, not 'str')
So I replaced 
`f.write(data)`
by
```
       try:
            f.write(data)
        except TypeError:
            f.write(str(data))
```
It works for the stdout and for creating a file

**Comment by lornajane** [comment]
I'm starting to feel uneasy about our reportlab dependency. That project does not have a public issue tracker or source code repository, so I'm not sure how to get things fixed upstream. There's a mailing list but I'm not sure they actually want people to use it now I've read the last few messages. Other things I found on my travels:
 * The mailing list: https://pairlist2.pair.net/mailman/listinfo/reportlab-users
 * A code mirror (but I think the hg repo has gone offline now) https://github.com/MrBitBucket/reportlab-mirror
 * xhtml2pdf depends on reportlab (https://github.com/xhtml2pdf/xhtml2pdf) but it looks like similar project WeasyPrint doesn't (https://github.com/Kozea/WeasyPrint)
